### ISSUE TITLE
Add Option to let Workers inherit Working Directory

### ISSUE THREAD

**Issue by maxmunzel** [rq/rq#1007]
Hey Everyone,
thank you for your awesome library! 

I'm currently using it from a command line app and its pretty awkward that due to the worker having a different working directory I cant pass relative links to arguments. I'm therefor wondering, wether it was possible to add a `inherit_pwd: bool = False`-esque parameter to `Queue.enqueue()`. 

I'm not as deep in the internals to know wether or not this would break the `pickle`-ing, but if I get green lights from you, that this would be a worthwile feature, I'd be happy to implement it and open a pull request.

Kind regards

Max

**Comment by selwin** [comment]
You can use `--path` cli argument when running the worker (`rq worker --path foo`) to add your working directory to RQ worker. Let me know if this solves your issue.

**Comment by maxmunzel** [comment]
Thank you for your answer, I’ll take a look at it!
