### ISSUE TITLE
rq memory leak on task failing

### ISSUE THREAD

**Issue by craynic** [rq/rq#1008]
A job failed in my worker:
> Traceback (most recent call last):
   File "/root/.local/share/virtualenvs/app-I4rustzo/lib/python2.7/site-packages/rq/worker.py", line 793, in perform_job                                
     rv = job.perform()                          
   File "/root/.local/share/virtualenvs/app-I4rustzo/lib/python2.7/site-packages/rq/job.py", line 599, in perform                                       
     self._result = self._execute()              
   File "/root/.local/share/virtualenvs/app-I4rustzo/lib/python2.7/site-packages/rq/job.py", line 605, in _execute                                      
     return self.func(*self.args, **self.kwargs) 
 TypeError: new_job() takes exactly 1 argument (20 given)  

This is because the given arguments cannot fit in the function to execute.
Unfortunately, the worker listens on the failed queue, so the failed job came to a dead loop.
We found that the memory usage grew slowly. By counting the objects, we found that tuple objects and function objects were keeping growing. I believe it is a memory leak.
I'm on rq 0.12.0, python 2.7.

**Comment by selwin** [comment]
Does this only happen on a worker that continuously perform the same failing job, over and over again? Are you seeing this behavior on regular RQ use?

Which worker class did you use? `Worker` or `SimpleWorker`?

**Comment by craynic** [comment]
Not one same failing job. When we found it, there are 10k+ failing jobs keep running. The jobs have same function and same args. It looks good on regular use.
We use `SimpleWorker`.

**Comment by craynic** [comment]
Using `Worker` may be too heavy in my case. 
When I have time I will test it in local env.

**Comment by selwin** [comment]
Please reopen the issue if your investigation shows that the leak is happening on the RQ side and not your application code.

If RQ has a memory leak, I'd love to fix it.
