### ISSUE TITLE
Not all the worker resisted into Redis if launch multiple worker concurrency

### ISSUE THREAD

**Issue by alvin1** [rq/rq#1013]
Some background:
- Using Linux as my working environment, python version 3.6, already set `FLASK_APP` environment variable
- I'm using Flask-RQ2 (https://github.com/rq/Flask-RQ2) to make rq working with Flask.
- I have some work spaces and each work space has its own queue.
- I need to launch some worker to process jobs in these queues.
- I'm using supervisor / bash to launch the workers
- I'm using rq-dashboard to monitoring and check the worker status

Issues:
- When I start worker with supervisor, all the worker process start up, but when I check the workers in rq-dashboard, not all the workers list there, and not have any useful information to help investigate the issues.
- I tried to launch worker with bash script instead of supervisor, the issue still there if not sleep 1 second each time launch a worker.

Supervisor configuration:
```
[program:worker_1]
command=flask rq worker -n worker_1 workspace1 workspace2 workspace3
killasgroup=true
stopasgroup=true
redirect_stderr=true
stdout_logfile_maxbytes=0
stdout_logfile=/var/logs/rq_worker/worker_1.log
```

**Comment by selwin** [comment]
This may be caused by `-n worker_1`, this tells RQ to use `worker_1` as the name of your workers. If you spawn multiple instances of these workers they may not work correctly. Try removing the `-n` arg.
