### ISSUE TITLE
Support for Sentry SDK

### ISSUE THREAD

**Issue by selwin** [rq/rq#1017]
- [ ] `rq worker` script should accept `--sentry-sdk-dsn` parameter (and raise `DeprecationWarning` when `--sentry-dsn` is passed used. This happens here:
https://github.com/rq/rq/blob/master/rq/cli/cli.py#L233

- [ ] Deprecate `SENTRY_DSN` in favor of `SENTRY_SDK_DSN` in settings file. This happens https://github.com/rq/rq/blob/051104b0ffc3a3b25438679be04a10bc5285718b/rq/cli/cli.py#L198

- [ ] Deprecate the reading of `SENTRY_DSN` from environment variable in favor of `RQ_SENTRY_SDK_DSN`. This happens https://github.com/rq/rq/blob/051104b0ffc3a3b25438679be04a10bc5285718b/rq/cli/cli.py#L185

**Comment by untitaker** [comment]
I would prefer to have the integration removed and would also like to see other RQ maintainers chime in on that. I still think this is a good plan under the assumption that the code in RQ must stay.

**Comment by samuelcolvin** [comment]
I'm a little foggy on the background to all this in #1003.

But looking at it from a distance, surely `--sentry-dsn` is more intuitive than `--sentry-sdk-dsn` and `SENTRY_DSN` is more intuitive than `SENTRY_SDK_DSN`? Not at all clear why `sdk`/`SDK` adds any information or is any more specific.

The only exception to this I guess would be an environment (eg. heroku) where you want the `SENTRY_DSN` env variable to be set but not used by rq. In this case, I can imagine also having `RQ_SENTRY_DSN` which overrides `SENTRY_DSN` and allows for special values like `'-'` or `'none'` which disables sentry for rq.

**Comment by untitaker** [comment]
@samuelcolvin this is done for backwards compatibility reasons. `--sentry-dsn` is already used to drive the raven SDK, and swapping it out with the new SDK is a breaking change.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1045

**Comment by selwin** [comment]
Docs here: https://python-rq.org/patterns/sentry/
