### ISSUE TITLE
HerokuWorkerShutdownTestCase failing

### ISSUE THREAD

**Issue by selwin** [rq/rq#1019]
@samuelcolvin after support for Redis 3.0 was merged into master, `HerokuWorkerShutdownTestCase.test_1_sec_shutdown` [started failing](https://travis-ci.org/rq/rq/jobs/462599271) on PyPy.

Do you mind taking a look at this? Or should we just skip the entire `HerokuWorkerShutdownTestCase` under PyPy since it's not on Heroku's [list of supported Python runtimes](https://devcenter.heroku.com/articles/python-support#specifying-a-python-version)?

**Comment by samuelcolvin** [comment]
definitely let's skip it, pypy's behaviour with exit codes differs significantly from cpython.

see #1020.
