### ISSUE TITLE
SimpleWorker - ImportError

### ISSUE THREAD

**Issue by maxisme** [rq/rq#1021]
I am looking for a solution to this:

https://stackoverflow.com/questions/52098967/python-redis-queue-rq-how-to-avoid-preloading-ml-model-for-each-job

in my case I have attempted this:
```
listen = ['high', 'low']
redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')
conn = redis.from_url(redis_url)

d = detecter.Detecter()
if __name__ == '__main__':
    with Connection(conn):
        worker = SimpleWorker(list(map(Queue, listen)))

        # use sentry with worker
        client = Client(config.SENTRY_URL, transport=HTTPTransport)
        register_sentry(client, worker)

        worker.work()
```
as one thread. And this as my request:

```
redis_conn = Redis()
Queue('high', connection=redis_conn, default_timeout=60).enqueue('d.run', img)
```

Unfortunately this is returning:

```
ImportError: No module named d
```

Effectively I am trying to run the function `d.run()` (which can only be run in a single thread) with a priority.

**Comment by selwin** [comment]
Your workers would have to be able to import `d`. Please check your worker's python path config.
