### ISSUE TITLE
Doc pages disagree about Redis version requirements?

### ISSUE THREAD

**Issue by hartwork** [rq/rq#1023]
Hi!

https://github.com/rq/rq/blob/master/docs/patterns/index.md reads `redis==2.10.5` while https://github.com/rq/rq/blob/master/docs/index.md reads `RQ requires Redis >= 3.0.0`.

Is that intended?

**Comment by hartwork** [comment]
I see!

So the fix would be to make https://github.com/rq/rq/blob/master/docs/patterns/index.md read `redis==3.0.0` to be in sync?

**Comment by selwin** [comment]
Version 0.13 which supports Redis 3 is now out on PyPI. https://pypi.org/project/rq/

**Comment by hartwork** [comment]
Actually, that would be a great occasion to get https://github.com/rq/rq/blob/master/docs/patterns/index.md back in sync now, right?

How about:
```
redis==3.0.1 
rq==0.13.0
```
?

@selwin please re-open this ticket. Thank you!

**Comment by selwin** [comment]
@hartwork I just updated the docs here: https://github.com/rq/rq/commit/22f004f7d6953b4ac9bae02712710fc87a342e4b :)
