### ISSUE TITLE
Queue status check

### ISSUE THREAD

**Issue by abitrolly** [rq/rq#1027]
Does `rq` provide an API to monitor queue status and errors? I am reading the website and don't see anything.

For example https://release-monitoring.org/ uses cron job on different server to check releases. When this job fails, users can't see that. The solution could be to write a custom script that interacts with server with a cron job, checks pid, error status, logs, whatever. Would it be easier to use `rq` for managing request queue and expose the queue status to users (meaning that cron job will be replaced by worker)? Does `rq` support that out of the box?

**Comment by selwin** [comment]
The only thing that we have built in is `rq info` CLI command. This allows you to monitor the status of your queues.

Aside from that, other libraries like https://github.com/rq/django-rq and https://github.com/eoranged/rq-dashboard provides web interfaces that allow you to monitor queue and job status, but those projects were built separately.

Let me know if you have an idea of what hooks RQ can provide to make monitoring easier.

**Comment by abitrolly** [comment]
https://python-rq.org/docs/monitoring/ should be fine for now. Explicit REST API would be useful - how many workers (if possible) are active, what is the status of each worker, what are historical stats for each worker. The dashboards already look good for that purpose.

**Comment by abitrolly** [comment]
I remembered that I needed to know from Python how many workers are online and what is their status (busy, processing, offline). Having a status of the queue is also important - if there is a green worker and work queue is full, then something is not right.
