### ISSUE TITLE
logging_level=WARN still produces INFO logs

### ISSUE THREAD

**Issue by amir20** [rq/rq#1029]
I am losing my mind here. I am trying to make the logging less verbose. This is my worker file: 

```py
import sys

from rq import Connection, Worker

from mypackage import redis_connection


def main():
    with Connection(connection=redis_connection):
        qs = sys.argv[1:] or ['default']
        w = Worker(qs)
        w.work(logging_level='WARN')


if __name__ == "__main__":
    main()
```

However, in the logs I still see `INFO:rq.worker:player: clashleaders.queue.player.update_players...`

Am I doing something wrong?  I am using `rq==0.13.0`

By the way, thanks for the great library. The API is very nice.

**Comment by selwin** [comment]
Please open a PR if you think this is a bug.

**Comment by selwin** [comment]
This should be fixed in https://github.com/rq/rq/pull/1059/commits/620e79858bbd44364d7419bd4291777a21df4694
