### ISSUE TITLE
Work-horse process was terminated unexpectedly on version 0.13.0

### ISSUE THREAD

**Issue by agmathew** [rq/rq#1038]
I recently upgraded rq to 0.13.0 from 0.10.0 and found that all jobs would fail with a 'Work-horse process was terminated unexpectedly (waitpid returned 256)' error. When I downgraded to 0.12.0, everything seemed to work again. I'm using Redis 3.2.12 on Heroku. Let me know if I can provide any more information.

**Comment by selwin** [comment]
RQ 0.13 requires redis-py>=3. Check that you have the correct version of that library installed.
