### ISSUE TITLE
warning: Moving job to 'failed' queue (work-horse terminated unexpectedly; waitpid returned 9

### ISSUE THREAD

**Issue by alaamub** [rq/rq#1041]
I'm sending a large object to the worker and sounds like the worker has died with the message `warning: Moving job to 'failed' queue (work-horse terminated unexpectedly; waitpid returned 9` is there a way to see why is this happening? I don't see any other logs. could increasing the timeout solve this problem?

**Comment by alaamub** [comment]
turns out the job needs more memory.

**Comment by garaujo9412** [comment]
How do you gave more memory to the job, i've been messing with maxmemory and maxmemory policy on redis.conf and till now i can't run my job! it is a awfully huge job

**Comment by raveenb** [comment]
memory was the key here, I was running it inside a docker container and it would throw this error. bumping memory up removed this problem, I was loading a large data frame

**Comment by janzjos** [comment]
@raveenb - how did you bump up memory on this issue?  when i look at my docker-compose settings and stats, there are no limits.  when i run without the rq, it completes just fine.  thank you

**Comment by raveenb** [comment]
@janzjos I was running inside of an AWS container, so moved to a container with larger memory. docker will use up as much memory there is if you don't configure it.

**Comment by zachliu** [comment]
i saw the same error. i'm running it inside a k8s pod, i just increased the memory limit and it's fine now

**Comment by Stephane-Ag** [comment]
Having the same error. Using k8s pods in AWS EKS and increasing resource memory settings does nothing for me.
