### ISSUE TITLE
coverage module not collecting task coverage

### ISSUE THREAD

**Issue by bmbouter** [rq/rq#1051]
We have functional tests that run RQ tasks to test our RQ tasks. We have the coverage module running rq like this:

`rq worker -n 'reserved-resource-worker-1@%h' -w 'pulpcore.tests.functional.worker_with_coverage.CoveragePulpWorker' -c 'pulpcore.rqconfig' >> ~/reserved_worker-1.log 2>&1 &`

The `CoveragePulpWorker` starts and stops coverage and runs our custom worker (needed for some customization of our RQ application). It's a pretty simple script:

```
import sys
import coverage

from pulpcore.tasking.worker import PulpWorker


class CoveragePulpWorker(PulpWorker):
    def perform_job(self, job, queue):
        cov = coverage.Coverage()
        cov.start()

        super().perform_job(job, queue)

        print('writing coverage', file=sys.stderr)
        cov.stop()
cov.save()
```

And yet tasks that we know run due to log output are not being reported in the coverage report when we see it. It is correctly recording various aspects of the worker's code, but it is *not* recording any code running after the fork point.

How do you get coverage from your RQ tasks?

**Comment by selwin** [comment]
Not sure about coverage, but you should try running the task using `SimpleWorker` which runs jobs in the same process as your test process.

**Comment by bmbouter** [comment]
Thank you, I think we will try using SimpleWorker instead for these things.
