### ISSUE TITLE
shared Instance of class

### ISSUE THREAD

**Issue by pinkynrg** [rq/rq#1054]
I have 2 jobs A, B that needs to be executed by the same worker:

A. This Job needs to refresh the instance of a Driver class if some configuration data has changed by the user. Executes every 5 seconds. 
B. This Job reads data from a hardware controller using the Driver class instance. 

What is the best approach to share an instance of class across jobs?

**Comment by selwin** [comment]
This is not an RQ related question but rather how you structure your application logic.
