### ISSUE TITLE
Getting the worker while handling a job?

### ISSUE THREAD

**Issue by tshead** [rq/rq#1057]
I’m hacking together a computer graphics render farm, and RQ has been a big help, many thanks!

A natural use-case in this domain would be one job (“render sequence”) that spawns many new jobs (“render frame 1”, “render frame 2”, …).  To do this, I’m using a custom worker class that sets a static variable to the connection passed to its `__init__`, so I can use that connection to create a new queue without having to know the redis connection info passed to the worker on the command line / config.

This is all working fine, I’m just wondering if there’s a better way that I’ve overlooked.  Any suggestions welcome.

Cheers,
Tim

**Comment by selwin** [comment]
I will accept pull requests for `get_current_worker()` :). The implementation should be similar to [get_current_job](https://github.com/rq/rq/blob/d9798fd64f9811d0f076ba09d40e3374e5841609/rq/job.py#L74).

**Comment by tshead2** [comment]
Sure, I'll take a crack at it.  I had a similar question about jobs anyway, I wasn't aware of get_current_worker().

Cheers,
Tim

**Comment by tshead** [comment]
Once I started working on this, I realized that `get_current_job()` and `get_current_connection()` both give me everything I should ever need.  I was able to greatly simplify my code by using them, instead of my previous workaround.  Upon deeper reflection, I think `get_current_worker()` might be a bit of a hack anyway, as it would tend to blur the clean separation of concerns.

Would you consider a PR with sphinx-doc support instead?

**Comment by selwin** [comment]
I'd welcome any documentation PRs, but would rather not switch to a different docs system/framework for now. To contribute to our docs, please open a PR and modify the markdown files in the `docs` directory.

**Comment by tshead** [comment]
Closing this issue in the meantime.
