### ISSUE TITLE
rqworker failing to start from project directory

### ISSUE THREAD

**Issue by snkashis** [rq/rq#106]
I seem to be having a problem launching rqworker from inside my otherwise normally-functioning project directory.
It's throwing

Traceback (most recent call last):
  File "/usr/local/bin/rqworker", line 9, in <module>
    load_entry_point('rq==0.2.2', 'console_scripts', 'rqworker')()
  File "/usr/local/lib/python2.7/dist-packages/rq/scripts/rqworker.py", line 66, in main
    w.work(burst=args.burst)
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 269, in work
    self.register_birth()
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 181, in register_birth
    with self.connection.pipeline() as p:
AttributeError: **exit**

I pipped this install of rq.
I am able to launch it fine with sudo, but then I have issue with proper paths(tasks come in, but cannot find modules) and I don't see any examples requiring to fire it up with sudo.

Any ideas?

**Comment by mateocam** [comment]
@nvie how can I do this: You're saying it can't find modules. Are you running the RQ worker in the project root? If not, you can adjust the PYTHONPATH using the -P flag to the worker:

--path PATH, -P PATH  Specify the import path.

I have my rq worker inside a folder in the root directory and I am getting ImportError: no module named xxxx.

I have a flask app, where do I change the PYTHONPATH ? is it in the worker file or in the Procfile ?
