### ISSUE TITLE
funding for rq (at least a little bit)

### ISSUE THREAD

**Issue by samuelcolvin** [rq/rq#1060]
https://tidelift.com/lifter/search/pypi/rq

![image](https://user-images.githubusercontent.com/4039449/55007289-11667100-4fd7-11e9-9e58-d8e080e3ddb8.png)

@selwin, you do a lot of work on rq and I'm sure a lot of people (myself and my company included) appreciate that a lot.

Perhaps you should start collecting a little funding for your work and perhaps promote the tidelift link to encourage others to contribute financially so the amount could increase.

(disclaimer: I have nothing to do with tidelift, I've done absolutely not investigation, this might all be smoke and mirrors.)

**Comment by selwin** [comment]
Thanks, will look into this sometime in the near future.

**Comment by dfrankow** [comment]
This is a good idea.

A related idea: is there an easy way for people to bid on getting (github-filed) issues resolved? That might help both selwin and the community of RQ.

**Comment by samuelcolvin** [comment]
Not that I know of, probably best to email @selwin and me if you really want something fixing and offer to pay us (@selwin best as he really runs rq).

Side note: there's also [github sponsors](https://help.github.com/en/articles/about-github-sponsors) which AFAIK is a colaboration between tide and github.

**Comment by dfrankow** [comment]
email addresses?

**Comment by samuelcolvin** [comment]
Mine is s@muelcolvin.com, I can get @selwin's email address from `git log`.

**Comment by dfrankow** [comment]
Great, thanks.

Turns out there is a place for sponsoring issue resolution: BountySource. https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

I've never used it. Random Internet sources say: it started in 2003, was a VC-backed company, then went volunteer-run, has had [some issues](https://github.com/bountysource/core/issues/1147) with the github integration.

**Comment by dfrankow** [comment]
But they're still paying out bounties: https://twitter.com/Bountysource

**Comment by selwin** [comment]
I've enrolled RQ on Tidelift, if anyone happens to be a sponsor on Tidelift, please consider supporting RQ [via this link](https://tidelift.com/subscription/pkg/pypi-rq?utm_source=pypi-rq&utm_medium=referral&utm_campaign=readme) :).

![rq 2019-06-07 21-19-56](https://user-images.githubusercontent.com/188658/59110790-05e5dd80-896a-11e9-9c8b-0b5ca797748f.jpg)
