### ISSUE TITLE
RQ Worker Crash Time Delta

### ISSUE THREAD

**Issue by miha93** [rq/rq#1061]
A worker sometime crash with the following error and are unable to restart until I clear the task queue and the failed queue. 

ValueError: time data '2019-03-30T06:07:00.000000Z' does not match format '%Y-%m-%dT%H:%M:%S.%f+00:00'
 
Anyone seen this before we are using python2.7 RQ version 0.7.1

**Comment by selwin** [comment]
You probably have a job that's created by an older version of RQ. Upgrade to version 1.0 :)
