### ISSUE TITLE
1.0 release date

### ISSUE THREAD

**Issue by haoleman** [rq/rq#1062]
Great library. just wondering when 1.0 will be officially released

**Comment by selwin** [comment]
Hopefully this weekend :)

**Comment by mlissner** [comment]
Are there release notes? I'm doing a big evaluation of rq vs huey vs celery right now. If rq is about to change, I'd love to know what's coming, if possible (didn't see anything in the docs directory).

My analysis is here, if it's interesting/useful/etc: https://docs.google.com/spreadsheets/d/1Q_v__QtYzDtIDOkfmeQqVAw_jiksBz-GbJn-m-pDM34/edit?usp=sharing

**Comment by peterfarrell** [comment]
@mlissner Nice comparison doc you made. Celery removed the ability to email on failed tasks in version 4.x.

**Comment by mlissner** [comment]
Yeah, it's pretty ad hoc, but it's getting there. Totally forgot the email on failed task thing is gone in 4.x. It's for the best. We rely on it, but we shouldn't because every now and then it sends us 10k emails...

**Comment by selwin** [comment]
@mlissner you can see the changelog here: https://github.com/rq/rq/blob/master/CHANGES.md

RQ 1.0 is now up on PyPI :)
https://pypi.org/project/rq/

**Comment by selwin** [comment]
@mlissner I was just checkout out the docs you made. The "Resume tasks after clean shutdown" should be marked as "Yes", RQ puts jobs that don't finish after a 30 seconds grace in period in `FailedJobRegistry`. Or does it mean a different thing?

**Comment by mlissner** [comment]
@selwin, that refers to bug #802, which I thought meant that if the worker is shut down while working on a task, that task isn't put back on the queue cleanly.
