### ISSUE TITLE
Worker documentation omissions/tweaks

### ISSUE THREAD

**Issue by mlissner** [rq/rq#1065]
Two small things. First, these options aren't documented [on the worker page](https://python-rq.org/docs/workers/#worker-arguments):

    --results-ttl INTEGER           Default results timeout to be used
    --worker-ttl INTEGER            Default worker timeout to be used

So that's interesting!

Second, I might be misunderstanding this, but shouldn't the docs recommend that the worker be started with the `default` queue as well? So, rather than showing this:

    rq worker high normal low

The docs should show:

    rq worker high normal default low

Or:

    rq worker high default low

Unless I had an error in my test, if you don't do something like that your tasks will normally go to the `default` queue, where they'll go unprocessed. Not so good!

**Comment by selwin** [comment]
Yeah, we should probably add `--results-ttl` to the docs.

I'm not too sure about `--worker-ttl` as I feel that this is something that RQ should handle on behalf of the user. I have plans to change this sometime in the near future as I work on building job scheduling into RQ proper (taking the best features of `rq-scheduler` and bringing it in should make RQ more pleasant to use).

> Second, I might be misunderstanding this, but shouldn't the docs recommend that the worker be started with the default queue as well
Well, if you instantiate a `Queue` without specifying a name, it defaults to `default`. Similarly, if you start `rq worker` without specifying queue names to process, it listens on the `default` queue. I'll probably change the `normal` to `default` just to avoid any confusion.

**Comment by mlissner** [comment]
> Yeah, we should probably add --results-ttl to the docs.

Great! 

> I'm not too sure about --worker-ttl as I feel that this is something that RQ should handle on behalf of the user.

Do you mean "this is something that RQ should *not* handle on behalf of users"? Either way, I think it should be documented, even if the docs say, "This feature is planned for deprecation."

> I'll probably change the normal to default just to avoid any confusion.

That makes the most sense to me, yep.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/commit/2af3d829b09c6243148a561b0495965c95a27db0
