### ISSUE TITLE
Document retrying jobs

### ISSUE THREAD

**Issue by mlissner** [rq/rq#1067]
There's the easy way, which is just to document `job.requeue()` on the jobs documentation page:

https://github.com/rq/rq/blob/master/rq/job.py#L527

I could be wrong, but I don't think that (super important) method is actually documented anywhere! I found it by searching the Github issues. 

---

And there's the hard way, which would be to provide this information with a full example of using exception handling to retry a task with exponential backoff. I think that's a *very* frequent use case, and I've spent a lot of time trying to figure it out today. 

As a Celery refugee, this is really frustrating because in Celery you just use a decorator on your job, and this is easy-peasy.

Thanks.

**Comment by taewookim** [comment]
Wow. Didnt even know that. Thanks @mlissner 

However, is there a way to set MAX retry with exponential back off with requeue?

**Comment by mlissner** [comment]
> However, is there a way to set MAX retry with exponential back off with requeue?

Sorry, as I said in #234, I wasn't able to get rq working.

**Comment by lowercase00** [comment]
This is documented [here](https://python-rq.org/docs/jobs/#requeuing-failed-jobs) and [here](https://python-rq.org/docs/jobs/#requeuing-failed-jobs). Feel free to reopen if there's anything else missing.
