### ISSUE TITLE
is it possible to send job in to a queue using python asyncio feature?

### ISSUE THREAD

**Issue by wojtek-fliposports** [rq/rq#1069]
is it possible to send job in to a queue using python asyncio feature?

**Comment by japrogramer** [comment]
why would you need to .. since the job is queued into the redis store.

do you mean to have async defs for the queued function ?

**Comment by samuelcolvin** [comment]
No it's not, but there's [arq](https://github.com/samuelcolvin/arq) (admission: I built arq) which is an async success or to rq.

> why would you need to .. since the job is queued into the redis store.

Because you're using an async framework therefore don't want to block the main thread while sending data to redis.

**Comment by hongquan** [comment]
@samuelcolvin Can `arq` be used in coordination with `rq`? My project is both sync and async (using Django-Channels). I want to enqueue job from synchronous Django view as well as from asynchronous WebSocket consumer.

Currently, I have to use Django-Channels' [`sync_to_async`](https://github.com/django/asgiref/blob/master/asgiref/sync.py#L303) to wrap the call to `task.enqueue`. However, it will be nice if I can use `aioredis` directly.
