### ISSUE TITLE
broken code in landing page documentation for `enqueue_call` timeout parameter

### ISSUE THREAD

**Issue by shaunharker** [rq/rq#1071]
The landing page docs at http://python-rq.org/docs/ gives the example

```python
q = Queue('low', connection=redis_conn)
q.enqueue_call(func=count_words_at_url,
               args=('http://nvie.com',),
               job_timeout=30)
```

but this yields `TypeError: enqueue_call() got an unexpected keyword argument 'job_timeout'` since the function accepts instead a `timeout` parameter:

```python
   def enqueue_call(self, func, args=None, kwargs=None, timeout=None,
                     result_ttl=None, ttl=None, failure_ttl=None,
                     description=None, depends_on=None, job_id=None,
                     at_front=False, meta=None):
       """Creates a job to represent the delayed function call and enqueues
        it.
        It is much like `.enqueue()`, except that it takes the function's args
        and kwargs as explicit arguments.  Any kwargs passed to this function
        contain options for RQ itself.
        """
        timeout = parse_timeout(timeout) or self._default_timeout
```

Perhaps fix by making also a `job_timeout` parameter and changing the last line shown to

```
        timeout = parse_timeout(job_timeout) or parse_timeout(timeout) or self._default_timeout
```

See also issue #698.

**Comment by shaunharker** [comment]
It might be worth considering allowing the alternative `timeout` (rather than `job_timeout`) for the `enqueue` function as well to minimize the amount of broken user code, but don't document it except for saying it is deprecated and will be removed down the line.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/commit/0d593f40e1efcf2bead67b8bade91d0f3477bf61 . 

I removed references to `queue.enqueue_call()`, but left the code as it is. This method should not be needed anymore since you can already pass `args` or `kwargs` to `queue.enqueue()`
