### ISSUE TITLE
Run job on delay or at specific time

### ISSUE THREAD

**Issue by Naatan** [rq/rq#1073]
Is it possible to use rq to run jobs at a specific time or after a specific delay? I can't find anything on this. Anything I find on delays are implicit delays.

**Comment by samuelcolvin** [comment]
(please excuse the plug)

Not possible with rq, but you can do both [delaying jobs](https://arq-docs.helpmanual.io/#deferring-jobs) and [running jobs at particular times](https://arq-docs.helpmanual.io/#cron-jobs) with arq.

**Comment by Naatan** [comment]
Cool, thanks for sharing!
