### ISSUE TITLE
get_job_ids() returns job ids but RQ dashboard shows none?

### ISSUE THREAD

**Issue by GaryMcPolin** [rq/rq#1074]
```
registry = StartedJobRegistry('default', connection=get_redis_connection())
running_job_ids = registry.get_job_ids()
>>> [u'f8658681-6eee-46c3-a197-fe49202369f3', u'c3f935f0-ddc1-400c-86ac-b8edb14f2a05', u'874bf02b-c7c4-4f7b-b4ca-65031919c68d', u'47341bb9-996a-4dd5-9277-12168c3df00f', u'1a6686a4-2f0c-467a-81eb-2c2113784520', u'e58447bd-c2cb-4c91-bb21-9fc281c75c81', u'c9857e19-f096-498c-9ee5-1be1e5372ab4']
```
rq info output:
```
default      | 0
failed       | 0
2 queues, 0 jobs total

0 workers, 2 queues

Updated: 2019-04-29 23:00:49.020517
```
I am trying to fetch the number of currently running jobs. However, there are a number of job ids that seem to be stuck in the `StartedJobRegistry`. When I try to fetch jobs by id I get an error `No such job: rq:job:f8658681-6eee-46c3-a197-fe49202369f3`
I have tried queue.empty() with no luck.

**Comment by selwin** [comment]
Try running a worker and check `rq info` again to see what happens. It could be that your workers were killed in cold shutdown and they never got the chance to cleanup the registries.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1107
