### ISSUE TITLE
Incorrect documentation on failed jobs

### ISSUE THREAD

**Issue by WeatherGod** [rq/rq#1077]
At https://python-rq.org/docs/results/#dealing-with-exceptions, the documentation states: `A reference to the job is put on the failed queue.`. This seems to no longer be the case as of v1.0? The documentation at https://python-rq.org/docs/exceptions/ does seem correct, though.

In addition, it would be nice to at least include documentation on how users could retain the old behavior of moving failed jobs to a failed queue. I was depending on that feature as part of my system design (I had a small pool of workers delegated to the "failed" queue so that failed jobs wouldn't obstruct processing of good jobs).

**Comment by selwin** [comment]
I have updated the docs to correct the reference to failed queue.

Unfortunately, there's no built-in way to retain the old behavior as the exception handling mechanism has been completely overhauled.

To replicate the old behavior, you can disable the default exception handler and create an exception handler that pushes jobs to a new "failed" queue.
