### ISSUE TITLE
inconsistency between enqueue() and enqueue_call()

### ISSUE THREAD

**Issue by WeatherGod** [rq/rq#1078]
`enqueue()` gained the `job_timeout` keyword argument in v0.13, and deprecated `timeout` in v1.0. However, the same was not done for `enqueue_call()`. This is a bit confusing, and I don't know if this was intentional or not.

In addition, as I noted in https://github.com/rq/rq/pull/1055/files/6e6e42521ad5c5f53d726cc5423b8102e5424ae5#diff-8cd1d5f89419373ed692b618467c6fda, there is incorrect documentation, showing `job_timeout` being used in an `enqueue_call()`.

**Comment by selwin** [comment]
I updated the docs in [this commit](https://github.com/rq/rq/commit/0d593f40e1efcf2bead67b8bade91d0f3477bf61) to completely omit `enqueue_call()` from the docs.
