### ISSUE TITLE
rq version 1.0 pip wheel file isn't correct

### ISSUE THREAD

**Issue by jameshulse** [rq/rq#1079]
When running `pip install -v rq==1.0` I can see that the wheel file includes a `handlers.py` file which was deleted in the latest 1.0 changes. From a quick look the other files seem to include their 1.0 changes. The wheel should probably be recreated to ensure it contains all the correct files and no old files.

Running `pip install --no-binary rq rq==1.0` installs from the zip which seems to be the more correct version.

For reference the wheel file that pip finds is `https://files.pythonhosted.org/packages/ee/f6/dbcf2a28e5621e1fcf6be6937da9777ad9ab03c7d3cb7d6ee835adc43329/rq-1.0-py2.py3-none-any.whl#sha256=0d28922da7287afc24f13e9e24ddafb4e737f27d55d91ad4f4e6de1134da85e5`

**Comment by selwin** [comment]
Hmm, unfortunately PyPI [doesn't](https://pypi.org/help/#file-name-reuse) allow filename reuse. I'll have to create a new point release this weekend.

**Comment by jameshulse** [comment]
Okay, no problem.

**Comment by selwin** [comment]
Sorry for the delay, but RQ v1.1.0 is now on PyPI.

**Comment by jameshulse** [comment]
Cheers mate.
