### ISSUE TITLE
Accessing a queue from within a job function

### ISSUE THREAD

**Issue by danielamaya** [rq/rq#1098]
I have a function that needs to enqueue a job for another worked based on some logic. For example, something like this:

```
def count_words_at_url(url):
    resp = requests.get(url)
    if len(resp.text.split()) > 100:
        q.enqueue(do_something_else, resp.text)
```

My question: From within the functions I define for workers, how do I access a queue?

**Comment by selwin** [comment]
You can use `get_current_job()` function documented here: https://python-rq.org/docs/jobs/#accessing-the-current-job .

After you get the `job`, `job.origin` will give you the name of the originating queue.
