### ISSUE TITLE
Jobs not getting enqueued

### ISSUE THREAD

**Issue by WonksknowAravind** [rq/rq#1100]
Jobs are enqueued on localhost, but when deployed to staging on heroku, the job queue is always empty
 
 rq = Queue('default',connection=redis_conn)
 jobs = rq.enqueue(upload_video, args=(base64.b64encode(a.read()), name,))

**Comment by selwin** [comment]
Check your Heroku configuration. I'm closing this issue since this is not a bug in RQ itself.
