### ISSUE TITLE
ImportError: cannot import name 'FailedQueue'

### ISSUE THREAD

**Issue by lmantesbtm** [rq/rq#1101]
Hi all,

I ran to an issue of this one. I don't know if this is here or django-rq.

Suddenly this module is gone after running pipenv install. I haven't change anything from the requirements or pipfile.

![image](https://user-images.githubusercontent.com/31840861/59076848-a6a4b080-890a-11e9-8c13-c11479335bcb.png)

Info that might help:
python: 3.5.5
django: 1.11
django-rq: 1.2.0
rq: 1.0
redis-cli/server: 4.0.1 (same version)

Thanks.

**Comment by lmantesbtm** [comment]
I have fixed this by copying the FailedQueue class and paste it in the rq.queue.

The question now is why it was missing.

**Comment by selwin** [comment]
`FailedQueue` has been deprecated in RQ v1.0. Please check the release notes. https://github.com/rq/rq/blob/master/CHANGES.md#10-2019-04-06
