### ISSUE TITLE
Workers unable to find media files in django

### ISSUE THREAD

**Issue by jvlomax** [rq/rq#1102]
I've come across an issue where my workers are not able to find media files that are referenced a django template. We are using django-rq too, and I've raised an issue there too.  However, I don't see anything in that package that would cause it since it's just a convenience wrapper for python-rq.

Are there any settings, env variables or additional config that is now required to work with django templates or media files?

**Comment by selwin** [comment]
Closing this issue since it's not an RQ related issue.
