### ISSUE TITLE
Jobs inappropriately added to FailedJobRegistry

### ISSUE THREAD

**Issue by rtoole13** [rq/rq#1103]
I'm running into an issue where jobs that are actively actively underway on a worker are popping up in my default queue's FailedJobRegistry. Despite those job ids being in the failed registry, the actual jobs will finish successfully.
```python
from rq import Queue  
default = Queue(connection=r)
ids = default.failed_job_registry.get_job_ids() 
print(ids)
```
Apparently, I've got 6 job ids in the registry: [u'e91f884e-1319-4de0-af57-1512f882d2c6', u'e12e5a0e-6a6f-4217-bc59-c5ec9823440b', u'7307712f-0090-4abe-becd-0ee5d421c502', u'ac89964a-ae3e-4a63-9126-f69440209d92', u'c53b0c33-2a3f-466b-a4c2-a2f2aabc3ff4', u'fe9f163b-5ec8-48e5-89ae-117d77e80c4a']

The jobs corresponding to those ids are not in the Redis db though (as presumably they've all completed successfully and been removed from the db).
```python
r.keys('*e91f88*') #yields no results, for instance
from rq.job import Job
Job.fetch(ids[0], connection=r) #unsurprisingly throws a NoSuchJobError for all of the 6 ids
```
Unfortunately, I'm struggling at the moment to replicate the issue. It seems be happening more or less at random, and my failed job registry grows. I'm wondering if anyone could help steer me towards finding the underlying issue here.

**Comment by zubairalam** [comment]
What `exc_info` info says for job ids in `failed_job_registry` of your default queue?

**Comment by selwin** [comment]
Do your jobs typically run close to job timeout? (180 by default).

**Comment by theomessin** [comment]
I have the same issue by the way. Jobs take a while but timeout has been set to infinity (`-1`).

**Comment by selwin** [comment]
@theomessin how are you setting your timeout? Through `queue.enqueue(timeout=-1)` or by some other means?

**Comment by theomessin** [comment]
Using `queue.enqueue(timeout=-1`

**Comment by selwin** [comment]
And do the both of you use RQ's default `Worker` (one that forks and executes the job in a separate process) and `Queue` class?

**Comment by theomessin** [comment]
Yes. Here's my code:
```
conn = redis.Redis("redis", 6379)
w = rq.Worker("default", connection=conn)
w.work(logging_level="DEBUG")
```

**Comment by selwin** [comment]
@theomessin I haven't been able to determine what causes your jobs to be added to `FailedJobRegistry`, short of your enqueued function causing an exception.

I [committed a patch](https://github.com/rq/rq/pull/1110) to prevent people from adding jobs with `0` timeout, which people sometimes mistake for infinite timeout.

I'll also add more debug logging calls so we can troubleshoot your issues.

Alternatively, if you have failing test cases, that would be easiest for me to debug and fix.

**Comment by theomessin** [comment]
@selwin thanks :smiley: I'll try to create a repo that reproduces this issue and I'll keep this issue updated.

**Comment by rtoole13** [comment]
@selwin I'm doing pretty much the same thing as @theomessin is. But creating a number of workers/queues in screen sessions by means of a config file.

In a screen session:
```sh
rq worker -c settings
```

Where the config file, settings.py, defines a number of parameters:
```python
from socket import gethostname
import redis
config = {'host': '1.1.1.1', 'port': 0000, 'db':0} #dummy values

r = redis.StrictRedis(**config)
NAME = gethostname()
QUEUES = ['default', 'high', 'low']
#along with a few other params not listed here
```

Queuing occurs as such:
```python
from rq import Queue, Worker
from settings import r
queue = Queue('default', connection=r) 
#'default' is hardcoded here, but varies between the queue names specified in settings.py

job = queue.enqueue(my_func, filepath, job_timeout=-1, meta=meta)
#my_func is defined in the same script, filepath is a custom argument
#meta contains a number of entries with custom data
```

The jobs seem to show up in the failed job registries at about right when the worker pulls the job to begin work. As mentioned, work continues successfully though. Also, no exception info shows up in the job's exc_info.

**Comment by selwin** [comment]
@rtoole13 are you positive that jobs begin to appear in `FailedJobRegistry` shortly after work begins? If so, I'll focus on the codes surrounding that part of the worker.

**Comment by rtoole13** [comment]
> @rtoole13 are you positive that jobs begin to appear in `FailedJobRegistry` shortly after work begins? If so, I'll focus on the codes surrounding that part of the worker.

Yes, they show up at the beginning. My jobs last fairly long, some nearly an hour, and the work throughout that duration is consistent. I'm going to work on adding a logging exception handler to the workers to see if I can get more useful information.

**Comment by selwin** [comment]
@rtoole13 I added a test for running job with infinite timeouts, but the tests pass without revealing any issues. Feel free to look at the diff here: https://github.com/rq/rq/compare/test-infinite-timeout

**Comment by selwin** [comment]
@rtoole13 I added logging statements to `handle_job_failure` in this PR: https://github.com/rq/rq/pull/1112

If you can run your workers with `DEBUG` logging level, you maybe able to find clues on when your jobs are added to `FailedJobRegistry`.

**Comment by rtoole13** [comment]
Thanks @selwin! With my logging level set (as evidenced by the 'Sent heartbeat to prevent worker timeout..' statements printing every 420 seconds), I observed my `FailedJobRegistry` count increase but did not see a relevant debug statement.

Furthermore, I've added an exception handler (by means of the CLI on worker start) to the workers to log exceptions to a file, but haven't caught anything there either.

I did learn though that the jobs appear at times other than just shortly after work begins, so my apologies on my earlier statement. I'm suspecting it's occurring at the standard 420s or 35s worker heartbeat? I'll keep observing and post here if I learn anything. Thanks for the help so far.

**Comment by rtoole13** [comment]
FYI this hasn't been a problem for me beyond 1.1.0 (possibly sooner). Thank you!

**Comment by nkumar15** [comment]
I am not sure what wrong I am doing here but below code is not honoring job_timeout
```
queue = rq.Queue("queue1", connection=Redis.from_url("redis://"))
job = queue.enqueue(
          process_jobs,
          args=(my_job_id, my_job_type, my_job_params),
          job_id=my_job_id,
		  job_timeout=600
 )
```

And I am starting worker from rq cli command as 

`rq worker queue1`

I can see jobs are submitted successfully and starts execution also, but after 180 secs, automatically jobs are marked as failed with and below message is shown.

**Moving job to FailedJobRegistry (work-horse terminated unexpectedly: waitpid None)**

I have looked at my code and it is taking care of all expections. I am not sure why worker process is getting killed.
Any suggestions please?

**Comment by rish-hyun** [comment]
I have set timeout to -1 and still job goes to FailedJobRegistry while its running 
```
queue = Queue(connection=self.conn, default_timeout=-1)
queue.enqueue(f, result_ttl=60, job_timeout=-1, *args, **kwargs)
```
```
{"job_id":"xxxxxxxxxxxxxxxxxxxxxxxxx","exc_info":"Moved to FailedJobRegistry at 2021-12-12 12:36:18.059156"}
```
At the same time, worker is still running
```
. . .

--- sample statements ---
job running passed level 1
job running passed level 2
job running passed level 3
and so on . . .
--- sample statements ---

. . .
```
