### ISSUE TITLE
@job decorator failing when tapped on instance method

### ISSUE THREAD

**Issue by vswamyavi** [rq/rq#1104]
I have tried to tap the @job decorator on instance method and it fails while worker trying to execute the job with below error 

{noformat}
05:44:23 TriggerWorker: vs.add(1, 2) (e22b13f8-8281-4dc0-a9f0-9a91c349b1ae)
05:44:23 AttributeError: 'module' object has no attribute 'add'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 199, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 156, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'add'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 199, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 156, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'add'
{noformat}

**version info:**
Requirement already satisfied: rq in /usr/local/lib/python2.7/dist-packages (1.0)
Requirement already satisfied: redis>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from rq) (3.2.1)
Requirement already satisfied: click>=5.0 in /usr/local/lib/python2.7/dist-packages (from rq) (7.0)

**OS info:**

VERSION="14.04.6 LTS, Trusty Tahr"

**Comment by vswamyavi** [comment]
This is happening even if we create a custom decorator that does the job enqueue which is tapped on instance method.

This below property gets self.instance set to None

```
    @property
    def func(self):
        func_name = self.func_name
        if func_name is None:
            return None

        if self.instance:
            return getattr(self.instance, func_name)

        return import_attribute(self.func_name)
```

Thats because, unpickling either got wrongly ordered data or the second value which is supposed to be self.instance is set None

```
debug >self.connection.hgetall(key)
{'status': 'queued', 'origin': 'TriggerQueue-0', 'description': 'vs.add(<vs.VirtualService object at 0x7f067a437650>)', 'created_at': '2019-06-12T17:05:17.746350Z', 'enqueued_at'
: '2019-06-12T17:05:17.746952Z', 'timeout': '180', 'data': 'x\x9ck`\xd2\x88`c``(+\xd6KLI)d\xf4K.+\xe6\n\xcb,*)M\xcc\tN-*\xcbLN\xe5*d\xd2l,d\xae-dIj-d\xad-d+)d\xd7\x03\x00\xd3\xe3
\x11\x0f'}
debug >key
'rq:job:ba14d734-ad23-411e-a89d-f663392849c8'
debug >raw_data
'x\x9ck`\xd2\x88`c``(+\xd6KLI)d\xf4K.+\xe6\n\xcb,*)M\xcc\tN-*\xcbLN\xe5*d\xd2l,d\xae-dIj-d\xad-d+)d\xd7\x03\x00\xd3\xe3\x11\x0f'
debug >self.data
*** ValueError: Cannot build the job data
debug >zlib.decompress(raw_data)
'\x80\x02(X\x06\x00\x00\x00vs.addq\x01Ncvs\nVirtualService\nq\x02)\x81q\x03}q\x04b\x85q\x05}q\x06tq\x07.'
debug >loads
<built-in function loads>
debug >loads(zlib.decompress(raw_data))
(u'vs.add', None, (<vs.VirtualService object at 0x7f9805abc690>,), {})
```

Could someone help with this?

**Comment by selwin** [comment]
Sorry, but instance methods are not supported. You can only enqueue functions to RQ.

**Comment by vswamyavi** [comment]
I suspect that the decorator is function decorator and thus doesn't get the context of the function. it basically see that as just function but not as instance method. In order to see it as instance method then it has to be class decorator instead of function.

> Sorry, but instance methods are not supported. You can only enqueue functions to RQ.

Hi Selwin,

Thanks for your update. Could you share any details about the same like is there some issue in supporting this?

**Comment by vswamyavi** [comment]
Have created a custom class decorator and it is failing with errors during pickling? Could you shed more light on this?
