### ISSUE TITLE
Replace procname with setproctitle

### ISSUE THREAD

**Issue by j178** [rq/rq#1106]
The current rq implementation uses [procname](https://github.com/lericson/procname) for better `ps -ef` output, but the procname doesn't support Python3 actually, according to [this](https://github.com/lericson/procname/issues/3). 
When importing `procname` under python3, it throws `ImportError`: 
```
>>> import procname
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/johnj/.pyenv/versions/general/lib/python3.7/site-packages/procname.cpython-37m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule3
```

We should use [setproctitle](https://github.com/dvarrazzo/py-setproctitle) instead.

**Comment by selwin** [comment]
I'm not familiar with this piece of code, but if it never worked on Python 3 all this time, it probably means it's not widely used. Should we just remove this code altogether?

The alternative would be to use `setproctitle` like you mentioned.

**Comment by j178** [comment]
Personally I thought it's pretty useful to have a friendly customized program title like this:
![image](https://user-images.githubusercontent.com/10510431/59561053-a8c6e780-904d-11e9-86e5-5a681016833d.png)

Could I create a pull request to fix this?

**Comment by selwin** [comment]
Could you also document the existence of this feature in https://github.com/rq/rq/blob/master/docs/docs/workers.md ?

**Comment by j178** [comment]
Updated.
