### ISSUE TITLE
RQ workers output redirection works only for STDERR

### ISSUE THREAD

**Issue by exophoric** [rq/rq#1113]
In short, by default, `bash-4.2$ rq worker > stdout.log` will always produce an empty file, silencing print() and sys.stdout.write() calls you make in your worker function. 

However, `bash-4.2$ rq worker 2> stderr.log` will retain messages. You still lose track of bytes sent to stdout.  

This means the [recipe that is provided to wrap rq workers in systemd unit](https://python-rq.org/patterns/systemd/) will only retain stuff sent to stderr when you read `bash-4.2$ journalctl -u rqworker.service`.

**Comment by exophoric** [comment]
If you manually flush stdout (`sys.stdout.flush()`) after your prints / writes workers will write to stdout.

**Comment by exophoric** [comment]
This is pointing to a buffering issue in the child process. Since rq logging is sent to stderr, this buffer gets flushed, however, the stdout is never flushed. A possible workaround would be to set the [PYTHONUNBUFFERED environment variable to some value](https://docs.python.org/3.7/using/cmdline.html#envvar-PYTHONUNBUFFERED) in the environment of the systemd unit. 

I don't know the performance impacts though.

**Comment by selwin** [comment]
I think we should avoid change `print()` usage in RQ's codebase to use logging instead. What do you think?

**Comment by exophoric** [comment]
I'm not sure if I get what you mean. Does RQ codebase changes something about how stdout or print are handled? In case  there's something not clear in the way I explained the problem here are some clarifications.

The function (of my codebase, not RQ's) that I enqueue for asynchronous execution is writing some log messages to stdout. These log messages are not visible in systemd's journal (using the suggested pattern), which poses issues to debugging and maintenance. I'm indeed using a logging library. Although this logging library is custom to my organization and  writes some message types to stdout, some others to stderr. 

I've looked in the codebase to try to narrow down the problem without success up to now. I initially thought that the forking of a work horse was causing this, but a simple test with fork did not replicate the issue. I'll submit a pull request if I find a viable solution.

**Comment by selwin** [comment]
>> I'm not sure if I get what you mean. Does RQ codebase changes something about how stdout or print are handled? In case there's something not clear in the way I explained the problem here are some clarifications.

Please disregard my answer for this, I thought your original question referred to `print()` functions inside RQ's source code itself, while you're purely talking about logging things in your own jobs.

I'm closing this issue since this doesn't look like an RQ related issue, but if you find something that we can do in RQ to make your job easier, feel free to reopen this issue again.
