### ISSUE TITLE
rq worker --max-jobs Error: no such option

### ISSUE THREAD

**Issue by klewis486** [rq/rq#1122]
It looks like there might be an issue with the "--max-jobs" flag running rq worker in CLI mode. I'm using rq 1.0 on macOS 10.14.5 and I'm unable to run the following command in terminal:

`rq worker --max-jobs 10`
The response I get is "Error: no such option: --max-jobs"

**Comment by selwin** [comment]
`--max-jobs` is new to version 1.1. Please upgrade your RQ :)
