### ISSUE TITLE
`rq worker` does not work in docker container?

### ISSUE THREAD

**Issue by pkuwwt** [rq/rq#1123]
I tried to deploy `redis-server` and `rq` in the same docker container. In the container, `redis-server` works. The `rq` seems not having any connection problem. However, I cannot find any worker by `rq info` after starting `rq worker test`。

The `Dockerfile` is simple:

```dockerfile
FROM ubuntu:18.04

RUN apt-get update && \
	apt-get upgrade -y && \
	apt install -y python3-pip \
	redis-server \
	supervisor

RUN pip3 install redis rq

COPY supervisor_redis.conf /etc/supervisor/conf.d/

CMD ["supervisord"]
```
The content of `supervisor_redis.conf` file is
```
[supervisord]
nodaemon=true

[program:redis]
command = /usr/bin/redis-server
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```

The image is built as `rq-test` by
```
sudo docker build -t rq-test .
```
The container is run by
```
sudo docker run --name test-rq -d rq-test
```
The problem can be reproduced as
```
sudo docker exec -it test-rq bash -c 'LC_ALL=C.UTF-8 LANG=C.UTF-8 rq worker test'
```
and
```
sudo docker exec -it test-rq bash -c 'LC_ALL=C.UTF-8 LANG=C.UTF-8 rq info'
```

Everything seems OK except there is nothing in `rq info`:
```
0 queues, 0 jobs total

0 workers, 0 queues

Updated: 2019-08-04 07:53:49.835481
```

FYI, the versions are
  * redis: `Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3`
  * rq: `version 1.1.0`

**Comment by selwin** [comment]
I don't know much about docker or your setup so I'm not sure what the problem is. Please reopen this issue if you find evidence that there's a bug in RQ that we need to fix.

**Comment by HideyoshiNakazone** [comment]
I encountered the same problem, the thing is that when using Dockerfile CMD in the list form RQ isn't able to parse the env variable REDIS_URL or the REDIS_PASSWORD. So to solve this problem create a entrypoint script that will be ran by the docker container, such as:

```
#!/bin/bash


if [[ $1 == "--queue" || $1 == "-q" ]]; then
   rq worker --with-scheduler
else
    python -m storage_service
fi

exec "$@"
```

Just a comment to help anyone else that is facing similar problems.
