### ISSUE TITLE
'enqueue' doc, infinite ttl not allowed

### ISSUE THREAD

**Issue by Battleman** [rq/rq#1127]
I think there is a small inconsistency between the doc and actual behaviour, in `enqueue` (and `enqueue_call`). As I understand from the [doc](http://python-rq.org/docs/), to have a job with infinite `ttl` we should pass a value of -1, as the following:
> `ttl` specifies the maximum queued time of the job before it’s discarded. If you specify a value of -1 you indicate an infinite job ttl and it will run indefinitely

But after testing this, and inspecting the code:
https://github.com/rq/rq/blob/b14c4e288d5f1b74f16c42f381a6c8993ee9c122/rq/queue.py#L245-L246
This seems to differ from the expected behaviour.

I'm using the latest version (1.1.0). I didn't find any issue already opened regarding this. Please correct me if there is, or if this is actually expected.
Cheers.

**Comment by granigd** [comment]
Can confirm, I have the same issue with the 1.1.0 verson from pypi. Setting the ttl to -1 would be convinient for my usecase.

**Comment by selwin** [comment]
You should just pass in `None` for infinite TTL. I fixed the docs in this PR: https://github.com/rq/rq/commit/ed15b9e031eab74f2216f333883321be78bd4056
