### ISSUE TITLE
Moving job to FailedJobRegistry could be optional in case of waitpid == 9

### ISSUE THREAD

**Issue by nurettin** [rq/rq#1129]
I run 2 machines with 150 processes each, doing various tasks. Sometimes OOM killer or some other external process kills some of the jobs, but they should be requeued and completed. 

Instead, I have to run rq requeue in a loop as fast as possible in order to return failed tasks back on the queue and they may or may not be in fail state because of an OS cleanup. 

In short, it would be very useful to be able to decide what to do in case of certain PIDs. Where can I start reading about this? Is it part of the scheduler or the worker?

I see [this code]( https://github.com/rq/rq/blob/d0884be9296cf2cba2428d5d90cdeda65a550296/rq/worker.py#L657) Is this where I need to change for PR?

**Comment by selwin** [comment]
You could disable RQ's default worker handling mechanism with `disable_default_exception_handler=True` and passing in your exception handling mechanism via `exception_handlers=[my_exception_handler]`.

More info here: https://python-rq.org/docs/exceptions/
