### ISSUE TITLE
Does RQ offer a pub-sub model?

### ISSUE THREAD

**Issue by salimfadhley** [rq/rq#1131]
My application produces a number of events.

When certain events happen, some follow-on processes should happen. It's not a big deal if they fail to happen, mostly they are non-critical notifications.

Is there a way to just push an event onto a queue, and have workers subscribe certain channels. If the worker dies, or a message goes without being picked-up, it can safely expire.

**Comment by selwin** [comment]
Yes, you could do `queue.enqueue(job, ttl=10)`. In this case, if the queued job doesn't get picked up by a worker in 10 seconds, the job will expire.

More info here: https://python-rq.org/docs/
