### ISSUE TITLE
redis.exceptions.RedisError: ZADD requires an equal number of values and scores

### ISSUE THREAD

**Issue by irthomasthomas** [rq/rq#1138]
Hi

I'm running in to this error, which occurs even when testing the simplest demonstration from the readme. Using Ubuntu 18.04, python 3.6, redis 5.0.5 and rq 1.1.0.

Thanks

**Comment by tarponjargon** [comment]
Yeah I'm having the same issue.  rq seems to work fine if I start it like this:

`rq worker tasks`

But I get that zadd error when trying to start with 

`python worker.py`

With worker.py being:

```
import os
import redis
from rq import Worker, Queue, Connection

listen = ['tasks']

redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')

conn = redis.from_url(redis_url)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()
```

I'm using python 3.7.0 and redis-server 5.0.7

**Comment by tarponjargon** [comment]
Actually, I think this is a python path problem in my dev environment.  When I use:

`python3 worker.py`

it works fine.  Sorry!

**Comment by yezigege** [comment]
this is "redis.zadd" code.

    def zadd(self, name, *args, **kwargs):
        """
        Set any number of score, element-name pairs to the key ``name``. Pairs
        can be specified in two ways:

        As *args, in the form of: score1, name1, score2, name2, ...
        or as **kwargs, in the form of: name1=score1, name2=score2, ...

        The following example would add four values to the 'my-key' key:
        redis.zadd('my-key', 1.1, 'name1', 2.2, 'name2', name3=3.3, name4=4.4)
        """
        pieces = []
        if args:
            if len(args) % 2 != 0:
                raise RedisError("ZADD requires an equal number of "
                                 "values and scores")
            pieces.extend(args)
        for pair in iteritems(kwargs):
            pieces.append(pair[1])
            pieces.append(pair[0])
        return self.execute_command('ZADD', name, *pieces)

read example, you can do this.

**Comment by Ckend** [comment]
pip install redis --upgrade
