### ISSUE TITLE
Failed jobs are never removed from rq:job.

### ISSUE THREAD

**Issue by gbrova** [rq/rq#1143]
When I queue and run a failing job:

```
def failing_fn(args):
    raise Exception("failed")

myq = rq.queue.Queue("myq", connection=Redis())
myq.enqueue(failing_fn, (), result_ttl=0, failure_ttl=0)

myw = rq.worker.Worker(["myq"], connection=Redis())
myw.work()
```

the reference to this job in Redis (`rq:job:xxx`) is never deleted, even after the registry gets cleaned up (when `rq:failed:myq` is empty). 

This is manifesting as a memory leak because I'm abusing rq to pass data around by calling functions with large *args. These functions occasionally fail, so the args serialized in `rq.job.xxx` never get freed. 

This is possibly related to #1008. 

Is there a reason why failed jobs shouldn't expire? This seems to be a [deliberate choice](https://github.com/rq/rq/blob/master/rq/registry.py#L179), but I wonder if it's worth revisiting now that `failure_ttl` was added in 1.0?

**Comment by selwin** [comment]
Failed jobs should expire automatically after `failure_ttl` seconds. This seems to be a bug. PR welcome :)

**Comment by gbrova** [comment]
You beat me to it :-)  Thanks for fixing, and I look forward to using the new release.
