### ISSUE TITLE
rq queue not resolving

### ISSUE THREAD

**Issue by SumNeuron** [rq/rq#1148]
This issue is inspired by this S.O. [post](https://stackoverflow.com/questions/58473432/tensorflow-1-14-dockerized-task-based-flask-api-doesnt-run-and-or-stalls):

While the post has a more complex setup, a MWE of the flask, redis, rq docker interaction can be found [here](https://gitlab.com/SumNeuron/docker-nuxt-flask-redis-rq/). 

While it seems that the configuration is correct it is unclear. rq's experience in addressing this would be appreciated.

**Comment by lowercase00** [comment]
@SumNeuron more details on this? A *minimal* example would be helpful, a whole repo with a lot of moving pieces is harder to debug. As a suggestion take flask out of the equation, and have a 2/3 file micro example just with the task.

**Comment by lowercase00** [comment]
Closing as stale. Feel free to reopen if needed.
