### ISSUE TITLE
Easy Documentation fix!

### ISSUE THREAD

**Issue by goldstar611** [rq/rq#1152]
On the [various pages](http://python-rq.org/docs/workers/) where you use specify ```--url``` from the command line, it would be great if you add in a mention of ```unix:///var/run/redis/redis.sock``` so that users can easily figure out how to connect an rq worker to a unix socket. 

For whatever reason, ```redis:///var/run/redis/redis.sock``` works fine in a flask app but not on the rq worker cli.

**Comment by selwin** [comment]
Please open a PR for this.

**Comment by goldstar611** [comment]
PR opened :)
