### ISSUE TITLE
rq worker parameter error: --logging_level override -v

### ISSUE THREAD

**Issue by zyt312074545** [rq/rq#1166]
When I use `rq work -v` want to get more output, I find that I can't  get more output
![rq_1](https://user-images.githubusercontent.com/8190833/70210276-42559300-176d-11ea-9105-248faf817e45.png)

I read source code find this
https://github.com/rq/rq/blob/cf501518534429640a9a6d14e022f9329225e701/rq/cli/cli.py#L220
https://github.com/rq/rq/blob/cf501518534429640a9a6d14e022f9329225e701/rq/cli/cli.py#L252
https://github.com/rq/rq/blob/cf501518534429640a9a6d14e022f9329225e701/rq/worker.py#L453

`logging_level` use in `work` function override `-v` setting

So I suggest remove `--logging_level` parameter, if you agree my idea, I will fix this

**Comment by selwin** [comment]
The correct behavior should be, if `--verbose` should override `logging_level` is it's passed in. Please open a PR for this.
