### ISSUE TITLE
Using Python 3.8 with older workers causes pickle protocol errors

### ISSUE THREAD

**Issue by schinkelg** [rq/rq#1168]
As a workaround I changed the value HIGHEST_PROTOCOL to 4 in job.py.
Line 27 of jobs.py: 
dumps = partial(pickle.dumps, protocol=4)

rq.exceptions.UnpickleError: ('Could not unpickle', ValueError('unsupported pickle protocol: 5',))

Can the protocol value be set somewhere, as a client of rq?

**Comment by selwin** [comment]
I think having a configurable serializer is a good way to do this. Please take a look at https://github.com/rq/rq/issues/973 . There's also a half done PR on this at https://github.com/rq/rq/pull/1141
