### ISSUE TITLE
RQ is breaking application logging

### ISSUE THREAD

**Issue by harlowja** [rq/rq#1183]
I have an application which does the following (or something like this):

```
import logging

import rq

log = logging.getLogger("bbbb")

logging.basicConfig(level=logging.DEBUG, format='%(asctime)-15s %(levelname)s:%(name)s:%(message)s')

... do stuff ...

log.debug("hi")
```

The above now outputs nothing.

All of a sudden with 1.2.0 all my messages are getting dropped.

**Comment by selwin** [comment]
Should be fixed in RQ 1.2.1
