### ISSUE TITLE
Jobs with -1 timeout failing with "work-horse terminated unexpectedly; waitpid returned None"

### ISSUE THREAD

**Issue by theY4Kman** [rq/rq#1186]
Since 1.2.1, jobs with a timeout value of `-1` have been failing, with the log message
```
WARNING 2020-02-05 20:51:01,504 (rq.worker.monitor_work_horse): Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned None)
```

I think what might be happening is the new hard kill on heartbeat isn't respecting `-1` to mean "no timeout" or "infinite timeout": https://github.com/rq/rq/blob/0080b223fece617ceb33cb22701950b21dba28a1/rq/worker.py#L690-L693

I think on the first heartbeat, it performs the arithmetic `job.timeout + 1`, which'll be `0`, and since the elapsed time will always be higher than that, it immediately kills the work horse.

**Comment by lcoimbra** [comment]
Had the same issue, going back to v1.2.0 solved it for now.

**Comment by filipallberg** [comment]
I was worried when I came across this setting, can confirm that this affects me. Setting the timeout to a large number made the problem go away as well as going back to previous version.

**Comment by b3nab** [comment]
Same here on v1.2.2 and also confirm that going back to v1.2.0 as suggested by @lcoimbra solved just for now because we can't upgrade to latest version without issues.
