### ISSUE TITLE
When a job throws an exception, the exception should be stored as a result.

### ISSUE THREAD

**Issue by luisbc92** [rq/rq#1190]
The documentation explain that when a job throws an exception, it should be stored as its result and pickled to the caller.

Currently the job.result property returns None as the exception is never stored.

**Comment by smaccona** [comment]
@luisbc92 If a job fails, the exception is available in the job’s `exc_info`. Does this not satisfy your needs?

**Comment by luisbc92** [comment]
@smaccona yes, that also works. However, the documentation might need to change to reflect that as it currently implies the exception is stored as the result.

**Comment by selwin** [comment]
I think the current behavior (storing exception info in “exc_info” is the right eay to go). Will change the docs.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/commit/bf93e11f2f98f526039f49341114b8c42fc05b17
