### ISSUE TITLE
Pass job_id in Worker.handle_exception extra argument

### ISSUE THREAD

**Issue by smaccona** [rq/rq#1192]
In `Worker.handle_exception`, the call to `self.log.error` passes various details of the job (namely `func_name`, `args`, `kwargs` and `origin`) in the `extra` `dict`. This is useful because any log handlers that receive the exception's `LogRecord` will not be able to get access to the job via `get_current_job()`, because at that point the job context will be unavailable.

In my use case, I have Django logging set up to email the site admins on exceptions (including job exceptions). The built-in Django `AdminEmailHandler` mails exception details including a full stack trace to the site admins, but I have extended `AdminEmailHandler` to provide extra functionality (for example, certain types of exception that occur in data import jobs can be handled by data analysts making changes to ETL configurations and then re-running the job, and those exceptions should go to those data analysts instead of to the overall site admins). Sometimes the stack trace in question can contain sensitive information, so it would be useful for the email being sent to include a link to the failed job on the Django admin site instead of including the full stack trace (because access to the failed job queue on Django admin can be better controlled). This also provides quick immediate access from the email to the failed job, both for troubleshooting and requeueing (we can have 100s of failed jobs at any given time, and locating them via the full list of failed jobs on the admin can sometimes be time-consuming).

To do this, however, we need the job ID, which as I mentioned is not readily available while the log handler is executing. Is there another way to get the job ID besides `get_current_job()` that I am not aware of, or is a PR which adds `job_id` as another entry in the `extra` argument to the `self.log.error` call in `Worker.handle_exception` the best way forward? I am happy to submit the PR if so.

**Comment by smaccona** [comment]
@selwin is a PR the way to go here, or am I missing something? It's feels to me like I am missing something and that there is already a way to get the job ID in a worker's logger that I just don't know about.

**Comment by selwin** [comment]
Sorry I missed this issue. Yes, please open a PR, passing extra context to error handlers is good.

**Comment by smaccona** [comment]
@selwin PR ready when you have a chance to review. Thanks as always.
