### ISSUE TITLE
redis.exceptions.ResponseError: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by nadermx** [rq/rq#1195]
Hi, I'm tring to empty all the failed queues in my rq.  But I can't seem to pass the password argument via the cli?

I'm using `rq empty failed -u redis://localhost:6380` not sure how to pass the password? I've tried adding `--password` but then it says `-p` not found

**Comment by nadermx** [comment]
Ok, I figured it out, `rq empty failed -u redis://user:password@localhost:6380`

But, this doesn't work, as the password has a `!` so it says `-bash: !@localhost: event not found`

**Comment by lowercase00** [comment]
You can try using quotes, or looking at how to escape characters within redis docs. At last you could try using `RQ_REDIS_URL`
