### ISSUE TITLE
Is it possible to disable args printing in the worker log?

### ISSUE THREAD

**Issue by guyschlider** [rq/rq#1198]
Hi,

I sometimes pass a very long list(20k+ dict objects) as a param to the worker task, it's spamming my logs.

Any documented way to truncated the params being passed to the logs?

Thanks

**Comment by selwin** [comment]
Are you using the latest version of RQ? `job.args` and `kwargs` should only be logged during failures.

I'll accept a PR that truncates args and kwargs logging to a reasonable length.

**Comment by n4cr** [comment]
I use the latest version (1.3) and the args are still printed when a job is added to the queue.

**Comment by selwin** [comment]
Could you please open a PR to truncate args and kwargs logging to a reasonable length?

**Comment by JhonnyBn** [comment]
Sorry, I didn't saw this issue earlier. Answering in case of future search in this topic
> Hi,
> 
> I sometimes pass a very long list(20k+ dict objects) as a param to the worker task, it's spamming my logs.
> 
> Any documented way to truncated the params being passed to the logs?
> 
> Thanks

See [#1263 comment](https://github.com/rq/rq/issues/1263#issuecomment-640112585)

> The best approach I've found is within the worker's parameters, log_job_description=False.
> 
> Example code: worker.py
> 
> ```
> if __name__ == '__main__':
>     with Connection(conn):
>         worker = Worker(map(Queue, listen), log_job_description=False)
>         worker.work()
> ```
> 
> The output now is:
> 
> ```
> 15:28:34 default: job id here
> 15:28:47 default: Job OK ( job id here )
> ```

There's also [documentation of Workers](https://python-rq.org/docs/workers/)

**Comment by isms** [comment]
Looks like this should be closed by #1277

**Comment by lowercase00** [comment]
Fixed in #1277
