### ISSUE TITLE
Support list of failed job registries

### ISSUE THREAD

**Issue by r0fls** [rq/rq#1207]
Prior to upgrading, the failed job queue would contain failed jobs compliled from multiple queues. Now, they're separated into their own failed job registires. Would you accept a PR that creates a new `GlobalFailedJobRegistry`? Or, are there any recommendations for elegant workarounds given the above? Basically our `failed_queue` instance in our codebase went from spanning all queues, to only looking at the failed jobs from default queue, and I'd like to avoid mangling things  too heavily in our codebase to solve this.

Thanks!

**Comment by selwin** [comment]
You can iterate all/some of your queues and use `queue.failed_job_registry.get_jobs()` to list failed jobs.
