### ISSUE TITLE
RQ is causing zombie processes

### ISSUE THREAD

**Issue by marcinn** [rq/rq#1209]
I'm running app on Python 3.7.3.

I've recently upgraded:
* django-rq 1.2.0 -> 2.3.0
* redis 2.10.3 -> 3.4.1 (required as dependency)
* rq 0.12 -> 1.2.2
* rq-scheduler 0.7.1 -> 0.9.1

And now I'm noticing increasing number of zombie processes:

![Firefox_Screenshot_2020-03-06T08-42-22 353Z](https://user-images.githubusercontent.com/139032/76066934-d44c8200-5f8e-11ea-9886-b657277ae3f8.png)

I have entries in crontabs restarting workers every few hours, which saves my ... and this is just why servers are still alive.

Does anybody know what is going on?

**Comment by selwin** [comment]
Please use the master branch to see if it fixes your issue.

Do you have a lot of jobs that are timing out or is crashing? There's a PR merged a few weeks ago that takes care of cleaning up zombie processes: https://github.com/rq/rq/pull/1194 .

**Comment by marcinn** [comment]
Sorry for late reply. Seems that the master branch fixes the issue.

![Firefox_Screenshot_2020-03-09T16-15-30 898Z](https://user-images.githubusercontent.com/139032/76234231-b77fab00-6229-11ea-848a-57151564e7b7.png)

Thank you for a suggestion. Yes, some of our jobs ends with timeouts quite often.
