### ISSUE TITLE
rqinfo output is broken

### ISSUE THREAD

**Issue by marcinn** [rq/rq#1210]
Hi.

I was using older release of RQ and output of rqinfo was readable. Something like this:
```
HostName1.PID: idle default
HostName2.PID: busy default
```

Now I'm using newest RQ (1.2.2) and the output of rqinfo is something like this:
```
aa33cae447dd427d9d9e864fa3129b20 (b'HostName1' PID): idle default
f56ff3f2a3fe450383041d1ad70cacee (b'HostName2' PID): busy default
```

It is less readable now, rows are too long, hostname contains bytes prefix.

It would be handy to provide configuration of output view to add possibility of bringing back readable output. Thanks.

**Comment by selwin** [comment]
RQ >= 1.0 uses UUID as hostname because some docker workflows don't work using autoincrementing worker naming schemes.

**Comment by selwin** [comment]
Reopening the issue since host names don't get properly converted from byte string to regular string.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/commit/8a0153efc8e2e152566a9832cdb7760241538a19

**Comment by marcinn** [comment]
Thank you. Would you accept PR which will give possibility to format/change the output (but leaving the current output as default)? 

In my case (without docker) UUID aren't helpful and they're taking too much space on the screen. I'm using terminal multiplexer with screen splitted by queues (all at one screen). Output is "messed up" due to long lines.
