### ISSUE TITLE
Work horse always killed if started_at present on job before work horse starts

### ISSUE THREAD

**Issue by gord1anknot** [rq/rq#1217]
Hello!

First off, let me say, awesome project, RQ has solved a TON of problems for us! 😄 

We have diagnosed an issue with RQ after upgrade to v1.2.2 we believe is due to #1169, in which the `monitor_work_horse` function kills a job before it's configured `timeout` has elapsed.

Under these circumstances:

1. a job already has a `started_at` property in it's properties hash when it is enqueued.
This would happen if a job is requeued from the failed queue, or a [rq scheduler repeated job](https://github.com/rq/rq-scheduler#periodic--repeated-jobs) is used to enqueue the same job id repeatedly on a schedule. `started_at` is not explicitly cleared from the Job anywhere I can see, so as long as the Job's id remains the same, it will be set
2. The job takes longer than `rq.worker.Worker.job_monitoring_interval` seconds, [which by default is `30`](https://github.com/rq/rq/blob/c4cbb3af2ff7baad1cf4a2319b72324f966df77b/rq/defaults.py#L6-L5), but less than timeout seconds, which [by default is `180`](https://github.com/rq/rq/blob/ed67de22c6e1d40c5f851113ad60b74eaf4f40b4/rq/queue.py#L27)
3. `SimpleWorker` is not used - so there is a fork of the work_horse

When the job is enqueued, the properties are read from Redis into memory on the Job object.
The work horse then forks, and after the fork (not before) in `rq.Worker.perform_job`, the `started_at` value is unconditionally reset without persisting to Redis:

https://github.com/rq/rq/blob/8f7dbf1b1dc392704e0be42292c8787286d962ad/rq/worker.py#L880-L886

This is a problem because the updated_at in the memory of the parent pid doesn't see this update in the event the `started_at` value is already set:

https://github.com/rq/rq/blob/8f7dbf1b1dc392704e0be42292c8787286d962ad/rq/worker.py#L675-L686

If that `started_at` value is more than 30 seconds in the past, `monitor_work_horse` will kill the work horse if it's still running after `rq.worker.Worker.job_monitoring_interval` seconds, instead of `timeout` seconds, which our system was expecting:

https://github.com/rq/rq/blob/8f7dbf1b1dc392704e0be42292c8787286d962ad/rq/worker.py#L687-L695

In our system, we worked around this by overriding `monitor_work_horse`, then removing the contents of PR #1169 from our derived `rq.worker.Worker` worker class already in place.

**Comment by selwin** [comment]
I think the correct solution would be to make sure `job.started_at` is cleared whenever a job is put on the queue. Mind opening a PR for this?

**Comment by pvanderlinden** [comment]
This prevents all jobs from being requeued indeed, started_at should be cleared.

**Comment by selwin** [comment]
Fixed https://github.com/rq/rq/pull/1227
