### ISSUE TITLE
cannot issue SIGINT to subprocess started from rq worker

### ISSUE THREAD

**Issue by djru** [rq/rq#1221]
Hello, I am using an rq worker to pop jobs off of a queue and run some preexisting python scripts in a subprocess. Those scripts may need to be killed using a SIGINT (aka keyboard interrupt). The scrip catches the signal and performs some cleanup before exiting.

**When running a python script via subprocess from an rq worker, the child will not receive SIGINTs.**

I have noticed the child process can be killed using a SIGTERM. The problem is only when using SIGINT.

Here is a trivial example to reproduce:

rq worker:

```
def process(job_id):
    proc = subprocess.Popen('python myscript.py')
```

myscript.py:

```
try:
    while True:
        time.sleep(1)
except:
    print('do my cleanup')
```

`sudo kill -2 <my subprocess pid>`  NOTHING HAPPENS
`sudo kill -9 <my subprocess pid>` SCRIPT EXITS WITHOUT CLEANUP

However, if I run the exact same setup outside the context of a rq worker, the child process receives the signal and and performs its cleanup.

**Comment by selwin** [comment]
That's probably because RQ [setups a signal handler for SIGINT](https://github.com/rq/rq/blob/636d6d2f54bc11da8e97f9cac643b470adf2f5c8/rq/worker.py#L762).

If you know of a way that enables RQ to pass on that signal to another listener within your job, please let me know. I'm also open to other ideas.

**Comment by djru** [comment]
@selwin thanks for looking at this. If these are the only 2 types of signals that are being intercepted (seems that way based on the method linked), I suppose we could send some other type of signal (possibly SIGQUIT).
