### ISSUE TITLE
Job in rq:wip: seems like stuck and cannot finish

### ISSUE THREAD

**Issue by lehoangnam040** [rq/rq#1222]
I have a job running for very long time and it's seems like stuck and cannot finish.
I setup job timeout for this job is 1 day, but normally this job execution is very fast.
Can anyone help me??

![Screenshot from 2020-03-28 14-30-20](https://user-images.githubusercontent.com/31096652/77817882-d5418100-7100-11ea-85e8-63c061710149.png)

**Comment by selwin** [comment]
If your job is fast, consider setting a smaller timeout. RQ doesn't provide a mechanism to check your job's progress so you'll have to handle this on your own.

RQ does periodically check (by default every 30 seconds) if your job is still alive. So if the job hasn't terminated, it's likely that your job is stuck in a loop or something.
