### ISSUE TITLE
scheduler run job one by one, event the jobs at same time. 

### ISSUE THREAD

**Issue by wenbindu** [rq/rq#1223]
Recently, I test the rq worker scheduler. And run three times with function `enqueue_at` at same time. But the job runs one by one. I think this is not so good.
Maybe we can change the scheduler function, to make the jobs run in differrent threads.

**Comment by selwin** [comment]
The scheduler's job is only to enqueue the jobs. Once they're enqueued, jobs will be processed by your workers.

If you want to increase throughput, consider increasing the number of workers.
