### ISSUE TITLE
Better logging for workhorse being terminated

### ISSUE THREAD

**Issue by tomhamiltonstubber** [rq/rq#1228]
So we're just solving an issue where we are using custom Job IDs, and then getting an error in which a new job is being created with the `job.started_at` and `job.ended_at` as values from an older, very recently completed job.

As `job.started_at` is old at this point, it's being killed [here](https://github.com/rq/rq/blob/master/rq/worker.py#L693). It would be great to have more information on why a job was killed here, as all we get in logs is [`Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned None)`](https://github.com/rq/rq/blob/master/rq/worker.py#L720), which isn't particularly helpful, especially considering that something had to have gone very wrong to have caused that to happen.

We're not totally sure at this point how the new job is getting values from the old job, any insight would be welcome.

**Comment by staticfox** [comment]
We're also seeing this with jobs enqueued with rq-scheduler. We're also using custom, fixed job IDs per scheduled, reoccurring job.
![image](https://user-images.githubusercontent.com/6256971/78756704-1707ce00-7930-11ea-8b2d-5fa8653f5ca8.png)

**Comment by selwin** [comment]
>> So we're just solving an issue where we are using custom Job IDs, and then getting an error in which a new job is being created with the job.started_at and job.ended_at as values from an older, very recently completed job.

Make sure the custom Job IDs you create are unique, the easiest way would be to use UUID as job IDs.

>> As job.started_at is old at this point, it's being killed here. It would be great to have more information on why a job was killed here, as all we get in logs is Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned None), which isn't particularly helpful, especially considering that something had to have gone very wrong to have caused that to happen.

If you're getting this message, this really means RQ has no idea what happened to the work horse. In my experience, most of the time the job is killed by the OS itself (perhaps for using too much memory or some other reasons).

>> We're also seeing this with jobs enqueued with rq-scheduler. We're also using custom, fixed job IDs per scheduled, reoccurring job.

Like I mentioned, RQ expects job IDs to be unique. If you're reusing the same job ID for a recurring job, don't forget to clear `job.started_at` and `job.ended_at` when requeuing jobs. See [this PR](https://github.com/rq/rq/pull/1227).
