### ISSUE TITLE
"rq worker" -> ResponseError: wrong number of arguments

### ISSUE THREAD

**Issue by mrx23dot** [rq/rq#1231]
On Win7 x64, rq-1.2.2 also rq-1.3.0

starting "rq worker" out of the box gives:

> 
> 22:21:07 Worker rq:worker:3efd74e7e6c04e1dadc0d9de4acf5832: started, version 1.2.2
> 22:21:07 *** Listening on ←[32mdefault←[39;49;00m...
> 22:21:07 ←[31mWorker rq:worker:3efd74e7e6c04e1dadc0d9de4acf5832: found an unhandled exception, quitting...←[39;49;00m
> Traceback (most recent call last):
>   File "c:\python36\lib\site-packages\rq\worker.py", line 500, in work
> ......
>     return self.execute_command('SET', *pieces)
>   File "c:\python36\lib\site-packages\redis\client.py", line 878, in execute_command
>     return self.parse_response(conn, command_name, **options)
>   File "c:\python36\lib\site-packages\redis\client.py", line 892, in parse_response
>     response = connection.read_response()
>   File "c:\python36\lib\site-packages\redis\connection.py", line 752, in read_response
>     raise response
> redis.exceptions.ResponseError: wrong number of arguments for 'set' command
> 
> server:
> [5600] 14 Apr 22:20:54 * Server started, Redis version 2.4.5
> [5600] 14 Apr 22:20:54 # Open data file dump.rdb: No such file or directory
> [5600] 14 Apr 22:20:54 * The server is now ready to accept connections on port 6379
> [5600] 14 Apr 22:20:55 - 0 clients connected (0 slaves), 672768 bytes in use
> [5600] 14 Apr 22:21:00 - 0 clients connected (0 slaves), 672768 bytes in use
> [5600] 14 Apr 22:21:05 - 0 clients connected (0 slaves), 672768 bytes in use
> [5600] 14 Apr 22:21:07 - Accepted 127.0.0.1:51905
> [5600] 14 Apr 22:21:07 - Client closed connection
> [5600] 14 Apr 22:21:10 - DB 0: 1 keys (1 volatile) in 4 slots HT.
> [5600] 14 Apr 22:21:10 - 0 clients connected (0 slaves), 673972 bytes in use

**Comment by mrx23dot** [comment]
got broken in rq==1.2.2

**Comment by selwin** [comment]
Windows is not supported.
