### ISSUE TITLE
ChildProcessError: [Errno 10] No child processes

### ISSUE THREAD

**Issue by levrik** [rq/rq#1234]
After upgrading from RQ 1.1.0 to 1.3.0 I'm seeing the above error with my custom worker class.

That custom class is quite similar to the HerokuWorker:
```python
class JobCancelledException(Exception):
    pass


class CustomWorker(Worker):
    DEFAULT_JOB_CANCEL_TIMEOUT = 60

    def __init__(self, *args, job_cancel_timeout=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.job_cancel_timeout = (
            parse_timeout(job_cancel_timeout) or self.DEFAULT_JOB_CANCEL_TIMEOUT
        )

    def handle_warm_shutdown_request(self):
        if self.horse_pid != 0:
            self.log.info(
                "Warm shut down requested, requesting delayed cancelling of running job"
            )
            self.kill_horse(sig=signal.SIGTERM)
        else:
            self.log.info("Warm shut down requested")

    def setup_work_horse_signals(self):
        """Setup signal handing for the newly spawned work horse."""
        signal.signal(signal.SIGINT, signal.SIG_IGN)
        signal.signal(signal.SIGTERM, self.request_stop_sigterm)

    def request_stop_sigterm(self, signum, frame):
        signal.signal(signal.SIGALRM, self.request_force_stop_sigterm)
        signal.alarm(self.job_cancel_timeout)

    def request_force_stop_sigterm(self, signum, frame):
        raise JobCancelledException(
            "Task cancellation exceeded maximum timeout value "
            "({0} seconds)".format(self.job_cancel_timeout)
        )
```

The exception is raised by the call to `os.waitpid` in the `monitor_work_horse` function.
This seems to have been introduced by #1194. If I revert this change, the process exits without that exception after the timeout.
I think that the `os.waitpid` call in `kill_horse` is blocking the thread and when execution continues, the `os.waitpid` in `monitor_work_horse` doesn't have anything to monitor anymore and raises.
I didn't try the HerokuWorker but since the setup is basically the same, I think we're facing the same issue there.

Actually this issue seems to happen only before the first `os.waitpid` in `monitor_work_horse` timed out.

I'm still investigating more.

**Comment by levrik** [comment]
I think I figured out some more details here.

If I'm killing the work-horse in `handle_warm_shutdown_request()` the call to `kill_horse` blocks until my timeout expires. That basically means that `self._stop_requested` was also never set to `True` because the worker never got there.

**Comment by selwin** [comment]
Obviously I don't know the context of you needing to use a custom worker class, but I can think of a few ways to make your life easier.

>> If I'm killing the work-horse in handle_warm_shutdown_request() the call to kill_horse blocks until my timeout expires. That basically means that self._stop_requested was also never set to True because the worker never got there.

I'm okay with changing the behavior of `request_stop()` to always set `._stop_requested` to `True` when it's first called. This way, `_stop_requested` will always be `True` when `handle_warm_shutdown_request()` is called.

>> I also see that waitpid call in kill_horse doesn't seem to ever resolve when the process is getting killed by SIGALRM later.

This is a bug that needs to be fixed. There are two posssible solutions I can think of:
1. Maybe there are arguments we can pass to `os.waitpid()` to fix this
2. If there's not, we may need to implement our own timeout behavior so this piece of code doesn't hang.

**Comment by wevsty** [comment]
Call `kill_horse()` in `handle_warm_shutdown_request()`  generates a ChildProcessError I think because `kill_horse( )` and `monitor_work_horse()` for the same PID twice call the `os.waitpid()`.

>     1. Maybe there are arguments we can pass to `os.waitpid()` to fix this
You can make the function return immediately by adding the `os.WNOHANG` parameter to `os.waitpid()`. But I don't think this is a good idea. The problem with executing `os.waitpid()` multiple times remains.

My solution is to split `kill_horse()`  functions, and then pair the `handle_warm_shutdown_request()` makes some changes.
This will avoid zombie processes and will not repeat the execution of os.waitpid().

I'll resubmit a PR to fix this.

**Comment by levrik** [comment]
The changes by @wevsty actually fixed all issues I was experiencing while trying to update to 1.3.0 from 1.1.0
I've successfully upgraded to 1.5.2 now with my custom timeout logic still in place.
Thanks a lot. I'll close this issue.
