### ISSUE TITLE
Could delay() also accept an argument specifying job id?

### ISSUE THREAD

**Issue by grayshirt** [rq/rq#1236]
#415 added an argument to `enqueue()` allowing the caller to specify the id of the job being created. Is it intentional that the `delay()` method of functions decorated with `@job` does not offer the same behavior?

No big deal but I did run into this when I tried switching some uses from `enqueue` to `delay` for the purpose of specifying some common job metadata on the decorated function itself, rather than having to make sure to do so in the several places that function might be enqueued.

**Comment by selwin** [comment]
PR welcome :).
