### ISSUE TITLE
Error in handle_job_success(): TypeError caused by job.started_at

### ISSUE THREAD

**Issue by mkushnir** [rq/rq#1239]
Look like a case when None in _job.started_at_ is not handled properly:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 895, in perform_job
    started_job_registry=started_job_registry)
  File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 852, in handle_job_success
    job.ended_at - job.started_at, pipeline
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```

**Comment by selwin** [comment]
Do you know how to reproduce this error?

**Comment by mkushnir** [comment]
Hi Selwin,

I found it in my work project.  I will see how I can make a minimal repro.

--
Markiyan.

2020-04-24 4:14 GMT+03:00, Selwin Ong <notifications@github.com>:

**Comment by mkushnir** [comment]
Hi Selwin,

It turns our to be not that trivial to figure it out.  The first thing
is that this error occurs from time to time, and seems to depend on
some timing condition between Python and Redis.  The other thing is
that it occurs in the context of a worker, specifically in a forked
job.  A worker function accesses the instance of the current job via
rq.get_current_job(), then essentially updates the contents of "meta"
property of the current job within a sequence of
job.refresh()...job.save().  I could not find any code that messes up
with other properties, especially "started_at".  With all that said, I
could not reproduce the case without directly clearing the
"started_at" property in a worker function, something along these
lines:

from redis import Redis
from rq import get_current_job, Connection

conn = Redis()
def testfoo(*args, **kwargs):
    with Connection(conn):
        j = get_current_job()
        j.started_at = None # XXX

This trivial worker function would raise the exception I had reported.
Please let me know if it makes sense ti fix it similarly to how it is
done in Worker.handle_job_failure().

--
Markiyan

2020-04-24 10:09 GMT+03:00, Markiyan Kushnir <markiyan.kushnir@gmail.com>:

**Comment by selwin** [comment]
If all you need is to save `job.meta`, try using `job.save_meta()` to see if that solves your issue. `save_meta()` is made exactly for this purpose, to add custom metadata to a job without tampering with other job properties.

If this fixes your problem, I'd appreciate your help in adding this to the docs :)

**Comment by mkushnir** [comment]
Hi Selwin,

I used save_meta() as you suggested, however, ho luck. I was still
hitting exceptions in handle_job_success().  I will leave this method
in my code, since this is exactly the one I need there.

I also tried to trace the problem on a live application a bit harder,
it looks like it occurs when there is quite a high load of jobs...

I currently cannot think of any better idea as to add a check to
handle_job_success().

--
Markiyan.

2020-05-03 13:38 GMT+03:00, Selwin Ong <notifications@github.com>:

**Comment by selwin** [comment]
The thing is, I looked through the codes at `worker.execute_job()`, I don't see how `job.started_at` can be `None` when `handle_job_success()` is called. If there's a bug in the code, I'd like to get it fixed instead of just checking for the existence of `job.started_at` and `job.ended_at`.

`handle_job_failure()` checks for the existence of both because it's a failure case.

**Comment by mkushnir** [comment]
Closing the issue, I could not find a reliable reproduce of the problem.  I also fixed it in my project by reducing data exchange between rq worker and redis.
