### ISSUE TITLE
monitor_work_horse prematurely kills recurring scheduled jobs due to stale started_at

### ISSUE THREAD

**Issue by rmartin48** [rq/rq#1241]
I use [rq-scheduler](https://github.com/rq/rq-scheduler) (via [django-rq-scheduler](https://github.com/isl-x/django-rq-scheduler)) to do cron style job scheduling. As indicated by @selwin [in this issue](https://github.com/rq/rq/issues/1208#issuecomment-618757142), `rq-scheduler` re-uses the same `job.id` every time a job in re-enqueued which can lead to unexpected behaviour.

One unexpected behaviour that I am experiencing is any recurring job that takes longer than the `DEFAULT_JOB_MONITORING_INTERVAL` of 30 seconds gets killed prematurely by `monitor_work_horse`.

For example, the following job should take 45 seconds to execute and then exit cleanly. The first time it is enqueued, it runs as expected. However, on every subsequent run the work horse is killed.
```
@job(timeout=60)
def long_job():
    print("running...")
    time.sleep(45)
    print("completed")
```
If I schedule the job to run every 5 minutes, it results in this:
```
09:00:00 running...
09:00:45 completed

09:05:00 running...
09:00:30 Killed horse pid 1234
09:00:30 Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned None)
```

The following code in `monitor_work_horse` is responsible for killing the work horse:
```
# Kill the job from this side if something is really wrong (interpreter lock/etc).
if job.timeout != -1 and (utcnow() - job.started_at).total_seconds() > (job.timeout + 1):
    self.kill_horse()
    break
```
I was able to determine that `job.started_at` was referencing the time that the job was first run, not the time that the current job was started and therefore was exceeding `job.timeout`.

Further, `prepare_job_execution` and `perform_job` both attempt to set `job.started_at` on the current job so I was confused as to why `monitor_work_horse` was reporting the wrong time. My understanding though is that `prepare_job_execution` and `perform_job` are both executed inside the work horse after it is forked and `monitor_work_horse` executes in the worker, so the updated `started_at` value is not available to the worker.

I am happy to raise a PR to fix this, but I wanted to get the opinion of the package authors on the best way to go about it. I have fixed it in a fork by changing the following line in `monitor_work_horse` so that `job.started_at` always get overwritten:
`job.started_at = job.started_at or utcnow()` -> `job.started_at = utcnow()`. It could also be fixed by moving the `started_at` related work of `prepare_job_execution` and `perform_job` to just prior to the work horse fork.

(Thanks to the maintainers of this excellent package!)

**Comment by selwin** [comment]
Are you using the latest version of RQ? This should already be fixed in [this commit](https://github.com/rq/rq/commit/5f949f4cefed67de2554ef8dfc08bd62142a52a4).

**Comment by rmartin48** [comment]
I'm running commit [cfe389b](https://github.com/rq/rq/commit/cfe389bd65769ef1db7c01dbda11a6ba61e621c4) which is a later  commit than the one you have referenced.  In fact, line 679 from that commit is what causes the issue as `job.started_at` is already defined on the recurring job, so it doesn't get reset. I'm suggesting line 679 becomes `job.started_at = utcnow()` to ensure any previous value is overridden.

**Comment by selwin** [comment]
Ah yes you’re right. Your proposed fix looks good to me.

**Comment by zoltan-fedor** [comment]
I just hit the exact same issue.
Named cron jobs only succeed at the first run and then throw 

> "Killed horse pid"

error at 30 seconds.

I think fixing this would justify a bugfix release.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1242
