### ISSUE TITLE
Fix Redis DeprecationWarning: Pipeline.hmset() is deprecated. Use Pipeline.hset() instead.

### ISSUE THREAD

**Issue by adamchainz** [rq/rq#1244]
rq.job and other places are triggering this warning from redis:

```
Pipeline.hmset() is deprecated. Use Pipeline.hset() instead.
```

This was deprecated in redis 3.5.0: https://github.com/andymccurdy/redis-py/blob/252c840ea2ade01637b4ed7c834dd83b130041b4/CHANGES#L17

**Comment by selwin** [comment]
Mind opening a PR for this?

**Comment by adamchainz** [comment]
I don't have the time myself.

**Comment by selwin** [comment]
@bbayles I had to revert your PR in https://github.com/rq/rq/pull/1260 because it's causing crashes in deployments with [Redis server < 4.0](https://github.com/rq/rq/issues/1256).

**Comment by bbayles** [comment]
Alas! The docs aren't quite clear on what Redis server and `redis-py` versions are required/supported. Perhaps they could be updated to be more specific? Currently the front page says:
> RQ requires Redis >= 3.0.0.

And `requirements.txt` says:
> redis>=3.0

Is it a coincidence that the versions are the same?

**Comment by tomhamiltonstubber** [comment]
For clarity, is this an issue or not?

On 1.4.2 I'm still getting a deprecation warning with redis v5.

Happy to create a PR.

**Comment by dmitrypol** [comment]
+1

**Comment by selwin** [comment]
@tomhamiltonstubber yes it's still an issue since the previous PR is crashing deployments on Redis server < 4. @aparcar plans to work on a PR that adds [Redis server version awareness](https://github.com/rq/rq/pull/1271#discussion_r446564849) to RQ. Hopefully we can get this patch in after this change.

**Comment by aparcar** [comment]
What about this case here? https://github.com/rq/rq/blob/master/rq/job.py#L147 It uses `hset` directly instead of the compat function `hmset`? Just trying to understand the current setup

**Comment by aparcar** [comment]
Related https://github.com/rq/rq/pull/1286

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1286/files
