### ISSUE TITLE
hmset/hset change causing worker crash

### ISSUE THREAD

**Issue by bxjw** [rq/rq#1256]
With [this update](https://github.com/rq/rq/pull/1253), I find myself getting the following error when starting a worker on Heroku:

> app/worker.1 redis.exceptions.ResponseError: Command # 2 (HSET rq:worker:d10e75607d00442686c9856744c639e1 birth 2020-05-20T19:32:16.172931Z last_heartbeat 2020-05-20T19:32:16.172931Z queues high,default,low pid 4 hostname c919b373-dde4-48af-a9f7-2760ed9acb5a version 1.4.1 python_version 3.7.5 (default, Oct 17 2019, 21:38:12) 
app/worker.1 [GCC 7.4.0]) of pipeline caused error: wrong number of arguments for 'hset' command

When I use 1.4.0 prior to this PR, it seems to work all right.

**Comment by dumar** [comment]
same issue, 
```
python 3.8.3
rq==1.4.1
redis==3.5.2
```

`Redis server v=3.0.6`

**Comment by nazywam** [comment]
This might be related to the change of `hset` command siganture in redis server.
In [this commit](https://github.com/antirez/redis/commit/01a4b9892d0922eeafbb1bfba0f9fa70bf1a2f3b) it was converted to variadic.

This came up just now because rq started using `hset` in the [pull request](https://github.com/rq/rq/pull/1253/) linked by bxjw.

I've performed a super basic test and it seems to fail on `redis server 3.2.13` and work on redis server `4.0.0`

So if you're having problems, try upgrading your redis-server to version `>= 4.0.0`

**Comment by selwin** [comment]
I don't have a Redis server < 4.0 handy to test this issue with. @bxjw @dumar do you mind checking whether [this patch](https://github.com/rq/rq/pull/1260) fixes your problem?

**Comment by rbed23** [comment]
I just found myself having the same issue, solved it by reverting back to 1.2.2, good to know I could have downed to 1.4.0...

[stack-details-here](https://stackoverflow.com/questions/61972101/issue-deploying-heroku-app-rq-worker-wrong-number-of-arguments-for-hset-com/61983542#61983542)

**Comment by selwin** [comment]
@rbed23 can you try to see if https://github.com/rq/rq/pull/1260 solves your issue?

**Comment by rbed23** [comment]
fyi, Im running my dev environment with the following setup, without problem:

> python 3.7.4
> redis 3.4.1
> rq 1.4.1

but when I deploy my project up as a Heroku app, that is when I get the HSET failure...

Python 3.7.4 (default, May 11 2020, 15:58:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import redis, rq
\>\>\> redis.\_\_version\_\_
'3.4.1'
\>\>\> rq.\_\_version\_\_
'1.4.1'
\>\>\>

**Comment by rbed23** [comment]
and after deploying the project to Heroku, now it works (sans #1260 change)...

> app[api]: Deploy 5907f43c by user rbed23
> app[api]: Release v19 created by user rbed23
> heroku[web.1]: Starting process with command `bash heroku.sh`
> app[web.1]: [heroku-exec] Starting
> app[web.1]: {'connection': Redis<ConnectionPool<Connection<host=pike.redistogo.com,port=11022,db=0>>>, 'hostname': '00247b8e-34d7-4d32-8d9a-1fd3a70722ff', 'pid': 39, 'job_class': <class 'rq.job.Job'>, 'queue_class': <class 'rq.queue.Queue'>, 'version': '1.4.1', 'python_version': '3.7.4 (default, Sep 12 2019, 01:19:52) \n[GCC 7.4.0]', 'serializer': <class 'rq.serializers.DefaultSerializer'>, 'name': '40dc5144801f4c019ff3e90692e62719', 'queues': [Queue('default')], '_exc_handlers': [], 'default_result_ttl': 500, 'default_worker_ttl': 420, 'job_monitoring_interval': 30, '_state': 'starting', '_is_horse': False, '_horse_pid': 0, '_stop_requested': False, 'log': <Logger rq.worker (WARNING)>, 'log_job_description': True, 'last_cleaned_at': None, 'successful_job_count': 0, 'failed_job_count': 0, 'total_working_time': 0, 'birth_date': None, 'scheduler': None, 'disable_default_exception_handler': False}
> app[web.1]: 14:38:29 Worker rq:worker:40dc5144801f4c019ff3e90692e62719: started, version 1.4.1
> app[web.1]: 14:38:29 *** Listening on default...
> app[web.1]: 14:38:29 Cleaning registries for queue: default
> heroku[web.1]: State changed from starting to up

and Ive confirmed the same envr on the Heroku app as my dev

**Comment by rbed23** [comment]
replicated the original error (on Heroku) after upgrading redis to 3.5.2... my local dev envr ran it fine (running Python 3.7.4 GCC 8.3.0)

Python 3.7.4 (default, Sep 12 2019, 01:19:52)
[GCC 7.4..0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import redis, rq
\>\>\> redis.\_\_version\_\_
'3.5.2'
\>\>\> rq.\_\_version\_\_
'1.4.1'


> app[api]: Deploy 60c3286f by user rbed23@gmail.com
> heroku[web.1]: Starting process with command `bash heroku.sh`
> app[web.1]: [heroku-exec] Starting
> app[web.1]: {'connection': Redis<ConnectionPool<Connection<host=pike.redistogo.com,port=11022,db=0>>>, 'hostname': 'f22bbdcd-a388-44a2-96f4-91da837652b8', 'pid': 39, 'job_class': <class 'rq.job.Job'>, 'queue_class': <class 'rq.queue.Queue'>, 'version': '1.4.1', 'python_version': '3.7.4 (default, Sep 12 2019, 01:19:52) \n[GCC 7.4.0]', 'serializer': <class 'rq.serializers.DefaultSerializer'>, 'name': 'f1277dfa595942ce95abd3d6e7d93fd8', 'queues': [Queue('default')], '_exc_handlers': [], 'default_result_ttl': 500, 'default_worker_ttl': 420, 'job_monitoring_interval': 30, '_state': 'starting', '_is_horse': False, '_horse_pid': 0, '_stop_requested': False, 'log': <Logger rq.worker (WARNING)>, 'log_job_description': True, 'last_cleaned_at': None, 'successful_job_count': 0, 'failed_job_count': 0, 'total_working_time': 0, 'birth_date': None, 'scheduler': None, 'disable_default_exception_handler': False}
> **app[web.1]: Command # 2 (HSET rq:worker:f1277dfa595942ce95abd3d6e7d93fd8 birth 2020-05-24T15:00:52.757180Z last_heartbeat 2020-05-24T15:00:52.757180Z queues default pid 39 hostname f22bbdcd-a388-44a2-96f4-91da837652b8 version 1.4.1 python_version 3.7.4 (default, Sep 12 2019, 01:19:52)
> app[web.1]: [GCC 7.4.0]) of pipeline caused error: wrong number of arguments for 'hset' command**
> heroku[web.1]: Process exited with status 0

**Comment by selwin** [comment]
I released 1.4.2 on PyPI to address this. Please check whether it works properly and reopen if needed. Thanks!

**Comment by bxjw** [comment]
It works, thanks @selwin !

**Comment by rbed23** [comment]
@selwin I can confirm 1.4.2 works with redis 3.5.2

great work, thanks so much!
