### ISSUE TITLE
How workers consumes the CPU of the instance

### ISSUE THREAD

**Issue by AnandMoorthy** [rq/rq#1262]
Hi All,

I have a 2 workers which execute the same function, I am looping through my code to create a job for the queue. But when the queue starts to process the jobs, the CPU consumption is barely hitting 15 percentage. how can I config the RQ to consume maximum CPU to process the jobs quicker.

I really want to understand how the RQ is performing with multiple workers if I span 10 workers in the 2 core instance will it work faster or RQ will run only 2 jobs parallelly.

This is my code for initiating worker

```
import os

import redis
import multiprocessing

from rq import Worker, Queue, Connection

listen = ['images']

redis_url = os.getenv('REDISTOGO_URL', 'redis://127.0.0.1:6379')

conn = redis.from_url(redis_url)

worker_count = 2

if __name__ == '__main__':
    with Connection(conn):
        for i in range(worker_count):
            multiprocessing.Process( target=Worker(listen).work ).start()
```

**Comment by KonstantinSchubert** [comment]
Is it possible that your jobs are I/O bound?

If each worker runs in a separate OS process, and if your worker processes spend a lot of time in I/O wait, then running 10 workers should be faster than 2.

But I am arguing from first principles here - have you tried it?

**Comment by selwin** [comment]
How much RQ consumes your CPU is based entirely on the jobs you throw at it. If you have two workers running simultaneously and they consume 15% CPU, you should get the same result if you use two different processes to run your functions without relying on RQ.
