### ISSUE TITLE
Mocking RQ connection

### ISSUE THREAD

**Issue by kylejohnson** [rq/rq#1268]
I've seen this come up a few times (#282), however all of those issues are many years old, and while the docs [have a little information](https://python-rq.org/docs/testing/) on using `FakeStrictRedis`, that's not all of what I need.

How can you use mock to patch `rq.Queue` to use `FakeStrictRedis` (if that is the right approach)?

Essentially I am trying to add test coverage to a part of my code which relies on the number of jobs in a queue, and then does more work, or exits, based on the queue size.

Here is what I am trying:

My example code:
```
def fubar(self):
    q = Queue(connection=Redis("real-redis-server", 6379))
    j = len(q)

    if j > 0:
        print("Queue is not empty.  Not adding additional jobs.")
        return
    else:
        # add more jobs
        # ...
```

And my example test:
```
def test_queues_empty(self):
    with mock.patch("rq.Queue") as mock_rq:
        mock_rq.return_value.connection.return_value = FakeStrictRedis()

        self.main.fubar()
```

The tests just hang, because I'm not patching the right object, so the code is still trying to connect to "real-redis-server"

**Comment by selwin** [comment]
It depends on what you want to achieve.

If what you want to test is the number of enqueued jobs, you can:
1. Mock `queue.enqueue()`
2. Check for `len(queue)` to check for number of enqueued jobs

If what you want is to run tests without a real Redis server, you shouldd use a library that mocks Redis connection.
