### ISSUE TITLE
RQ should truncade job args/kwargs to a reasonable length by default

### ISSUE THREAD

**Issue by JhonnyBn** [rq/rq#1269]
> Apart from that, I think RQ should also truncate job args/kwargs to a reasonable length by default. A PR for this would be much appreciated.

_Originally posted by @selwin in https://github.com/rq/rq/issues/1263#issuecomment-639194904_

Logging job's description with huge arguments makes terminal unreadable and log files too large.
It would be nice if arguments with more than N characters, let's say 100, get truncated.

I guess this could be done [here](https://github.com/rq/rq/blob/29222ea12f/rq/worker.py#L585) (worker.py where it prints job's description) or [here](https://github.com/rq/rq/blob/29222ea12f822e29307ee7ba674166d5031b3ae4/rq/job.py#L668) 
 (job.py, function that creates jobs' descriptions)

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1277
