### ISSUE TITLE
First release of RQ Monitor

### ISSUE THREAD

**Issue by pranavgupta1234** [rq/rq#1273]
Hello RQ Fam,

I have been working with RQ for quite some time now. Its simple and great. For monitoring purposes I have checked out [rq-dashboard](https://github.com/Parallels/rq-dashboard) previously and it gets the job done but I felt there was room for improvement and some missing functionalities which I wanted so I was working on the creating some kind of monitoring dashboard and today I am releasing first production ready version of [rqmonitor](https://github.com/pranavgupta1234/rqmonitor). Sharing here so that people can give it a try and provide feedback so more improvements can be done.

**Comment by selwin** [comment]
Congrats on the release!

A link to `rqmonitor` has been added to https://github.com/rq/rq/blob/master/README.md so I'm going to close this issue.
