### ISSUE TITLE
Creating job using static methods causes resolving error

### ISSUE THREAD

**Issue by KHN190** [rq/rq#1275]
This might not be a bug, but I asked the question first on stackoverflow so I think I should plainly paste it [here](https://stackoverflow.com/questions/62371945/rq-job-creating-not-correctly-resolve-namespace).

Thanks for advice!

**Comment by nmanovic** [comment]
It looks like the problem with the code. The static method (A.f) is resolved as 'module.f' instead of 'module.A.f'.  A possible solution is to use `func.__qualname__` instead of `func.__name__` in the code below in rq/job.py.

```
        elif inspect.isfunction(func) or inspect.isbuiltin(func):
            job._func_name = '{0}.{1}'.format(func.__module__, func.__name__)
```
