### ISSUE TITLE
[Help wanted] Redis maxmemory-policy: add or not for RQ use-case?

### ISSUE THREAD

**Issue by transhapHigsn** [rq/rq#1280]
Hi,

I am running RQ with maxmemory-policy directive enabled in redis. Is it good idea or am i risking losing jobs due to that? Especially in cases where i am queuing 5k+ jobs at a time.

Note: I am using redis server as a cache too.

```
maxmemory = 1gb
maxmemory-policy = allkeys-lfu
```

**Comment by selwin** [comment]
Well, since RQ relies on Redis for its storage, you'll lose data if Redis decides to evict RQ related keys from storage.

**Comment by transhapHigsn** [comment]
@selwin even though latency is very low between job scheduling and job execution? The case is i have limited resources, and i want to use ti in the best way i can. Is there a better approach to this problem?
