### ISSUE TITLE
Can a task reschedule itself? If yes, how does this affect dependent tasks

### ISSUE THREAD

**Issue by MW3000** [rq/rq#1283]
I have tasks that work with web resources. If a web-server is not reachable when the task is running, can the task reschedule _itself_ and rerun after a certain time? If so, how?

If this is possible and the task has dependent tasks, how does rescheduling the task affect its dependent tasks?

**Comment by selwin** [comment]
Dependent tasks will only execute after successful execution of task it depends on.

RQ supports [scheduled job execution](https://python-rq.org/docs/scheduling/), but there's currently no way to configure retries on failed job execution in RQ (although I plan on working on it soon-ish).

**Comment by MW3000** [comment]
>  but there's currently no way to configure retries on failed job execution in RQ (although I plan on working on it soon-ish).

I look forward to this feature. It would come in very handy.

**Comment by inactivist** [comment]
@selwin wrote:
> Dependent tasks will only execute after successful execution of task it depends on.
> 
> RQ supports [scheduled job execution](https://python-rq.org/docs/scheduling/), but there's currently no way to configure retries on failed job execution in RQ (although I plan on working on it soon-ish).

I'd like to assist with this if possible.  Is there a feature branch in the works?

**Comment by adamb70** [comment]
@inactivist Looks like this is being actively developed now #1299.
