### ISSUE TITLE
Marking a job as failed from within without throwing an exception

### ISSUE THREAD

**Issue by DavidVentura** [rq/rq#1297]
How do I mark a job as failed from within without throwing an exception?
I like having things that are determined at runtime as having failed in the `failed` queue so they can be re-tried, but when I show the logs for a task execution I always end up with a stacktrace, the jobs throw a fake exception to mark themselves as failed

is there a better way?

**Comment by selwin** [comment]
You can build this logic into the function that's enqueued. Instead of raising an exception, you can requeue a new job so it can be picked up again by RQ.

**Comment by DavidVentura** [comment]
I am only interested in the mark-as-failed part, retrying things or re-queueing things is not an issue
