### ISSUE TITLE
rq worker sending all output to stderr

### ISSUE THREAD

**Issue by oduspace** [rq/rq#1298]
My worker processes appear to be sending all output to stderr. Nothing is being sent to stdout. Is this normal behaviour for rq?
I've been struggling to get supervisord to separate worker output between stderr/stdout.

This is what I see when I kick off a worker from the command line to see where the output goes:

```
rq worker low 2> >(while read line; do echo "$(tput setaf 1)STDERR: $(tput sgr0)$line" >&2; done)
STDERR: 10:53:30 Worker rq:worker:ff2d9bdfff464a81b7df6c5b08ed9ce8: started, version 1.4.3
STDERR: 10:53:30 *** Listening on low...
```
I'd expected this to go to stdout.

**Comment by selwin** [comment]
PR welcome :)

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1312
