### ISSUE TITLE
Worker events (experimental)

### ISSUE THREAD

**Issue by nvie** [rq/rq#13]

**Comment by klausenbusk** [comment]
Maybe a event when the job finish?
So I can do something more efficiency than this:
```
while job.result is None:
        pass
```
I have a &wait=1 option for my API.
Could we reopen this issue?

**Comment by proofit404** [comment]
@klausenbusk Any kind of events is unnecessary in this case. We already have some circumstances under which we can determine job is done. It is job hash modification and job hash expiration with job id stored in the failed queue. I can *guess* that it is possible to observe this actions with redis pub/sub and implement api like this.
```python
job = queue.enqueue(my_awesome_function)
try:
    job.wait()
except ConnectionClosed:
    raise Http500
if job.is_failed:
    raise Http500
return response(job.result)
```
Maybe @nvie can clarify my guesswork. But in any case I doesn't think that `rq` needs some kind of event passing machinarium.

**Comment by klausenbusk** [comment]
> implement api like this

Something like that will be perfect. I don't think polling until the job has finish is optimal (at least not when doing it hundreds times a seconds, `time.sleep(0.05)` will help on that through).

**Comment by proofit404** [comment]
In my opinion polling can't be optimal way in any case.

**Comment by selwin** [comment]
The best way to do this would be to use Redis' pub/sub feature to publish an event, whether it's job start, finished or failed so interested parties can just subscribe to the channel should they need to.

**Comment by proofit404** [comment]
@selwin So this should be a part of `registry` module?
