### ISSUE TITLE
Version 1.5.0 no longer works with FakeRedis

### ISSUE THREAD

**Issue by atainter** [rq/rq#1307]
Hi, 

I tried upgrading to 1.5.0 from 1.1.0, but it looks like all of my integration tests are failing because 1.5.0 is incompatible with `fakeredis`. I was initially using `fakeredis` 1.1.0, but I upgraded to 1.4.1 and it still doesn't work. Normally, I wouldn't expect this to be compatible with another 3rd party library, but it's the suggested method for testing in the [docs](https://python-rq.org/docs/testing/#running-jobs-in-unit-tests). 

Can anyone help? Here's my stack trace. Looks like it's calling an [unsupported command](https://github.com/jamesls/fakeredis#server)

```
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/rq/queue.py:425: in enqueue
    at_front=at_front, meta=meta, retry=retry
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/rq/queue.py:368: in enqueue_call
    job = self.enqueue_job(job, at_front=at_front)
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/rq/queue.py:476: in enqueue_job
    job.save(pipeline=pipe)
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/rq/job.py:585: in save
    if self.get_redis_server_version() >= StrictVersion("4.0.0"):
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/rq/job.py:594: in get_redis_server_version
    self.connection.info("server")["redis_version"]
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/redis/client.py:1306: in info
    return self.execute_command('INFO', section)
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/redis/client.py:901: in execute_command
    return self.parse_response(conn, command_name, **options)
../../.pyenv/versions/3.7.2/envs/authz-service@3.7.2/lib/python3.7/site-packages/redis/client.py:915: in parse_response
    response = connection.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = FakeConnection<server=<fakeredis._server.FakeServer object at 0x10e652cc0>,db=0>

    def read_response(self):
        if not self._server.connected:
            try:
                response = self._sock.responses.get_nowait()
            except queue.Empty:
                raise redis.ConnectionError(CONNECTION_ERROR_MSG)
        else:
            response = self._sock.responses.get()
        if isinstance(response, redis.ResponseError):
>           raise response
E           redis.exceptions.ResponseError: unknown command 'INFO'
```

**Comment by selwin** [comment]
From my perspective, it's upon the mocking library to mock the functionalities of the class it's mocking.

I'm open to receving a PR to address this if it can be solved elegantly, but if this is not fixed within a few days, I think I'll remove the mention of `FakeRedis` from the docs.

I don't have much free time these days and this is simply not high on my to do list. I have a few significant things that I want to  implement for RQ.

**Comment by atainter** [comment]
> From my perspective, it's upon the mocking library to mock the functionalities of the class it's mocking.
I totally agree, just posting this here because it was mentioned in the docs. 

I ended up subclassing `fakeredis` and mocking the `info` method. It works for my issue right now. Hopefully `fakeredis` supports this method in the future.

```python
class InMemoryRedis(FakeStrictRedis):
    """
    Subclassed to support unimplemented features for RQ
    """

    def info(self, section=None):
        return {"redis_version": "5.0.7"}

```

**Comment by selwin** [comment]
Can you confirm that `fakeredis` raises `redis.exceptions.ResponseError` exception when `command` is called? @atainter.

I just merged a [PR](https://github.com/rq/rq/pull/1322/files) that centralizes redis server version checks so it'll be easier to handle this.

**Comment by atainter** [comment]
Confirmed: `redis.exceptions.ResponseError: unknown command 'INFO'`

**Comment by selwin** [comment]
This should be fixed in master.
