### ISSUE TITLE
Queued Jobs fail with -> time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'

### ISSUE THREAD

**Issue by jjohnsontrilogy** [rq/rq#1309]
Similar issue to [1282](https://github.com/rq/rq/issues/1282) - but the solution there didn't fix my issue

**Local: (works, no issues)**
Python 3.7.7
rq: 1.5.0

**Production: (issues)**
Python 3.8.2
rq: 1.5.0

Steps to reproduce (code snippets below)
1. python3 category.py _successfully puts object in the queue - have verified this_
2. rq worker categories --url redis://pathtoredis - fails with the below error

Code for category.py: (this works successfully)
```python
import os
from redis import Redis
from rq import Queue
from datetime import datetime
from handler.category import handle_category_listing
from dotenv import load_dotenv

load_dotenv()

begin_time = datetime.now()
q = Queue("categories", connection=Redis(os.getenv('QUEUE_HOST')))

q.enqueue(handle_category_listing, os.getenv('CATEGORY_START_URL'))
```
When I run the worker `rq worker categories --url redis://pathtoredis` it fails with the following error:, this error does NOT occur locally, just in on the production server

```
12:32:19 Worker rq:worker:fbd5f9ebb7954479b771b97311026e49: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rq/utils.py", line 169, in utcparse
    return datetime.datetime.strptime(string, _TIMESTAMP_FORMAT)
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rq/worker.py", line 508, in work
    result = self.dequeue_job_and_maintain_ttl(timeout)
  File "/usr/lib/python3/dist-packages/rq/worker.py", line 574, in dequeue_job_and_maintain_ttl
    result = self.queue_class.dequeue_any(self.queues, timeout,
  File "/usr/lib/python3/dist-packages/rq/queue.py", line 539, in dequeue_any
    job = job_class.fetch(job_id, connection=connection)
  File "/usr/lib/python3/dist-packages/rq/job.py", line 303, in fetch
    job.refresh()
  File "/usr/lib/python3/dist-packages/rq/job.py", line 515, in refresh
    self.restore(data)
  File "/usr/lib/python3/dist-packages/rq/job.py", line 478, in restore
    self.started_at = str_to_date(obj.get('started_at'))
  File "/usr/lib/python3/dist-packages/rq/utils.py", line 256, in str_to_date
    return utcparse(as_text(date_str))
  File "/usr/lib/python3/dist-packages/rq/utils.py", line 172, in utcparse
    return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%SZ')
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

**Comment by selwin** [comment]
I think we'll simply need to check for empty string and skip parsing that data.

**Comment by systemseven** [comment]
I think that's probably a good idea - but as an update, turns out the production server actually had the package `python-rq` v. 1.2.2 installed - that's what `rq` was bound to. Upon removing that package, and calling your package directly - everything worked just fine, no date errors. Perhaps that `python-rq` package is out of sync with yours?

**Comment by selwin** [comment]
Ok, I'm closing this issue then.

**Comment by peetysmith** [comment]
> I think that's probably a good idea - but as an update, turns out the production server actually had the package `python-rq` v. 1.2.2 installed - that's what `rq` was bound to. Upon removing that package, and calling your package directly - everything worked just fine, no date errors. Perhaps that `python-rq` package is out of sync with yours?

Having the exact same problem, how did you remove python-rq and unbind rq? 
Whenever I try apt-get remove python-rq I get an error E: Unable to locate package python-rq

**Comment by p0nt** [comment]
> > I think that's probably a good idea - but as an update, turns out the production server actually had the package `python-rq` v. 1.2.2 installed - that's what `rq` was bound to. Upon removing that package, and calling your package directly - everything worked just fine, no date errors. Perhaps that `python-rq` package is out of sync with yours?
> 
> Having the exact same problem, how did you remove python-rq and unbind rq? Whenever I try apt-get remove python-rq I get an error E: Unable to locate package python-rq

maybe a little late, but you probably need to remove python3-rq instead of python-rq... at least that was the fix on my side.

**Comment by pujanisgreat** [comment]
I am still not be able to do it.

**Comment by chnbrs** [comment]
same issue here !

**Comment by catracabh** [comment]
same issue here !
