### ISSUE TITLE
Scheduler shouldn't recreate a Redis object

### ISSUE THREAD

**Issue by info-prod** [rq/rq#1310]
Hello,

Since the changes introduced with MR #1302 , the scheduler will re-create a Redis object from scratch regardless of what it receives as connection. This is undesirable as everything else in RQ will work just fine with a custom class (provided it implements the same interface as py-redis).

My use case for a custom "Redis" object: a proxy which balances the requests between a master and two replicas (depending on whether write access is required). 

Another potential use case: for unit test it would be useful to pass FakeRedis (as suggested in the doc) or another custom "dummy" class instead of a true Redis object.

Thanks for reading and have a nice day.

**Comment by selwin** [comment]
Yes, we can use `connection.__class__` to instantiate the connection. Please open a PR for this.
