### ISSUE TITLE
Duplicate execution of scheduled tasks by workers

### ISSUE THREAD

**Issue by snaptravel-eng** [rq/rq#1314]
Hi Everyone,

I am using RQ to run a single job per row in an input csv. I am rate throttling the execution by scheduling the job for each row 2 seconds apart using queue.enqueue_at, and I have two workers (one per AWS elastic beanstalk instance). For the most part this is working well, but about once per day the workers seem to begin duplicate execution of the scheduled tasks. On RQ dashboard I observe the two workers executing the same job (same row content, same job id). I also see evidence of duplicate execution in my server logs (multiple calls to the same url, which should be unique per row). This issue is resolved by rebooting the instances.

Does RQ guarantee single execution or only at least 1 execution of a job? Is this duplicate execution avoidable?

My setup is a docker container running on AWS elastic beanstalk. Within the container there is:

A flask server with 6 instances: `gunicorn -w 6 -b 0.0.0.0:$APP_PORT app:app -k gevent -t 60 --preload`

The RQ: `python3 worker.py`

where worker.py looks like:

```
from gevent import monkey
monkey.patch_all()

from rq import Connection, Queue, Worker

import app
import models

listen = ['bulk_jobs']

conn = models.bulk_jobs_cache_redis

if __name__ == '__main__':
  with Connection(conn):
    worker = Worker(list(map(Queue, listen)))
    worker.work(with_scheduler=True)
```

My queue is defined as:

`BULK_JOBS_QUEUE = Queue('bulk_jobs', connection=models.bulk_jobs_cache_redis)`

And a sample enqueue looks like:

`BULK_JOBS_QUEUE.enqueue_at(next_enqueue_time, process_row_func, row_data)`

I am using rq version 1.4.3 and redis version 3.5.3.

I would appreciate any help!

Thanks in advance :)

Ryan

**Comment by selwin** [comment]
Yes, for this scenario you should use `depends_on` to make sure that the next job is run right after the previous job finishes. It looks something like this:
```python
for row in rows:
    job = queue.enqueue(process_row, row, depends_on=job)
```
