### ISSUE TITLE
Support running tests with fakeredis (or provide socket override)

### ISSUE THREAD

**Issue by thesamesam** [rq/rq#1315]
Hi!

It'd be a huge help in e.g. Gentoo where we run tests within a network sandbox to be able to run rq's tests either with fakeredis, or at least have an environment variable to give e.g. an unix socket to communicate with a running Redis instance.

EDIT: Seeing https://github.com/rq/rq/pull/1403 helps with realising how to do this, actually.

**Comment by selwin** [comment]
The ideal scenario would be for `fakeredis` to support all commands for the library it's mocking (i.e Redis), as it's their responsibility to properly mimic the library they're mocking. Having said that, I'm not in the loop of fakeredis' development so I'm not aware if support for Redis' `info` command is coming.

I'm open to making RQ easier to test. Any idea on how you want to implement this?

If you simply want to use a unix socket, I think you should be able something like this:
```python
redis = Redis.from_url("unix://[[username]:[password]]@/path/to/socket.sock?db=0")
queue = Queue(connection=redis)
```

**Comment by lowercase00** [comment]
Even though the `info` restriction was resolved, `rq` now uses `stream`, which has not been implemented in `fakeredis`, so for now, this is not possible. Closing this.
