### ISSUE TITLE
rqworker 1.5.0 jobs exist, but not queued.

### ISSUE THREAD

**Issue by fcollman** [rq/rq#1316]
We are running  redis==3.5.3, and rq==1.5.0.  using a redis server v6.0.5.

Our rqworker system seems to be unreliable in the sense that jobs are created, but not enqueued.  When i scan through redis i see a lot of rq:job: keys, and i can use rqworker to fetch those jobs, and the job.is_queued = True, but when i look in the queue there are no jobs.  

The queue.enqueue() call seems to have returned a job, but that job is not actually in the queue.  Could someone point to me in the direction of what is wrong and how it might be fixed?  Is this a version incompatibility or a bug in rqworker?

For example.. this code..
```cursor, keys =redis.scan(cursor=0, count=10, _type='HASH')
for key in keys:
    
    data = redis.hget(key, 'description')
    ended = redis.hget(key, 'ended_at')
    print(key, data, ended)```
```
prints

```
b'rq:job:b3ef65fe-c871-4f4d-a572-0e2fa80892e2' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [183582175134749411, 183863650111460049])" b''
b'rq:job:84201e33-2bd6-4e72-99ef-45fe6cd774d2' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [175159924655919409])" b''
b'rq:job:9c45c1ba-0687-4084-88a4-7f63822880d4' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v26', [161032308340565104])" b''
b'rq:job:5da87a4e-9340-4b32-8516-deed2f63f78a' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [179920784234385902])" b''
b'rq:job:7d1f0c67-dbd1-4581-8d22-80d503a2ea3a' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [163849257130927347, 163849257130927348])" b''
b'rq:job:2b857032-b56b-4f42-8946-cbed17ea0978' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [186096762522438829])" b''
b'rq:job:2ae16bb2-b529-416e-8809-f17522bcc1a7' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [186645427414637214])" b''
b'rq:job:12a33221-0d83-4e2b-97a2-36053e2698cd' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [185531613545767409])" b''
b'rq:job:409425ce-a10e-4fc3-b80c-e869df020df4' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v31', [163850352347587270, 163850352347587271, 163850352347587272, 16385035234758...)" b''
b'rq:job:f467c31a-0982-49c3-bf48-0053b3aa9a98' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v26', [161033407852194015])" b''
b'rq:job:bd171224-4505-47f7-919b-f0414b517d0b' b"pychunkedgraph.app.meshing.tasks.remeshing('fly_v26', [162716755859347869, 162998230836064501])" b''

```
None of these jobs ever ran.   

if i get the job with say

```
job=queue.fetch_job('b3ef65fe-c871-4f4d-a572-0e2fa80892e2')
print(job.get_status())
```
It prints "queued", but 
```
queue.get_jobs()
```
returns an empty list.

Many jobs are created successfully and queued, but some percentage are not.  So something unreliable is happening.

**Comment by fcollman** [comment]
@theambient is it possible that the problem solved in  #1303 is what is underlying this issue?

**Comment by theambient** [comment]
@fcollman yes, seems it covers this case as well

**Comment by selwin** [comment]
I'm going to assume it's fixed in https://github.com/rq/rq/pull/1303 . If not, please reopen with a test case on how to reproduce this bug.
