### ISSUE TITLE
Directory tests/config_files is included in published package

### ISSUE THREAD

**Issue by bbc2** [rq/rq#1331]
Installing rq adds a `tests` module to the global namespace, conflicting with other `tests` modules.  This is also explained in #192, which originally fixed a similar issue.  I don't really understand why that fix doesn't work anymore.

```bash
$ unzip -l rq-1.5.1-py2.py3-none-any.whl
Archive:  rq-1.5.1-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
[...]
        0  2019-11-23 13:34   tests/config_files/__init__.py
      170  2019-11-23 13:34   tests/config_files/dummy.py
      224  2019-11-23 13:34   tests/config_files/dummy_override.py
      211  2019-11-23 13:34   tests/config_files/sentry.py
[...]
---------                     -------
   207537                     38 files
```

**Comment by selwin** [comment]
I’m not sure how this can happen. If someone knows how to fix this, please open a PR.

**Comment by selwin** [comment]
So apparently wheel builds behave differently than tarball distributions and this issue only happens with wheels. Fixed in https://github.com/rq/rq/commit/a31d37f1ea32c001da6d7c6c57a3a3e16290450c
