### ISSUE TITLE
Status of Internal Scheduler

### ISSUE THREAD

**Issue by BobReid** [rq/rq#1332]
What is the status of the internal scheduler? 

According to the docs it is not recommended for production use and people should continue to is the external rq-scheduler package. Is this still the recommendation? 

I like the idea of having the scheduler internal and it providers the async retry functionality that is not available when using the external scheduler. 

If the internal scheduler is still not the recommended deployment strategy is there a roadmap for the scheduler feature or an issue list to stabilize it? I might be able to contribute towards the effort.

**Comment by selwin** [comment]
I’m quite happy with the status of RQ’s internal scheduler implementation. I’m just putting out the docs there to make sure that enough people try it before I remove the warning label :)

**Comment by BobReid** [comment]
Good to know, thanks.

**Comment by tboulogne** [comment]
hello @selwin,

What about cron with the in-house scheduler ?

Thanks for all !

Thierry
