### ISSUE TITLE
Queue list shows job in failed but failed job list shows none.

### ISSUE THREAD

**Issue by jtrip** [rq/rq#1333]
My dashboard is showing a job in failed but it shows no jobs in the failed job list.

![Screen Shot 2020-09-04 at 7 42 57 AM](https://user-images.githubusercontent.com/125447/92239371-e1d4bd00-ee88-11ea-8522-d410783f3656.png)

I investigated using redis and the python console to connect, and both showed me that there is a reference to a job id in the failed queue, however that job does not seem to exist in redis anymore. So while I first thought this was a dashboard issue it looks like the dashboard is doing the best it can given the information that rq is supplying.  

I recently implemented the new Retry class as enqueue parameter and my suspicion is that the job failed, was retried and succeeded and the reference to the job in the failed registry was not removed, although I have no other evidence for this.   

I've been using this system for well over a year and this is the only change I've made in a while so it seems quite likely to be related at least.

**Comment by jtrip** [comment]
Here is a screenshot showing the state of data I believe causing this. We can see job references in a failed job queue however those keys do not exist.

![Screen Shot 2020-09-08 at 8 23 23 AM](https://user-images.githubusercontent.com/125447/92476713-65561d00-f1ad-11ea-9af6-596a97a38a4f.png)

**Comment by selwin** [comment]
I’ll take a look whether using retries can cause this to happen.

**Comment by selwin** [comment]
I have a PR for this here. https://github.com/rq/rq/issues/1333
