### ISSUE TITLE
add a job using plain redis commands

### ISSUE THREAD

**Issue by CarlosUvaSilva** [rq/rq#1337]
how can I add a job to a RQ queue without using rq? I want to use simple redis commands

My goal is to add jobs to the queu from a Rails app and the jobs are processed in Python.

something like this but for RQ instead of Sidekiq: https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-push-a-job-to-sidekiq-without-ruby

**EDIT:**

I managed to add the job to the queue using simple redis commands using a copy of a python job from `redis-cli`
Just need help with the data pickle, what exactly I'm I supposed to pickle?
As per the documentation the hash contains:
data        => <pickled representation of the function call>
description => "count_words_at_url('http://nvie.com')"

is the data the pickle of the description? or is it something else?

Thank you very much

**Comment by selwin** [comment]
Take a look at https://github.com/rq/rq/blob/master/rq/queue.py#L313
