### ISSUE TITLE
Scheduler does not support retry?

### ISSUE THREAD

**Issue by vaal-** [rq/rq#1338]
Is there any reason for this?
https://github.com/rq/rq/blob/master/rq/queue.py#L429-L430
Here the parameter retry is not passed further.

I did a couple of tests on code where I added a parameter passing. Everything worked out fine. But maybe there are some pitfalls?

**Comment by nerok** [comment]
I would assume that the issue is that no one has noticed when adding the retry functionality, same was the issue with the job-decorator (see #1319 for that fix). I would assume you could make a pull request if that is a feature you need.

**Comment by selwin** [comment]
Yeah, PR for this is welcome.

**Comment by johnraz** [comment]
@selwin I believe this can be closed :-)

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1343
