### ISSUE TITLE
RQScheduler production running bug

### ISSUE THREAD

**Issue by nikkonrom** [rq/rq#1354]
We run RQ in production and have a bunch of scheduled jobs (~10M) in one queue. Also we have ~250 workers that works on this queue. We have starting all these workers with `--with-scheduler` parameter, and have relied on RQ documentation, that says that in one moment only one worker can run with scheduler.
But after working in this mode several days, we noticed, that amount of jobs in our queue continuously grows. And count of jobs in ScheduledJobRegistry didn't reduce. We started to investigate source code of RQ and tried to identify reason of the problem.
And we found this code:
https://github.com/rq/rq/blob/55dce19a95dc043bae1691ac3bda13c33550a0ec/rq/scheduler.py#L89
So in this line, one instance of RQScheduler acquire locks in Redis. It sets key with pid (also insecure if you running multiple workers with schedulers on different servers and pids can coincide) and most important that it sets expire time to 5 seconds.
After acquiring locks, scheduler calls `enqueue_scheduled_jobs` function and it is blocking call (important).
After that call, scheduler calls `heartbeat` function that renew lock that scheduler acquires.

And cause we have many scheduled jobs, it's enqueuing can take more than 5 seconds, and lock key expired from Redis. One of the other workers with scheduler now can acquire lock and also start to `enqueue_scheduled_jobs`, so jobs duplicates and if this worker dies, it also don't removed from ScheduledJobRegistry and process repeats again and again.

**Comment by nikkonrom** [comment]
Also I would like to mention, that proposed pull request was tested on our system and scheduler stucks and disappeared locks was resolved.

**Comment by selwin** [comment]
I'm also increasing the expiry of the lock to 60 seconds to account for network/server load issues which may happen in shared/cloud environments.
