### ISSUE TITLE
Getting duplicated log messages in docker

### ISSUE THREAD

**Issue by waldner** [rq/rq#1356]
I'm running a worker in docker (```rq worker --url=redis://redis:6379 --with-scheduler --name=worker1```). Now I have a task that looks like this:

```
# tasks.py
import logging
def f():
    logging.log(logging.INFO, "THIS IS F LOGGING")
    return True
```
I run the task with the following code inside the container:

```
from rq import Queue
from redis import Redis
import tasks

q = Queue(connection = Redis('redis:6379'))
job = q.enqueue(tasks.f, args = [], kwargs = {})
```
When I run, I see this in the worker's log:

```
worker1         | 13:04:34 default: tasks.f() (1e2be2af-db11-4bb5-983a-4868019e5798)
worker1         | INFO:rq.worker:default: Job OK (1e2be2af-db11-4bb5-983a-4868019e5798)
worker1         | INFO:rq.worker:Result is kept for 500 seconds
worker1         | 13:04:35 default: Job OK (1e2be2af-db11-4bb5-983a-4868019e5798)
worker1         | 13:04:35 Result is kept for 500 seconds
```

So, not only I do not see the task log message (despite the worker apparently logging other INFO level messages), but all other messages are duplicated (with the ```INFO:``` prefix). If I remove the ```logging.log(logging.INFO, "THIS IS F LOGGING")``` from the task function then the worker log messages are no longer duplicated, but of course I'd like to have my task log without interfering with RQ's own messages.

I'm surely missing something about how RQ does logging and perhaps Python logging in general. Can somebody help?
Thanks

**Comment by lockie** [comment]
NVM, I was able to fix it by showing call to `logging.basicConfig` in front of my task function.
