### ISSUE TITLE
Propagate logging level from worker to scheduler

### ISSUE THREAD

**Issue by christopher-dG** [rq/rq#1365]
I'm running `rq worker --with-scheduler --quiet`, and it properly quiets the worker logs, but the scheduler remains set to `INFO`, where it prints out `Trying to acquire locks for default` every ~15 minutes. Could we make the `-q/--quiet` propagate to the scheduler? Currently it looks like the scheduler logger is not configurable except by accessing the logger directly.
If I find some time, I'll try to make a PR for this.

**Comment by selwin** [comment]
Yes, please open a PR for this.
