### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by OfekShochat** [rq/rq#1377]
when I use mp.Pool it outputs that error. ive looked into the errors like it in the github issues but there is no other issue that helped me nor has Rlock and not just "lock". 
this is the code (im making a chess engine that the net is in python):
```def update(L, net):
    from numpy import array, mean
    this_board = []
    row = []
    index = 0
    for piece in str(L.board):
        if piece != " " and piece != "\n":
            index += 1
            row.append([get_piece_val(piece)])
    
        if index == 8:
            index = 0
            this_board.append(row)
            row = []
    b = array([this_board])
    if L.board.turn:
        p = mean(net.predict(b))
        L.update_value(p)
        #cache.update({L.board.fen():p})
is this because the net.predict is parallelised?
    else:
        p = mean(1-net.predict(b))
        L.update_value(p)
        #cache.update({L.board.fen():p})
```
is this because `net.predict` is parallelized?

im using python3.8.6 and it says it doesnt have a version with mp.__version__

**Comment by lucawen** [comment]
what is your solution?

**Comment by OfekShochat** [comment]
To not do it in python (I make a chess engine). You can see it on the repository https://github.com/OfekShochat/0xA2_chessengine
