### ISSUE TITLE
Is sentry_sdk a dependency?

### ISSUE THREAD

**Issue by suliuzh** [rq/rq#1379]
As we see, sentry_sdk is used in the files- _rq/contrib/sentry.py_ and _tests/test_sentry.py_. So should sentry_sdk be regarded as a dependency for the project? test dependency or else?
![image](https://user-images.githubusercontent.com/27858725/99363265-7d55c580-28ef-11eb-87f8-0b9bb406843b.png)

**Comment by selwin** [comment]
Sentry SDK is only intended to be a test dependency.
