### ISSUE TITLE
InvalidJobOperation: Job is not currently executing when attempting to stop deferred jobs

### ISSUE THREAD

**Issue by JLHasson** [rq/rq#1388]
I have a job that I am exclusively launching as a dependency of another job. I.e. I will launch job1, and then later call `queue.enqueue(job2, ..., depends_on=job1)`. The issue I'm currently hitting is that I have launched job1 without any timeout, and it has somewhat silently failed meaning it is not exiting and is instead just running forever in the queue. At this point, I now have a job2 that is in `deferred` state waiting for job1 to complete (which it never will). I ran `send_stop_job_command()` on job1 to kill it, which worked and it is no longer in the queue. However, job2 is still in `deferred` state and is not getting queued. I cannot kill this job by running `send_stop_job_command()`, I get:
```
send_stop_job_command(..., job.id)
---------------------------------------------------------------------------
InvalidJobOperation                       Traceback (most recent call last)
...

/opt/conda/envs/kg/lib/python3.6/site-packages/rq/command.py in send_stop_job_command(connection, job_id)
     37     job = Job.fetch(job_id, connection=connection)
     38     if not job.worker_name:
---> 39         raise InvalidJobOperation('Job is not currently executing')
     40     send_command(connection, job.worker_name, 'stop-job', job_id=job_id)
     41

InvalidJobOperation: Job is not currently executing
```

Is there some sort of workaround for killing jobs that are in `deferred` state?

**Comment by selwin** [comment]
If job is in the deferred state, you can call `job.cancel()`.

**Comment by JLHasson** [comment]
Thanks @selwin! Will use that in the future 👌
