### ISSUE TITLE
stop_stop_job_command() results in misleading error message and task state

### ISSUE THREAD

**Issue by dralley** [rq/rq#1389]
After sending a stop job command, the following warning is logged:

>WARNING: Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)

The first thing about this is that since the job was deliberately stopped, it's inappropriate to say that the job failed due to the work-horse terminating unexpectedly.

The second thing is that a cancelled job is considered to be "failed", and triggers the ```handle_job_failure()``` method, but there is no special [job status code](https://github.com/rq/rq/blob/016da14723d21f6801b19cbff97f2fb9bee5c5db/rq/job.py#L29-L37) that allows distinguishing between failed/crashed jobs and jobs that were deliberately stopped.  This is something that a dev (or perhaps RQ itself, see comment below) might want to know, so that they can treat these jobs differently.  It would be good to add a new job status code named "canceled" or "stopped" for this purpose.

We have a concrete use case for needing this because we record job statuses in our own database, and we do have a separate state for cancelled jobs vs. jobs that failed "normally".

```
Dec 10 19:29:29 pulp2-nightly-pulp3-source-centos7.localhost.example.com gunicorn[9720]: pulp [c80542dbc4934f75aa83420c8b23df3e]: pulpcore.tasking.util:INFO: Canceling task: 351d9bb0-fcaa-4953-a96a-6a713ad32919
Dec 10 19:29:29 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[9717]: pulp [None]: rq.worker:INFO: Killed horse pid 9789
Dec 10 19:29:29 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[9717]: pulp [None]: rq.worker:WARNING: Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)
Dec 10 19:29:29 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[9717]: pulp [None]: rq.worker:INFO: 9717@pulp2-nightly-pulp3-source-centos7.localhost.example.com: 0cbb7b3b-5a38-4e2c-9dde-b579ce36fb08
Dec 10 19:29:29 pulp2-nightly-pulp3-source-centos7.localhost.example.com rq[9717]: pulp [None]: rq.worker:INFO: 9717@pulp2-nightly-pulp3-source-centos7.localhost.example.com: Job OK (0cbb7b3b-5a38-4e2c-9dde-b579ce36fb08)
```

**Comment by dralley** [comment]
Another thing, we don't use retries so I haven't tested this, but from the implementation of ```handle_job_failure()``` it looks like if the task was deliberately stopped but it was retriable, it might be re-queued.  I think that could easily be considered a bug in some cases.

**Comment by dralley** [comment]
@selwin I can contribute a fix, so long as you agree with the plan

**Comment by selwin** [comment]
@dralley I agree with you. It would be great if we have a “stopped” job status

**Comment by adammike** [comment]
I was just coming here to post the same thing. 

Another thing I would point out is that there are two different ways to stop the job. 

1. `job.cancel()` which appears to simply remove a queued job from the queue, but leaves the status as `queued`
2. `send_stop_job_command(rq.connection, job_id)` which kills the running job

I believe both options to cancel a job (running or not) should update the job status to something appropriate. Perhaps `cancelled` rather than stopped so a single status is valid in both cases?

**Comment by dralley** [comment]
@selwin Do you have any opinion on ^ before the PR is merged?

**Comment by selwin** [comment]
Sorry I missed this one.

1. `job.cancel()` should change the status to canceled and moved to a `CanceledJobRegistry`
2. This PR sets job status to `stopped` https://github.com/dralley/rq/commit/666a60ae3493a0da18b94b70b0d7be0af10e6eda

**Comment by dulestar** [comment]
This problem still exists, and the active send_stop_job_command starts to retry again?
