### ISSUE TITLE
q.job_ids and q.jobs always return empty list

### ISSUE THREAD

**Issue by BoomerB** [rq/rq#1391]
Hi,

I use rq 1.7.0
```
    with Redis(password=password) as redis_conn:
        q = Queue("queue_name", connection=redis_conn)
        q.enqueue(*cmd, **options)
        log.debug("job_ids: {}".format(q.job_ids))
        log.debug("jobs: " + json.dumps(q.jobs))
```
both logs show an empty list. I expect to find at least one job in the list.

my problem: I run background jobs which poll a 3rd system for a certain event. Once the event is encountered, some cleanup tasks are executed. But it can happen, that a second background job is started which waits for the same event but with different parameters. In this case I would like to inform the first job to execute the cleanup immediately.
So, how can I find out if another job is running which I need to notify?

kind regards
Boomer

**Comment by BoomerB** [comment]
I learned something new.
q.job_ids returns something, when the job still waits to be picked up by a worker.

**Comment by selwin** [comment]
> my problem: I run background jobs which poll a 3rd system for a certain event. Once the event is encountered, some cleanup tasks are executed. But it can happen, that a second background job is started which waits for the same event but with different parameters. In this case I would like to inform the first job to execute the cleanup immediately.
So, how can I find out if another job is running which I need to notify?

You can use `queue.enqueue(cleanup_func, depends_on=first_job)`.
