### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by Samll-Kosmos** [rq/rq#1393]
Hi

I can't figure out how to integrate sentry. According to the [documentation](https://python-rq.org/patterns/sentry/) I should just pass --sentry-dsn as a worker option but my exceptions are not reaching sentry. I use a custom script `worker.py` to initialize the worker:

```
import sys
from redis import Redis
from rq import Connection, Worker
import <my_custom_module>
  
with Connection():
    qs = sys.argv[1:]
    w = Worker(qs, connection=Redis("localhost", "6379", 1))
    w.work()
```

To start the worker:

`python worker.py --url redis://localhost:6379/1 --sentry-dsn <my_sentry_dsn>  <q_name>`

python: 3.7.6
rq: 1.7.0
sentry_sdk: 0.19.5
OS: cenos 7

Could you please tell me what am I doing wrong? Thank you in advance

**Comment by homeworkprod** [comment]
This is what works for me (done before creating and starting the worker instance):
```py
import sentry_sdk
from sentry_sdk.integrations.rq import RqIntegration

SENTRY_DSN = 'https://some-token:another-token@sentry.example/123'
SENTRY_ENV = 'prod'

sentry_sdk.init(
    dsn=SENTRY_DSN,
    environment=SENTRY_ENV,
    integrations=[RqIntegration()],
)
```
Good luck.

**Comment by Samll-Kosmos** [comment]
Thank you for your reply, I'm gonna test it and see if I can solve my problem.

**Comment by Samll-Kosmos** [comment]
Your solution worked and I now receive a sentry notification. It took almost an hour for the notification to arrive at sentry though.

**Comment by homeworkprod** [comment]
Glad I could help!
