### ISSUE TITLE
ScheduledJobRegistry isn't meant to store queued jobs?

### ISSUE THREAD

**Issue by luggie** [rq/rq#1399]
I was wondering if there is a job registry for queued jobs or if ScheduledJobRegistry would be that and I'm just not handling it correctly.

**Comment by selwin** [comment]
Queued jobs are stored inside `Queue` objects. You can get the jobs there by calling `queue.job_ids`. `ScheduledJobRegistry` is used to store jobs that are scheduled to run in the future.
