### ISSUE TITLE
RQ in docker: does worker need access to main server volume?

### ISSUE THREAD

**Issue by ilmoi** [rq/rq#1400]
I'm deploying RQ on docker for the first time. 

In my experiments I wasn't able to deploy `rq worker` successfully without giving it access to the same volume that the main server is using. 

Is this expected behavior? Or am I doing something wrong?

I expected rq worker to be a lean container with nothing more but RQ itself installed, but so far I've failed to get there. Is that even possible?

**Comment by JorgenRe1** [comment]
(tagging along for more info) As far as i know it only needs to be running the exact same code. So i personally have a master which creates jobs which workers take. They both run the same image, but master runs as a web server whilst the workers run as rq workers.

**Comment by ilmoi** [comment]
Interesting, thanks!

**Comment by KMouratidis** [comment]
I used them in docker at one point but don't remember much of the details. From what I know, rq doesn't use the filesystem other than for logging. Did you make sure to get the setup right (Redis installed in the containers and on your server, python + rq packages, docker port forwarding, correct ips)?

**Comment by selwin** [comment]
What @KMouratidis said is correct.
