### ISSUE TITLE
how can I run a job forever

### ISSUE THREAD

**Issue by xdandyx** [rq/rq#1401]
I want to run a job forever, however, it seems that job_timeout can‘t make it possible. So, how to make it?
Can `enqueue_in` be replaced by `enqueue(job_timeout)`, if so, what is the significance of this function?
In addition, can you add functions similar to crontab? I thought enqueue_in was a function similar to crontab, but I found it was not.

**Comment by KMouratidis** [comment]
`Running a job forever` doesn't make much sense. Are you interested in a submitting jobs repeatedly (e.g. look up `schedule`) or having a process that runs forever (like a server, game, etc / event loop)?

**Comment by xdandyx** [comment]
> `Running a job forever` doesn't make much sense. Are you interested in a submitting jobs repeatedly (e.g. look up `schedule`) or having a process that runs forever (like a server, game, etc / event loop)?

What you said makes sense. However, when I perform tasks such as data collection, I may want this process to run until I manually close it. Although I set a large job_timeout parameter to achieve this goal, But it still doesn't look so natural. However, as far as this function is concerned, it doesn't matter whether it is added or not.

**Comment by selwin** [comment]
You can use `timeout=-1` for jobs that don't have timeouts.
