### ISSUE TITLE
Worker closed with "Warm shut down requested"

### ISSUE THREAD

**Issue by marzottifabio** [rq/rq#1409]
Hi, I implemented a django app that enque jobs batch with RQ library. Everything works very very well!
I only don'ìt understand why, when I close the django server, the worker closed wirh ""Warm shut down requested".
At the moment it's not a big problem because I put the restart option in systemd config file but I'd like to undestand....

This my configuration for the start command:

[Unit]
Description=Rq
After=syslog.target network.target

[Service]
WorkingDirectory=/srv/siawebhook/SiaWebHook/SiaWebHook
ExecStart=/bin/su siawebhook -c "/srv/siawebhook/.conda/envs/SiaWebHook/bin/rq worker siawebhook >> /srv/siawebhook/SiaWebHook/log/sia_rq.log 2>&1"
ExecStop=/bin/pkill -u siawebhook -f /srv/siawebhook/.conda/envs/SiaWebHook/bin/rq
PrivateTmp=true
Restart=always

[Install]
WantedBy=multi-user.target

Thanks for the help
Fabio

**Comment by selwin** [comment]
RQ giving the message `Warm shut down requested` means the worker has received the shutdown message and will wait until the current job finishes before it shuts down. So in this case this message is normal.

**Comment by marzottifabio** [comment]
Hi Selwin and thanks a lot for your answer, actually the question is why closing django app process the WORKER task receive the shutdwon mesage and then close itself. Django app and WORKER run on two different processes, sorry but I don't understand, I miss something...

**Comment by selwin** [comment]
Oh yes, those are indeed two separate processes. Shutting down your Django webserver process shouldn't affect RQ as it performs shutdown when receiving a SIGINT signal.

Perhaps there's something in your deployment process that's triggering this.

**Comment by marzottifabio** [comment]
@selwin yes I found the mistake, thanks. In the systemctl configuration file for django app I wrote this command for the stop:
ExecStart=/bin/su siawebhook -c "/srv/siawebhook/.conda/envs/SiaWebHook/bin/python /srv/siawebhook/SiaWebHook/SiaWebHook/manage.py runserver xxx.xxx.xxx.xxx:1111

Also the worker run under the same pyhton path..... thanks, fabio
