### ISSUE TITLE
priority useless

### ISSUE THREAD

**Issue by taomujian** [rq/rq#1420]
My worker code is:
def worker(listen):
    with Connection(redis_conn):
        worker = Worker(map(Queue, listen))
        worker.work()

def run ():
    listen = ['high', 'medium', 'low']
    try:
        cpu_num = 5
        p = Pool(cpu_num)
        for i in range(cpu_num):
            p.apply_async(worker, args=(listen,))  # 开启worker
        p.close()
        p.join()
    except Exception as e:
        print(e)

My queue code is:
high_queue = Queue("high", connection = redis_conn)
low_queue = Queue("low", connection = redis_conn)

high_queue.enqueue_call(queue_scan, args = (1,), timeout = 7200)
low_queue.enqueue_call(queue_scan, args = (1,), timeout = 7200)

high_queue will take many time,  I run low_queue job when high_queue job is running, why low_queue job isn't block until high_queue is empty

**Comment by selwin** [comment]
If you want low queue to be processed, you can run a worker for high queue and one for low queue.

**Comment by taomujian** [comment]
I not want low queue to be processed, I want low queue to be block when high queue isn't empty

**Comment by selwin** [comment]
If you do `rq worker high low`, it will always dequeue from `high` queue first. `low` will only be processed when `high` is empty.
