### ISSUE TITLE
Please create a 1.8.0 release

### ISSUE THREAD

**Issue by zachgoulet** [rq/rq#1421]
It appears that [documentation](https://python-rq.org/docs/workers/#worker-arguments) references features available in version 1.8.0:

> *New in version 1.8.0.*
> - `--serializer`: Path to serializer object (e.g “rq.serializers.DefaultSerializer” or “rq.serializers.JSONSerializer”)

Though it appears as though version 1.7.0 is the newest available at [pypi.org](https://pypi.org/project/rq/#history). Could a version 1.8.0 be created from the current master branch?

**Comment by vijtad** [comment]
First time, I ran multi-dependencies job containing a list of 100 jobs chained with 21 instances, it ran successfully.
When I ran the same job, second time, I get following error, 

> Traceback (most recent call last):
>   File "/usr/srv/src/rq/rq/worker.py", line 1009, in perform_job
>     self.handle_job_success(job=job,
>   File "/usr/srv/src/rq/rq/worker.py", line 961, in handle_job_success
>     queue.enqueue_dependents(job, pipeline=pipeline)
>   File "/usr/srv/src/rq/rq/queue.py", line 510, in enqueue_dependents
>     jobs_to_enqueue = [
>   File "/usr/srv/src/rq/rq/queue.py", line 516, in <listcomp>
>     ) if dependent_job.dependencies_are_met(
> AttributeError: 'NoneType' object has no attribute 'dependencies_are_met'

**Comment by homeworkprod** [comment]
I'd also welcome a new release – to provide my users with #1403 in production without custom patches.

**Comment by tshead** [comment]
+1 for a 1.8.0 release, I’m anxiously awaiting the JSON serializer so I can use RQ across Python versions.

**Comment by selwin** [comment]
Version 1.8.0 is now on PyPI. Sorry for the wait.

**Comment by homeworkprod** [comment]
Thanks!

**Comment by tshead** [comment]
Thank you!

**Comment by homeworkprod** [comment]
@selwin I noted that my fix doesn't appear in the changelog. But then again, maybe I'm the only one caring about it anyway ;)
