### ISSUE TITLE
Pickle version incompatibility are not logged

### ISSUE THREAD

**Issue by clavigne** [rq/rq#1422]
Hi, 

I had a problem with jobs failing silently while running in Docker. I eventually realized that I was running workers in python 3.7, but was enqueuing calls from python 3.9 (an easy enough mistake to make when orchestrating different containers). 

What happens in this case is that the job gets enqueued, the worker starts execution but then the job fails. With `--logging_level DEBUG`, this is the result:

```
09:20:42 default: test_module.add2(1, 2) (586b3d13-cba9-436a-8b6f-45fc2c3bb8f0)
09:20:42 Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
09:20:42 Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.
09:20:42 Handling failed execution of job 586b3d13-cba9-436a-8b6f-45fc2c3bb8f0
09:20:42 Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
09:20:42 Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
09:20:42 *** Listening on default...
```

note that there is no indication here that the job has failed. However, `job.exc_info` does show the traceback,
```
Traceback (most recent call last):
  File "/home/clavigne/miniconda3/envs/funsies3.7/lib/python3.7/site-packages/rq/worker.py", line 970, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
  File "/home/clavigne/miniconda3/envs/funsies3.7/lib/python3.7/site-packages/rq/worker.py", line 867, in prepare_job_execution
    self.procline(msg.format(job.func_name, job.origin, time.time()))
  File "/home/clavigne/miniconda3/envs/funsies3.7/lib/python3.7/site-packages/rq/job.py", line 247, in func_name
    self._deserialize_data()
  File "/home/clavigne/miniconda3/envs/funsies3.7/lib/python3.7/site-packages/rq/job.py", line 215, in _deserialize_data
    self._func_name, self._instance, self._args, self._kwargs = self.serializer.loads(self.data)
ValueError: unsupported pickle protocol: 5
```
but this is never logged by `rq worker` itself.

I haven't had the chance to try yet, but I guess this may be fixed by #1303 ? I am also wondering if this could be the cause of errors reported in some of the comment in #758 .

**Comment by selwin** [comment]
This line indicates that the job's execution has failed:
`09:20:42 Handling failed execution of job 586b3d13-cba9-436a-8b6f-45fc2c3bb8f0`

**Comment by clavigne** [comment]
Sorry I realize now that I wasn't super clear. 

The "bug" (more like UI issue really) is not the failure but the fact that it is (AFAIK) only logged [at DEBUG](https://github.com/rq/rq/blob/fc7940c77b69704ad6c059385fd530c850e5f0be/rq/worker.py#L897) without information as to why it failed, so it's rather easy to miss. 

I don't know if that's the desired behaviour but it is rather quiet compared to the way [exceptions are logged](https://github.com/rq/rq/blob/fc7940c77b69704ad6c059385fd530c850e5f0be/rq/worker.py#L1043). 

To be consistent, I think the failure should be logged at the ERROR level with the Pickle Error exception text. 

I can PR it if you want.

**Comment by selwin** [comment]
Ah I see. Yes that makes sense. Feel free to open a PR for this. Thanks for the clarification!
