### ISSUE TITLE
Is there a way to have queue with randomly shuffled jobs ?

### ISSUE THREAD

**Issue by vitalik** [rq/rq#1423]
Currently you can insert job either to the start or to the end of the queue

Is there a workaround to insert job into random position ?
(or in a worker fetch job from random position)

**Comment by thomasmatecki** [comment]
You could probably implement a [`Queue`](https://python-rq.org/docs/workers/#worker-arguments) class that does this. The normal queue is implementing using Redis' `RPUSH` and `LPOP` commands. There is no Redis command to _either insert or remove a random item from the list at key X_. Perhaps one could cook up a queue backed by a Redis set and use [`SRANDMEMBER`](https://redis.io/commands/srandmember).

**Comment by marians** [comment]
I think this issue was closed because someone thought that https://github.com/rq/rq/pull/1425 solved it. I just looked at the PR and my understanding is that the change affected the order in which a worker would select the queue to pick from. It doesn't affect the order of jobs within a queue.
