### ISSUE TITLE
register_dependency - Invalid input of type: 'list'. Convert to a bytes, string, int or float first.

### ISSUE THREAD

**Issue by vijtad** [rq/rq#1429]
I am getting this error when calling register_dependency.
**Invalid input of type: 'list'. Convert to a bytes, string, int or float first.**

I created depends_on with multi-dependent jobs and following is the code snippet
```

    mergeQueue = Queue(connection=redisClient)
    job = Job.create(func=execDependentJob,args=(outputPath, destinationfilename),timeout=7200, depends_on=joblist)
    job.save()
    job.register_dependency()
    job._execute()
```

I am running Redis version=6.2.1
Can any one let me know how to fix this error.
I want to un list of jobs that need to be completed before running final job.

**Comment by jammie19** [comment]
What version of `rq` are you using? This happens to me on the latest release `1.7.0` but not on `master`. Master is the only version that has multiple dependencies implemented and `1.7.0` only accepts a single Job in the `depends_on` parameter.
See here for master installation instructions: https://python-rq.org/#installation

Also, you should pass your connection into `Job.create()`. I got an error trying to run this code as-is

**Comment by vijtad** [comment]
@jammie19  Thanks for your help.
I was using release 1.7.0
master branch worked for me.
When is this planned to release ?

**Comment by selwin** [comment]
Version 1.8.0 is up on PyPI. Closing this issue.
