### ISSUE TITLE
How do I start/stop worker based on a condition?

### ISSUE THREAD

**Issue by minecraft2048** [rq/rq#1430]
Lets say I want my worker to execute jobs only when a network connection is up, and stops executing jobs when that network connection is down, and retry when it is back up. How do I do that? The documentation says that there is a way to make custom worker class: https://python-rq.org/docs/workers/#custom-worker-classes but it doesn't show what methods and things I need to implement so that my custom worker class is compatible with rq

**Comment by minecraft2048** [comment]
I found some comments that asks similar things: https://github.com/rq/rq/issues/717#issuecomment-457991189 and https://github.com/rq/rq/issues/717#issuecomment-769012307

**Comment by selwin** [comment]
[This reently merged PR](https://github.com/rq/rq/pull/1387) changes RQ's behavior to automatically retry when Redis is unreachable. This may solve your issue.
