### ISSUE TITLE
MySQL query failing to fetch data for more than 8 columns

### ISSUE THREAD

**Issue by Bipulkumarsingh** [rq/rq#1432]
I am not sure why this is happening, I have a job that queries the database and performs other operations on it.
```
from rq import Queue
queue = Queue(connection=conn)

def sample_function(info):
    query = "select * from table"  # work fine if no. of columns is less than or equal to 8 with rq
    data = cursor.execute(query).fetchall()
    "futher process data" 
   
queue.enqueue(sample_function, info) 
```
#### Error message: 
`object of type 'int' has no len() (field 9th_column_name)`  # got this error for 9th column if 9th column is present in above select query.

**Comment by thomasmatecki** [comment]
@Bipulkumarsingh This looks more like a problem with your processing of the data returned from the query than an issue with RQ.

What line is the exception occurring at?

**Comment by selwin** [comment]
This looks like an application code error rather than an RQ error. Closing this issue.
