### ISSUE TITLE
depends_on issue

### ISSUE THREAD

**Issue by KessoumML** [rq/rq#1436]
Hello,
I have a use case where I need to defer jobs until another queue is empty (no waiting/executing/deferred jobs there).
I'm using depends_on many jobs right now, but I don't know if `depends_on` is the only way to defer jobs that needs to wait for others jobs to finish.
According the current implementation of `depends_on`, if a job is failed the deferred job will wait for ever.
I would like to know if there is any alternative to resolve this use case? any suggestions will help.
Thank you 
Edit: 
If some of job dependencies failed, the deferred will wait for ever, is there any way to start deferred job when all dependencies complete their execution (status doesn't matter)?

**Comment by selwin** [comment]
I plan on introducing an `on_success` and `on_failure` callbacks which may help with this (although the specifics may depend on your exact use case).

**Comment by KessoumML** [comment]
I see, it looks more flexible than coupling `depends_on` result to success status, I wonder if I could take a look and solve this, could you accept PR?

**Comment by selwin** [comment]
I’d be happy to accept a PR implementing this. To keep the scope small, we can start with on_success callback. Once that goes in, we can make another similar PR for on_failure.

**Comment by achalagarwal** [comment]
> I plan on introducing an `on_success` and `on_failure` callbacks which may help with this

That would be awesome!

@KessoumML Is it still under your radar? 😄

**Comment by selwin** [comment]
on_success and on_failure callbacks are already implemented in https://github.com/rq/rq/pull/1480
