### ISSUE TITLE
does rq support log-format by config_file?

### ISSUE THREAD

**Issue by chen19901225** [rq/rq#1437]
because such string  '--log-format="[$(asctime):%(levelname)s--%(name)s] %(message)s" ' will cause supervisor config error

**Comment by selwin** [comment]
You can pass in `--config myconfigfile` to RQ, but I'm not sure whether logging configurations are imported from that file. This is something I want to have though, so a PR for this would be great.

**Comment by thaodt** [comment]
hi @chen19901225 and @selwin maybe you guys understood rq thoroughly. Could you please help me how to put the rq logs from console into a file? 

my code looks like this:
```
import logging
from rq import Worker, Queue, Connection

from helpers.redis_helper import redis_helper
from settings import RQ_QUEUES_TO_LISTEN

_logger = logging.getLogger(__name__)   # i tried change __name__ into rq.worker but nothing happened

def start_worker():
    try:
        listen = RQ_QUEUES_TO_LISTEN
        redis_conn = redis_helper.get_connection('default')
        with Connection(redis_conn):
            worker = Worker(list(map(Queue, listen)))
                            # , exception_handlers=[retry_handler])
            worker.work()
    except Exception as e:
        _logger.error(e)
        exit(1)
```

**Comment by chen19901225** [comment]
@thaodt  it seem that rq does not provider log to file option, if you want to log to file 

1. use supervisord to redirect stdout to file (i choose this)
2. use shell redirect `python work.py >> out.log 2 >&1`

**Comment by lowercase00** [comment]
@selwin I think this can be closed. mostly related to logging config, as `rq` is using the default Python logger, this should be no different than any other logging configuration, including the `FileHandler`

**Comment by selwin** [comment]
@lowercase00 thanks for helping triage past issues!
