### ISSUE TITLE
Suspend only one worker not all of them

### ISSUE THREAD

**Issue by radheygupta** [rq/rq#1442]
I have a scenario, where I have three queues and three workers(one worker for each queue).
I want to Suspend one worker in night and resume it in morning as some dependencies are only available in business hours for this worker.

As per my understanding `rq suspend` will suspend all the three workers. Any easy and reliable way to suspend and resume only desired worker?

As a work-around, currently I kill the worker in night and re-initiate it in morning.

**Comment by selwin** [comment]
We don't have that kind of feature at the moment. I'm closing this issue, but I'd gladly accept suggestions or ideas if there's any concrete implementation plan.
