### ISSUE TITLE
Importing rq is three times longer than importing celery 

### ISSUE THREAD

**Issue by guettli** [rq/rq#1444]
I am unsure if I should use "celery" or "rq".

I am looking for a light-weight solution and my gut feeling told me that importing celery will be much slower than importing rq.

But the opposite is true. At least on my device:

```
> time python -c 'import rq'

real 0m0,115s
user 0m0,101s
sys	 0m0,014s
```

```
> time python -c 'import celery'

real 0m0,035s
user 0m0,034s
sys  0m0,001s
```

I measured this several times - same result.

My prejudice was wrong. Why is importing rq three times slower?

 

https://stackoverflow.com/questions/67010327/why-is-importing-rq-much-slower-than-importing-celery

**Comment by selwin** [comment]
I'm actually not sure about this, it hasn't been a problem in actual real world use for me. Having said that, if someone wants to contribute an improvement in this area, I'll be more than happy to accept a PR.

**Comment by guettli** [comment]
I am using a simpler solution now, so I won't provide a PR. I just wanted you to know about this. Feel free to re-open.
