### ISSUE TITLE
Unreasonably high CPU usage

### ISSUE THREAD

**Issue by spacegoing** [rq/rq#1446]
I'm new to rq, I enqueued my job normally and found the CPU usage is unreasonably high. Normally the job I submitted only take 1 CPU, but submitting with rq job and executing with `rq worker` it will takes nearly 30 CPUs. I would love to know what am I doing wrong?

[how I enqueue](https://i.stack.imgur.com/4spS1.png)
[CPU usage](https://i.stack.imgur.com/ZkjMS.png)
https://stackoverflow.com/questions/67031737/python-rq-takes-unreasonably-high-cpu-usage

**Comment by selwin** [comment]
Check the number of workers that you run. It could be that you're running a high number of workers which cause all of them to pick up jobs at the same time.

**Comment by spacegoing** [comment]
@selwin Thanks for your message, but it is not the case. I only had 1 worker running but still it has that high usage
