### ISSUE TITLE
How many workers should I have running in relationship to the number of cores I have?

### ISSUE THREAD

**Issue by majonathany** [rq/rq#1447]
Hi,

I use an EC2 instance with 8 cores - and I realize that right now I've only been testing with 1 or 2 requests max at a given time. Right now, with the architecture of our microservice, one request typically uses one worker.

It dawned on me that if only one worker is running, we can't actually make use of the different cores because the cores can only be occupied by one python process at a given moment.

So, I was thinking maybe I should start multiple workers. Maybe I could start 20 at a given time? Is there a drawback to that many workers, given that every request initializes a worker and this will cut out the latency involved in stopping and starting a worker?

I actually use Django-RQ 2.4.0, but since it is based off this library, I figure advice here could also be helpful.

Thanks!

**Comment by selwin** [comment]
It depends on the functions being executed by the workers themselves. You'll just have to experiment with your workload and see what works best for you. RQ itself is very lightweight, it's the type of jobs they run that will affect your CPU's workload.
