### ISSUE TITLE
Some Jobs not removed from redis

### ISSUE THREAD

**Issue by waldner** [rq/rq#1450]
I have a number of jobs (a minority) that, once completed, are not removed from redis.
Usually, I see the key eg `rq:job:a48172a7-4e25-447e-9ac2-8b3c208bbf3c`, with TTL: -1 and Type: Hash, and the only field it has is `last_heartbeat` and its value is a timestamp (eg `2021-04-20T00:03:44.049309Z`).
Since I run many jobs, these ghost jobs tend to pile up in redis and I have to periodically clean them up manually.
I can't identify anything special about these jobs, other instances of the same function are correctly removed, and this seems to happen randomly. 
I don't know where to start or where to look to debug this. Any help will be appreciated.

**Comment by selwin** [comment]
Hmm, are you using the latest version of RQ? My guess would be that there's a race condition happening somewhere in your server infrastructure that causes heartbeat to arrive after the job has been completed.

**Comment by waldner** [comment]
I'm using RQ 1.8.0, which AFAICT is the latest stable. Perhaps there's some modification in the master version?

**Comment by waldner** [comment]
With 1.10.0 I still see these orphan jobs. By "orphan jobs" I mean jobs that have definitely terminated, but are not in any of these places: FinishedJobRegistry, FailedJobRegistry, StartedJobRegistry, ScheduledJobRegistry and are also not queued, deferred or cancelled. They simply exist in redis as `rq:job:*` keys, and are not referenced from any other place, so they stay there forever.

**Comment by selwin** [comment]
@waldner you’re positive that these jobs are not leftovers from the previous RQ version, right?

Can you check what keys these orphaned jobs have?

**Comment by waldner** [comment]
> @waldner you’re positive that these jobs are not leftovers from the previous RQ version, right?

Yes absolutely, I started from a clean state. Here's a list of the currently orphaned job keys (not sure how it helps though):

```
rq:job:23d05045-282b-49f3-aaf9-3b65d70f08ff
rq:job:be83f107-2360-45a0-96fe-7567aadbcfe3
rq:job:9227f804-710f-4897-89ce-4c37f1878133
rq:job:375c5b92-3616-47dd-bcf7-b805f6d1e503
rq:job:84a8b7d1-4ec0-40a0-9b73-441b07bd5550
rq:job:c2ef4ab1-e09b-47fb-a9dd-fa2bb71722ba
rq:job:549b6d8e-d532-49f0-a2d4-a8ddb31ea6c1
rq:job:e21ad2a3-43fe-4c00-8a6c-f251e29a86f2
rq:job:21b2e904-0146-4785-8e1d-a56d4539ab70
rq:job:6465926b-2afd-4b97-86b8-793125591506
rq:job:2342fd45-f8e1-493f-9e07-60e4330b7960
rq:job:13165578-b70b-47e2-95f0-617649cda021
rq:job:8d1e6de4-b06a-4b76-85fa-4dba6ad377a3
rq:job:6e06c947-19f8-4d24-8b5f-f78d99621ab4
rq:job:5059740e-9a92-438b-bdc6-348e82440e8f
rq:job:5dddb267-f4b7-45ad-8afa-4090b7b77d28
rq:job:8acfcde2-1534-4da7-80b1-a568b571dc98
rq:job:73b87d60-d6e8-4617-8078-cd94a645e4b2
rq:job:f814281c-3d81-4571-b9cc-54bd5a35ff06
rq:job:e5fca967-895a-4a3a-ac6f-65573726f924
rq:job:e94166c3-3a03-4a5d-8dc5-d99b0d097976
rq:job:d5b27443-79ec-45d4-a4f7-9757cf4dcdc2
rq:job:bb5ef9d5-9adb-4bea-9dca-bf3214aacea9
rq:job:1be71660-5361-4464-bd43-55fe793b3998
rq:job:00d5397b-4ea6-4914-b802-5a8566be42b4
rq:job:007ee67c-0aac-4c93-8faa-c8bed8b0c0cd
```

**Comment by selwin** [comment]
Oh I meant can you examine the keys (they should be Redis hashes) and print
out their contents? Use `hgetall(key)` and print out the dictionary in
those keys.

**Comment by waldner** [comment]
Ah well, as I said in my first message (but I rechecked just in case) they're all as follows:

```
1) "last_heartbeat"
2) "2021-09-10T16:49:59.878729Z"
```
each with different dates of course.

**Comment by selwin** [comment]
@waldner ok thanks for the clarification. I had to make sure because 1.10 supposedly eliminated race conditions created by heartbeats. This means there are other heartbeats with race conditions. Will look into it.

**Comment by selwin** [comment]
@waldner one more thing, are you setting your jobs so that they expire immediately? i.e result_ttl = 0.

**Comment by waldner** [comment]
Yes, those jobs that remain orphaned are indeed set up to expire immediately, good catch.

**Comment by Padge91** [comment]
I believe I'm witnessing this behavior again; my earlier resolution may have been a red herring. I'm noticing the same behavior as reported above. Using version 1.10.0, result_ttl=0 for all jobs we submit (failure_ttl=0 also), and when I do hgetall on the keys in Redis they only have fields like so:
```
1) "last_heartbeat"
2) "2021-11-03T21:50:18.917245Z"
```

**Comment by selwin** [comment]
Yeah, this issue is caused by a race condition and is tricky to solve. I haven't been able to find an elegant solution for this.

I was able to solve the previous race condition bug where jobs remain in `StartedJobRegistry` even though it finished normally by using [xx=True](https://github.com/rq/rq/blob/master/rq/worker.py#L816) argument provided by Redis.

Unfortunately no such option exists for `hset` and its variant of commands.

**Comment by selwin** [comment]
@waldner @Padge91 can you check if this https://github.com/rq/rq/pull/1591 solves your issues?

**Comment by Padge91** [comment]
@selwin Will give it a try in our dev environment, though the volume is pretty small so it may take a bit to be certain it fixes the issue.

For a quick workaround in production, I will probably set result_ttl and failure_ttl to small values to try and void the race condition.

Thank you for your hard work, I appreciate your help.

**Comment by waldner** [comment]
It'll be some time before I can try this, but I'll do it ASAP. Thanks!

**Comment by waldner** [comment]
Ok, I've just applied the branch to the most heavy-load jobs I have (which were those that produced > 90% of the orphaned jobs). I'll let you know how it goes in a few days. Thanks.

**Comment by selwin** [comment]
👍🏻

**Comment by waldner** [comment]
As a preliminary result, I see many fewer orphaned jobs now, and they're likely to come from the other (unpatched) workers. I will perform a more thorough check when I have time, but it definitely seems promising so far.

**Comment by waldner** [comment]
I confirm what I said in my previous comment. If you can merge the patch and make a release, I'll be happy to apply it to all my workers. Thanks!

**Comment by selwin** [comment]
@waldner great thanks!

**Comment by waldner** [comment]
I'm happy to report that with 1.10.1 everywhere I have had exactly ZERO orphaned jobs in the last week so far.
Closing as this definitely seems fixed to me. Thanks!
