### ISSUE TITLE
why parent process doesn't exit after worker is forked

### ISSUE THREAD

**Issue by xdandyx** [rq/rq#1451]
I know that rq starts the worker by fork, and I want to realize the function of "turning the worker into a background orphan process". Therefore, I use the child process A to start the worker, and kill the child process A (worker's parent process) after the worker starts, but this method does not work in django, I will find that process A always exists. It stands to reason that rq's fork only replicates the A process, but even the listening ports are replicated in django. So I am a little confused whether it is the problem of rq or django

**Comment by selwin** [comment]
Don't roll your own worker process, you should use something like https://github.com/rq/django-rq instead.
