### ISSUE TITLE
Docker image on dockerhub/ghcr.io

### ISSUE THREAD

**Issue by rpkak** [rq/rq#1452]
As referenced in #1340 and #1448 there should be an official docker image from rq on dockerhub (or ghcr.io).

If some official pushs the image to dockerhub, I could create a github workflow for automated pushing of new versions.

**Comment by selwin** [comment]
I'm not familiar with docker hub, do you know how we should get started with this?

**Comment by rpkak** [comment]
I think to use ghcr.io nothing more than a docker push is used. For dockerhub I suggest an organisation (e.g. `rq`) and a repo (e.g. `worker`).

**Comment by rpkak** [comment]
I wouldn't link docker to this repo. I think making a github workflow is better.

**Comment by rpkak** [comment]
Is it ok, if I start know with the implementation:

- github workflow for automatic updates of the docker image
- dockerfile: installing rq from local and not from pypi
- moving `Dockerfile` and `run_tests_in_docker.sh` to another folder (e.g. `tests`) and `docker/Dockerfile` to the repo folder to show, what the dockerfile for use is.

**Comment by rpkak** [comment]
I have created a dockerhub organisation that can be found [here](https://hub.docker.com/u/redisqueue/).

@selwin could you please:

- Create a dockerhub account at https://hub.docker.com/
- Write me your docker id (e.g. in this issue) so that I can add you to the docker organisation
- Create a personal access token of your docker account and paste it in a GitHub secret of this repo called `DOCKER_TOKEN` (will be used by the workflow)

After this the workflow will push new versions of rq to dockerhub and docker.pkg.github.com.

**Comment by selwin** [comment]
@rpkak 

My docker id is `selwin`. I also  added `DOCKER_TOKEN` repository secret. Thanks!

**Comment by rpkak** [comment]
@selwin Can you please pull all old versions from **dockerhub** and push them to **docker.pkg.github.com**?

I hope noone wants to use rq<=9.0.0 with docker.
