### ISSUE TITLE
rq no longer works with Click 8.0+

### ISSUE THREAD

**Issue by shohamc1** [rq/rq#1464]
When trying to run `rq worker` now throws a `ValueError`. Here is the full traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/rq", line 5, in <module>
    from rq.cli import main
  File "/usr/local/lib/python3.9/site-packages/rq/cli/__init__.py", line 2, in <module>
    from .cli import main
  File "/usr/local/lib/python3.9/site-packages/rq/cli/cli.py", line 99, in <module>
    def empty(cli_config, all, queues, **options):
  File "/usr/local/lib/python3.9/site-packages/rq/cli/cli.py", line 77, in pass_cli_config
    func = option(func)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 2467, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 2106, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```

This seems to be an issue with [Click 8.0](https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0) which was released yesterday. A temporary downgrade to version 7.1.2 can be used as a temporary workaround.

**Comment by rpkak** [comment]
I can create a PR to change the default arg of `--path` from `'.'` to `['.']`. After that `default` is a list.

**Comment by dominem** [comment]
Thanks guys! I've just ran into the same issue and found that it might be quite simple to fix.
I'm new to rq community. Do you think it will be merged this week or during the next one? I'm just curious how fast things are going here.

**Comment by olegver** [comment]
@shohamc1, thanks for reporting - I've ran into exactly the same thing.

Could you, maybe, rename the issue to 'rq' no longer works with 'click 8.0.0'? 
I spent half an hour digging into rq/click code to get to the same conclusion as you, didn't check your issue due to a misleading name (I use python 3.8).

**Comment by shohamc1** [comment]
> ).



> 
> 
> @shohamc1, thanks for reporting - I've ran into exactly the same thing.
> 
> Could you, maybe, rename the issue to 'rq' no longer works with 'click 8.0.0'?
> I spent half an hour digging into rq/click code to get to the same conclusion as you, didn't check your issue due to a misleading name (I use python 3.8).

Sorry for the misleading name, I have renamed the issue.

Thanks @rpkak for the quick work in opening the PR.

**Comment by jenstroeger** [comment]
This bug is a good example of why package dependencies should be _frozen_ to a specific version or version range, instead of allowing any new version:

https://github.com/rq/rq/blob/b84b39f75f367f21a643bb2235b9dabc7ec7ca1c/requirements.txt#L1-L2
