### ISSUE TITLE
Is there a way to pass the parameters ssl=True, ssl_cert_reqs=None to the cli $rq info? 

### ISSUE THREAD

**Issue by mgcdanny** [rq/rq#1468]
I am connecting to Redis and RQ like this:

```python
import redis
from rq import Worker, Queue, Connection

conn = redis.Redis(
    host=host, password=password, port=port, ssl=True, ssl_cert_reqs=None
)

with Connection(conn):
    worker = Worker(map(Queue, listen))
    worker.work(with_scheduler=True)
```

However, I can't get the RQ cli to work:

$ rq info --url ....

Is there a way to pass the parameters ssl=True, ssl_cert_reqs=None to the RQ cli ? 

Thanks!

**Comment by rpkak** [comment]
You can use a [config file](https://python-rq.org/docs/workers/#using-a-config-file) (just a python file which declares variables) using
```
rq info --config [filename of the config file without '.py']
```
The config file would look like this:
```python
REDIS_HOST = 'yourhost'      # Default: 'localhost'
REDIS_PORT = 6379            # Default: 6379
REDIS_PASSWORD = 'secret'    # Default: None
REDIS_SSL = True             # Default: False
REDIS_SSL_CA_CERTS = None    # Default: None
REDIS_DB = 1                 # Default: 0
```

(works for all `rq` commands such as `rq worker`)

**Comment by selwin** [comment]
Thanks @rpkak for answering.

**Comment by mgcdanny** [comment]
Thank you all very much!  @selwin @rpkak 

Now I am getting this error:

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain

Can I specifically set this parameter in the config file?

ssl_cert_reqs

I found a similar issue here:
https://github.com/andymccurdy/redis-py/issues/1080

with what I think the important part being this:

"I still think that the problem is that by default the ssl_cert_reqs is set to 'required'. If someone wants to use ssl=true with password only, without certs, one needs to change this parameter instead of setting it to required only when you want to specify specific cert files."

I am using Reids on Heroku and trying to follow the instructions per here:
https://devcenter.heroku.com/articles/heroku-redis#connecting-in-python

**Comment by mgcdanny** [comment]
Hi - 

I was able to get it working by adding the following code to the cli in rq file, should I make a pull request:
```
"ssl_cert_reqs": settings.get("REDIS_SSL_CERT_REQS", "required"),
```

![image](https://user-images.githubusercontent.com/2024459/120514952-cf49ce80-c39b-11eb-96da-e652877be69b.png)

**Comment by selwin** [comment]
Sure, PR is welcome :)

**Comment by vinicius-oa** [comment]
for those who just need to specify `ssl=True`, you need to pass the url string as `rediss` instead of `redis`
