### ISSUE TITLE
Q: How to use database for permanent storage result

### ISSUE THREAD

**Issue by FloLaco** [rq/rq#1473]
Hi,

In my case, RQ will be trigger by a flask API.
My API clients will trigger a job, and they can get the result with another API.

But I need to keep a trace of ALL jobs (input data and result) in a database.
I suppose I have to create a custom class for handling an insert in the database at the begging of the job and update it a the end of the job.
Which I don't understand, is which class do I need to overide for my case ? Worker ? Queue ? Job ?

Thanks in advance

**Comment by rpkak** [comment]
You can use the
```python
job = Job.fetch(id, connection)
```
method to get a job instance. After that your result can be found at `job.result`.
You must store the `job.id` on a database or at client side oder give the job an unique id that the client knows. Otherwise I don't think you have to store anything on a database.

I don't know why you should overwrite anything.

**Comment by FloLaco** [comment]
Thanks you @rpkak 
The problem is the Redis retention. By default it's 500sec, too short, but I can't put 0 (infinite) because Redis is not a database, it's not made for archiving.
The other problem is that, an user who triggered a job can does not have to check the result back. So, how can I store the result into a database if nobody try to get the result ? (And, make a "cron" to get results and store to database is not an option)

**Comment by lowercase00** [comment]
This is mostly client-side implementation/architecture.

As @rpkak explained, the most common way to handle this is to return the `job_id` to your API client, and have a `/job/<job_id>` route in which you can get the job status.

If the user does not have to check the result, then it just depends on how you want to use this. As you mentioned you could just have a cronjob that queries results from Redis and saves them in a database.

Closing.
