### ISSUE TITLE
RQ with supervisord - Empty stderr files at intialization

### ISSUE THREAD

**Issue by duominds** [rq/rq#1477]
Hi, 

I'm having a setup for RQ where I'm using 10 workers under supervisord. The setup works well for my needs and I'm satisfied with. The only issue I'm facing with the setup, is that when ever supervisord initialize the workers I get 2 files created for each worker in the following path insider the container: /var/log/supervisor

The first file is worker-<worker-id>-stdout---supervisor-<ID>.log  
The second file is worker-<worker-id>-stderr---supervisor-<ID>.log

Any idea why I'm getting an empty err file created  ?, is that the default behavior for RQ or I have missed something in the configuration ? 

Here are the components I'm using in my project: 

Flask
RQ
Redis
Supervisor

Thanks a lot in advance

**Comment by selwin** [comment]
I'm not sure how Supervisord behaves in this regard, but this doesn't look like anything to do with RQ. Feel free to reopen if there's a PR that we can do to fix this.
