### ISSUE TITLE
Job not entering queue even though is_queued returns true

### ISSUE THREAD

**Issue by tnolan8** [rq/rq#1487]
Hi there,

I'm using a combination of FastAPI, rq and Supervisor. I have an API endpoint which kicks off a job that starts a Docker container through a shell script. The first time I hit the endpoint I can see the following attributes in the my API logs for the job (I'm just printing a couple things from the job):
```
status queued
is_queue True
queue atq
INFO:     127.0.0.1:52440 - "GET /user/login HTTP/1.1" 200 OK
```

However looking at the supervisor _rq_ logs the job doesn't appear to be hitting the queue. If I call the endpoint a second time I get the same output in my API logs:
```
status queued
is_queue True
queue atq
INFO:     127.0.0.1:52440 - "GET /user/login HTTP/1.1" 200 OK
```
But this time in my logs for _rq_ I can see that the job does enter the queue:
```
09:28:22 atq: app.tasks.start_tws.start_tws() (0dcfecdc-7462-4eea-bb29-fd8e75b21a7e)
Creating ib-docker_tws_1 ... 
Creating ib-docker_tws_1 ... done
09:28:24 atq: Job OK (0dcfecdc-7462-4eea-bb29-fd8e75b21a7e)
```

Is there any reason why the job wouldn't hit the queue the first time but works fine the second time I hit the route? Any help would be very much appreciated.

Version: rq==1.8.1

**Comment by rpkak** [comment]
Can you share the code, where you enqueue to job to the queue?

**Comment by tnolan8** [comment]
@rpkak I can't share the actual repo as it's private but I can cut and paste it. 

```python
# redis queue
from redis import Redis, connection
from rq import Queue

redis = Redis()
redisQueue = Queue('atq', connection=redis)
```
```python
# FastAPI endpoint
@router.get("/user/login")
async def login():
  start_tws = await ibgw.start()
  return start_tws
```

```python
# service to start job
from app.helpers.redisQueue import redisQueue

async def start(self):
  result = redisQueue.enqueue(start_tws)
  print("status ", result.get_status())
  print("is_queue", result.is_queued)
  print("worker ", result.worker_name)
  print("queue ", result.origin)
  return {"Success"}
```

```python
# start_tws job
def start_tws():
  f = open("/tmp/build_tws.log", "w")
    subprocess.call(['sh', "{path}/scripts/start_tws_container.sh".format(
      path=os.environ.get("PROJECT_PATH"
    ))], stdout=f)
```

**Comment by tnolan8** [comment]
Just to add, I've tried again this morning and found the following. First time hitting the endpoint I can see this in my logs:
```
id  6df55006-ae17-4e43-88fb-e99c84c8d4ea
status  queued
is_queue True
worker  None
queue  atq
INFO:     127.0.0.1:50781 - "GET /user/login HTTP/1.1" 200 OK
```

In Redis I can see the key is there and looking at it I get the following:
```
 1) "status"
 2) "finished"
 3) "created_at"
 4) "2021-06-08T11:17:56.839591Z"
 5) "data"
 6) "x\x9ck`\x9d\xaa\xc1\x00\x01\x1a=\xb2\x89\x05\x05z%\x89\xc5\xd9\xc5z\xc5%\x89E%\xf1%\xe5H\xac)~\x9a\xb5SJ\xa6\xe8\x01\x00x\xa9\x11-"
 7) "started_at"
 8) "2021-06-08T11:17:56.853930Z"
 9) "ended_at"
10) "2021-06-08T11:17:57.411097Z"
11) "last_heartbeat"
12) "2021-06-08T11:17:56.848851Z"
13) "worker_name"
14) ""
15) "origin"
16) "atq"
17) "description"
18) "app.tasks.start_tws.start_tws()"
19) "enqueued_at"
20) "2021-06-08T11:17:56.839741Z"
21) "timeout"
22) "180"
```

In _rq:finished:atq_ I can see the ID _6df55006-ae17-4e43-88fb-e99c84c8d4ea_. 

I've also added print statements inside my job which don't get executed on first request but subsequently do on the next. This is my Supervisor conf also:
```
[program:rq]
command=%(ENV_PYTHONENV)s/rq worker atq --with-scheduler
process_name=%(program_name)s-%(process_num)s
stdout_logfile=%(ENV_PROJECT_PATH)s/logs/supervisord/rq.log
stderr_logfile=%(ENV_PROJECT_PATH)s/logs/supervisord/rq.log
numprocs=1
directory=%(ENV_PROJECT_PATH)s
stopsignal=TERM
autostart=true
autorestart=true
```

If there's anything else that I can provide that might be over use let me know. Thanks for having a look.

**Comment by tnolan8** [comment]
I change the queue name and now it all appears to be working, not entirely sure what fixed it though, only thing I changed was the queue name and used double quotes for the queue name when creating the queue. Looks to be all good though.
