### ISSUE TITLE
Queue gets cleared automatically even though it has a lot of jobs in it.

### ISSUE THREAD

**Issue by shaikhAbuzar** [rq/rq#1506]
I  am running rq on my machine and and when I load all the jobs in the and start the workers, the workers select the first batch and run and the select the second (in some cases) while in most cases the queue is gone and all the other jobs are lost, even though the worker is up and running and executing the jobs.

**Comment by selwin** [comment]
I'm going to close this issue because there's not much information to go on. Would be great if you can show some logging outputs so we can see what's happening.
