### ISSUE TITLE
Sentinel Configuration Documentation

### ISSUE THREAD

**Issue by Erandurthil** [rq/rq#1509]
I just went through about an hour of reading through the source code to find out why the redis sentinel configuration was not working for the workers. 

In the documentation it states to use this format : 
SENTINEL: {'INSTANCES':, 'SOCKET_TIMEOUT':, 'PASSWORD':,'DB':, 'MASTER_NAME':}

While the the actual working format is: 
SENTINEL= {'INSTANCES':, 'SOCKET_TIMEOUT':, 'PASSWORD':,'DB':, 'MASTER_NAME':}

Please adapt the config reading routine or change the documentation.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/commit/1352465ad1965b635c41bb73934224193d695765
