### ISSUE TITLE
Send files with queue on remote server

### ISSUE THREAD

**Issue by nadermx** [rq/rq#1511]
If I have a a long running task that reads files from the server that starts the queue.  Is there an elegant way to send the files?

So say for example, I have 

```
queue.enqueue(long_running_task, input_file_path, out_put_file_path)
```
Can I have RQ send the file to the remote server, and then send it back? Or do I have to write a seperate function sending the files to the remote server, and one sending it back once it's done?

**Comment by bytearchive** [comment]
if it is a very small small, and if it is a toy project, maybe
otherwise, I would just put them in s3 and send the path to the remote server and download it at remote
or put it in behind HTTP server/nginx and send HTTP link via rq and have remote server download it

**Comment by nadermx** [comment]
I ended up putting the files on the server the task was going to be executed on.  Thank you
