### ISSUE TITLE
'NoneType' object has no attribute 'dependencies_are_met'

### ISSUE THREAD

**Issue by jad7** [rq/rq#1518]
Hello. I don't deeply know RQ code but on prod periodically we're getting an exception:
```
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/rq/worker.py", line 1042, in perform_job
    self.handle_job_success(job=job,
  File "/opt/bitnami/python/lib/python3.8/site-packages/rq/worker.py", line 978, in handle_job_success
    queue.enqueue_dependents(job, pipeline=pipeline)
  File "/opt/bitnami/python/lib/python3.8/site-packages/rq/queue.py", line 596, in enqueue_dependents
    jobs_to_enqueue = [
  File "/opt/bitnami/python/lib/python3.8/site-packages/rq/queue.py", line 602, in <listcomp>
    ) if dependent_job.dependencies_are_met(
AttributeError: 'NoneType' object has no attribute 'dependencies_are_met'
```
The problem is in a method queue.enqueue_dependents().  ->
```
dependent_job for dependent_job
                    in self.job_class.fetch_many(
                        dependent_job_ids,
                        connection=self.connection,
                        serializer=self.serializer
                    ) if dependent_job.dependencies_are_met(
                        exclude_job_id=job.id,
                        pipeline=pipe
                    )
```
self.job_class.fetch_many() method could return `None`.
```
....
        for i, job_id in enumerate(job_ids):
            if results[i]:
                job = cls(job_id, connection=connection, serializer=serializer)
                job.restore(results[i])
                jobs.append(job)
            else:
                jobs.append(None)  # This

        return jobs
```
At least it should be None-check, like `if dependent_job and dependent_job.dependencies_are_met(...)`. At most, something else...

**Comment by cesarferradas** [comment]
We see this issue intermittently too. Will make a PR with the above suggestion soon.

**Comment by cesarferradas** [comment]
@jad7 trying to understand how to reproduce. I believe this is caused by deleting a task via RQ dashboard or the RQ cli which was actually a dependency to another task which wasn't deleted. When the task finishes, it can no longer find the dependency in redis. Does this sound familiar?

**Comment by jad7** [comment]
I think it should be some kind of warning. To reproduce, let's assume that you have the tasks "A" and "B". "B" depends on "A". 'A' is submitted with postponing time or execute longer than TTL for 'in_queue'. This situation leads to this exception. In this case, the worker will die.
