### ISSUE TITLE
Mysql connection in redis queue job

### ISSUE THREAD

**Issue by SauravTelge** [rq/rq#1520]
I am a novice coder. I was trying to send data that I processed in my background worker to the database in the job itself, but couldn't because Redis couldn't detect the MySQL connection. Please guide me on how to connect my SQL DB to the job worker.

**Comment by rpkak** [comment]
Redis can't detect MySQL, because redis and MySQL are both databases. If redis is running rq shouldn't cause problems and if MySQL is running, your job, which needs MySQL should work as well.

So make sure your redis and your MySQL servers are running.

Otherwise you have to tell more information.

**Comment by SauravTelge** [comment]
yup, basically I had to add this code for MYSQL to work : 

`with app.app_context():` 

and then connect to MySQL DB.
Thanks a lot for your prompt reply.
