### ISSUE TITLE
Can I use RQ to run an infinite loop with some specific requirements?

### ISSUE THREAD

**Issue by amks1** [rq/rq#1527]
I need a listener function to start as soon as my web app starts, preferably on a different server from that of my web app. Only one instance of the listener should ever be running globally, even if multiple instances of the app itself are running. Also, if the function exits for some reason (exception etc) it should start right back up.

I already have RQ set up for my app to handle other asynchronous tasks like email and logging, but is it possible to achieve the above requirements with RQ?

**Comment by selwin** [comment]
No, RQ can't do this.
