### ISSUE TITLE
Multiple schedulers started for the same queue.

### ISSUE THREAD

**Issue by arterrey** [rq/rq#1531]
Using version 1.9

I have four workers on the same queue each started with the command:

```
rq worker --url redis://127.0.0.1:6379 --worker-class app.rq.MyWroker --job-class app.rq.MyJob --with-scheduler inet
```

After 4 days all 4 works are running the scheduler which is causing duplicate executions of jobs.  Here are the logs grep'ed for `rq.scheduler` but excluding lines containing `Trying to acquire locks for inet` I've sorted the logs in terms of time stamp.

```
rq-inet1-stderr---supervisor-mb7yjkax.log:2021-08-04 22:44:27,775 INFO  [rq.scheduler:233][MainThread] Scheduler for inet started with PID 1926
rq-inet2-stderr---supervisor-sl2qg0un.log:2021-08-05 13:46:29,650 INFO  [rq.scheduler:233][MainThread] Scheduler for inet started with PID 11335
rq-inet3-stderr---supervisor-8jwj8v2t.log:2021-08-06 13:44:55,344 INFO  [rq.scheduler:233][MainThread] Scheduler for inet started with PID 22254
rq-inet4-stderr---supervisor-m1aykzdz.log:2021-08-07 13:43:48,805 INFO  [rq.scheduler:233][MainThread] Scheduler for inet started with PID 30348
```

As you can see inet1, inet2, inet3 and inet3 all have acquired the schduler. After realising the circus I stop inet2, inet3, and inet4 which results in three schdeuler locks being release:

```
rq-inet2-stderr---supervisor-sl2qg0un.log:2021-08-07 14:54:47,138 INFO  [rq.scheduler:196][MainThread] Scheduler stopping, releasing locks for inet...
rq-inet2-stderr---supervisor-sl2qg0un.log:2021-08-07 14:54:47,419 INFO  [rq.scheduler:243][MainThread] Scheduler with PID 11335 has stopped
rq-inet3-stderr---supervisor-8jwj8v2t.log:2021-08-07 14:54:52,335 INFO  [rq.scheduler:196][MainThread] Scheduler stopping, releasing locks for inet...
rq-inet3-stderr---supervisor-8jwj8v2t.log:2021-08-07 14:54:52,396 INFO  [rq.scheduler:243][MainThread] Scheduler with PID 22254 has stopped
rq-inet4-stderr---supervisor-m1aykzdz.log:2021-08-07 14:54:58,999 INFO  [rq.scheduler:196][MainThread] Scheduler stopping, releasing locks for inet...
rq-inet4-stderr---supervisor-m1aykzdz.log:2021-08-07 14:54:59,000 INFO  [rq.scheduler:243][MainThread] Scheduler with PID 30348 has stopped
```

**Comment by arterrey** [comment]
The difference in timestamps between workers 2, 3 and 4 is about 24 hours which makes me think there is a TTL being set on the lock. 

The difference in timestamps between workers 1 and 2 is much less then 24 hours - could be more then one bug?

**Comment by selwin** [comment]
I think I know what the issue is. Scheduler locks have  a [TTL of 60 seconds](https://github.com/rq/rq/blob/master/rq/scheduler.py#L109) so if you have jobs that run for longer than that, there's a possibility that locks will expire.
