### ISSUE TITLE
Please create a 1.10.0 release 

### ISSUE THREAD

**Issue by joshcoden** [rq/rq#1551]
It appears that [documentation](https://python-rq.org/docs/#cli-enqueueing) references features available in version 1.10.0:

> ### CLI Enqueueing
> _New in version 1.10.0._
> 
> If you prefer enqueueing jobs via the command line interface or do not use python you can use this.

Though it appears as though version 1.9.0 is the newest available at pypi.org. Could a version 1.10.0 be created from the current master branch?

**Comment by aparcar** [comment]
I would also appreciate a new release!

**Comment by aparcar** [comment]
Friendly ping, there are numerous great changes which I'd like to start using:

```
Bo Bayles (1):
      Use result_ttl for synchronous queues (#1510)

César Ferradas (2):
      Handle ResponseError when CLIENT command is not supported (#1514)
      add None check before dependencies_are_met (#1532)

Josh Cohen (2):
      Respect serializer (#1538)
      Add option to enqueue a job's dependents when canceling (#1549)

Paul Spooren (1):
      job: add get_meta() function (#1536)

Selwin Ong (5):
      Requeueing job should clear job.exc_info (#1543)
      Fixed SENTINEL docs
      Minor changes (#1544)
      job.cancel() puts job into CanceledJobRegistry. (#1546)
      Main worker should use zadd(xx=True) to update heartbeat. (#1550)

Stanley Ruheza (1):
      fix: typo on readme file - enqueue_in() (#1534)

rpkak (4):
      Daily workflow for dependency testing (#1470)
      fix query request of issue listing (#1519)
      Make unstable tests more stable (#1523)
      Allows enqueueing by the cli (#1466)

waldner (1):
      Fix repo url for git intallation (#1545)
```

**Comment by selwin** [comment]
Hey guys, I want to try to investigate this issue https://github.com/rq/rq/issues/1554 . If I can't fix this issue, I'll make a release this weekend regardless.

**Comment by aparcar** [comment]
Looks like you just fixed it, great!

**Comment by selwin** [comment]
Version 1.10.0 is now on PyPI. Sorry for the wait!
