### ISSUE TITLE
RQ triggers job multiple times if date time object is timezone aware

### ISSUE THREAD

**Issue by aeltawela** [rq/rq#1554]
RQ triggers job multiple times if datetime object is timezone aware.

The issue occurs only if datetime has timezone info: queue.enqueue_at(datetime.now(tz=pytz.UTC) + timedelta(minutes=1), callback)

Here is how to reproduce the issue:

- Download the 3 files
https://gist.github.com/aeltawela/9219a170093d47196c08446944fb9262

- Install dependencies
pip install requirements.txt

- Run the example
python test

Output (triggered multiple times):
Triggered at 2021-09-05 15:41:01.528052
15:41:01 Worker rq:worker:48c43fdab0564b7e82d28afd8ddbd0d0: started, version 1.9.0
15:41:01 Subscribing to channel rq:pubsub:48c43fdab0564b7e82d28afd8ddbd0d0
15:41:01 *** Listening on default...
15:41:01 Trying to acquire locks for default
15:41:53 default: callback.callback() (3d9d01b6-1e5b-4c18-b6c4-56c1711fa5df)
Triggered at 2021-09-05 15:41:53.219054
15:41:53 default: Job OK (3d9d01b6-1e5b-4c18-b6c4-56c1711fa5df)
15:41:53 Result is kept for 500 seconds
15:41:54 default: callback.callback() (ec8acf59-ca0b-4e17-8bd7-86ff9eeca28a)
Triggered at 2021-09-05 15:41:54.231386
15:41:54 default: Job OK (ec8acf59-ca0b-4e17-8bd7-86ff9eeca28a)
15:41:54 Result is kept for 500 seconds
15:41:58 default: callback.callback() (083a365f-2206-482a-86fc-a7c307134ea1)
Triggered at 2021-09-05 15:41:58.289973
15:41:58 default: Job OK (083a365f-2206-482a-86fc-a7c307134ea1)
15:41:58 Result is kept for 500 seconds
15:42:01 default: callback.callback() (39814d7a-9d2d-4938-b321-7f90778faf5b)
Triggered at 2021-09-05 15:42:01.328329
15:42:01 default: Job OK (39814d7a-9d2d-4938-b321-7f90778faf5b)
15:42:01 Result is kept for 500 seconds
15:42:53 default: callback.callback() (469e7ef7-ed21-4547-be49-b58dda332c5e)

**Comment by selwin** [comment]
I tested your code and this does not look like a bug in RQ. You probably had some `callback` scheduled in your registry so whenever you run your script, it creates a new callback which in turn will create another job.

I modified your script slightly to clear the registry at the beginning of each run to show that this is not a bug in RQ. (**IMPORTANT** check the script below before you run this because it may lead to DATA LOSS).

```python
from redis import Redis
from rq import Queue, Worker
from rq.registry import ScheduledJobRegistry

from views import callback

redis = Redis()
queue = Queue(connection=redis)

if __name__ == "__main__":
    registry = ScheduledJobRegistry(queue=queue)
    redis.delete(registry.key)
    callback()
    worker = Worker(queues=[queue], connection=redis)
    worker.work(with_scheduler=True, logging_level="DEBUG")
```
