### ISSUE TITLE
code does not match the comment in job.py

### ISSUE THREAD

**Issue by rhaven-telesign** [rq/rq#1566]
job.py::113: ` elif not inspect.isclass(func) and hasattr(func, '__call__'):  # a callable class instance`

The "not" looks out of place

**Comment by rpkak** [comment]
`inspect.isclass` returns `True` if `func` is a `class`, but `False` if it is an instance.

```python
>>> inspect.isclass(object)
True
>>> inspect.isclass(object())
False
```
