### ISSUE TITLE
Any on_error / on_deferred callbacks?

### ISSUE THREAD

**Issue by euanmacinnes** [rq/rq#1596]
Hi,

I need to be able to track the full job status throughout a multi-user complicated pipeline, so it can be hard to see jobs that have errored or deferred without manually scanning the queues repeatedly and separately tracking what jobs are in the system. Do these callbacks exist, or any plan to implement such a thing?

Cheers,

Euan.

**Comment by selwin** [comment]
Yes, you can pass in `on_success` and `on_failure` arguments when [enqueueing jobs](https://python-rq.org/docs/#job-callbacks).
