### ISSUE TITLE
`remove_from_queue` not passed through in `Job.delete` to `Job._remove_from_registries`

### ISSUE THREAD

**Issue by joshcoden** [rq/rq#1598]
https://github.com/rq/rq/blob/0147b30f2bd6b5c26c530d5cb7a3c3714029b59a/rq/job.py#L788-L795

It should not be ignored.

**Comment by selwin** [comment]
Mind opening a PR for this? @joshcoden

**Comment by kusaku** [comment]
I found this issue too, the PR is here - https://github.com/rq/rq/pull/1601
