### ISSUE TITLE
sync job execution swallows exception

### ISSUE THREAD

**Issue by WeatherGod** [rq/rq#1603]
Before v1.10.1, the following would raise an exception from the execution of the given function.

```
q = Queue(is_async=False)
j = q.enqueue(div_by_zero)
```

Now, it doesn't. This is because `Queue.run_sync()`, which is called by `Queue.enqueue_job()` is swallowing the exception if an error callback wasn't set.

```
    def run_sync(self, job):
        with self.connection.pipeline() as pipeline:
            job.prepare_for_execution('sync', pipeline)

        try:
            job = self.run_job(job)
        except:  # noqa
            job.set_status(JobStatus.FAILED)
            if job.failure_callback:
                job.failure_callback(job, self.connection, *sys.exc_info())
        else:
            if job.success_callback:
                job.success_callback(job, self.connection, job.result)

        return job
```

In my view, this is a backwards-compatibility break.

Additionally, I haven't yet checked the behavior with asynced jobs, but do they still raise an exception if no error callback is set?

**Comment by WeatherGod** [comment]
Erm, ignore that last question, I just realized that it doesn't make a lot of sense (I wasn't thinking asynchronously...)

**Comment by selwin** [comment]
You're correct in that this is a backwards incompatible change.

But I think the previous behavior where RQ would raise an exception when job fails is a bug. The current behavior where RQ sets job status to `failed` and perform the usual bookkeeping stuff is correct because it is consistent how async jobs behave (and tests should be more accurate as a result).

In hindsight, I think the change should have been deferred until the next major version. I'll at least modify the changelog so that people are aware of it.

**Comment by WeatherGod** [comment]
Sorry for replying late to this (I imagine many of us have been distracted by other issues lately...)

I would like to point out that the behavior of the synced and asynced job execution is still quite different. If no error handler is specified, then nothing really happens to the job object (as far as I can tell). But for the asynced execution, there is a whole bunch of stuff that happens. See the snippet below for what happens for asynced exception handling:

```
        except:  # NOQA
            job.ended_at = utcnow()
            exc_info = sys.exc_info()
            exc_string = ''.join(traceback.format_exception(*exc_info))
            self.handle_job_failure(job=job, exc_string=exc_string, queue=queue,
                                    started_job_registry=started_job_registry)
            self.handle_exception(job, *exc_info)
```

Now, maybe this is elsewhere, but I can't find where the FAILED status is set for a synced job's exception getting swallowed. It isn't even logged as far as I can tell.

**Comment by selwin** [comment]
You’re right. The goal is to make async and sync job executions consistent. It’s better than before, but still not identical as you pointed out. Do you mind opening a pull request?

**Comment by WeatherGod** [comment]
I'd probably consider it, but it would have to wait a few weeks. My
approach to it would be to reduce code duplication by moving stuff into
job.py. My thinking is that an async job is just a synchronous job executed
by a worker. So if we could have the worker instance call the perform_job
method instead and have it only worry about worker-related things, then
we'd guarantee that asynced and synced jobs will execute nearly identically.

Note, I have not yet looked closely enough at the worker code for any fresh
splash of cold, hard reality to know if this is remotely possible.
