### ISSUE TITLE
Feature request: I suggest to add a simple way to rewrite all "rq:" prefix for redistribution keys.

### ISSUE THREAD

**Issue by maks-us** [rq/rq#1616]
I work in a company where one global Redis infrastructure could be shared between different services. 
I'd like to use RQ and avoid collisions with other projects. 
So I'd like to use project namespace as a prefix 
("rq:" prefix "project name:rq:" prefix )

**Comment by selwin** [comment]
This issue was proposed before, but I'm not sure this would add too much value. After all, you could do `Queue(name=prefix+queue_name)` instead of `Queue(prefix=prefix, name=queue_name)`.

**Comment by maks-us** [comment]
@selwin 
**Would you consider to merge PR if I extract "rq:" prefix as optional environment variable?**
It would be backward comparable.

I am able to inherit and rewrite Queue and Jobs key prefix. It become more complex when I begin looking at the workers Redis storage keys.

**Comment by selwin** [comment]
What kind of API are you proposing?

**Comment by maks-us** [comment]
I think about optional environment variable with fall back to "rq:".

redis_key_prefix = os.environ.get('RQ_REDIS_KEY_PREFIX', 'rq:')
