### ISSUE TITLE
 job decorator doesn't allow on_failure and on_success parameters

### ISSUE THREAD

**Issue by nepta1998** [rq/rq#1626]
I'm using the decorator to create jobs but it does not allow me to add the function that is used for when a job fails the same for when it's  successful.

worker1_1  | 2022-02-25T23:37:44.496565875Z Traceback (most recent call last):
worker1_1  | 2022-02-25T23:37:44.496568669Z   File "/usr/local/lib/python3.9/site-packages/rq/worker.py", line 1061, in perform_job
worker1_1  | 2022-02-25T23:37:44.496571546Z     rv = job.perform()
worker1_1  | 2022-02-25T23:37:44.496574265Z   File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 821, in perform
worker1_1  | 2022-02-25T23:37:44.496577169Z     self._result = self._execute()
worker1_1  | 2022-02-25T23:37:44.496579860Z   File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 844, in _execute
worker1_1  | 2022-02-25T23:37:44.496582711Z     result = self.func(*self.args, **self.kwargs)
worker1_1  | 2022-02-25T23:37:44.496585442Z TypeError: create_transaction() got an unexpected keyword argument 'on_failure'

**Comment by selwin** [comment]
Do you mind opening a PR for this?

**Comment by nepta1998** [comment]
@selwin ok PR is open.
