### ISSUE TITLE
If no failure callback, exception is not raised

### ISSUE THREAD

**Issue by ejm714** [rq/rq#1639]
There's a small bug in the recent change around failure callbacks in v.10.1.

If there is no failure callback but an error occurs, this gets swallowed rather than bubbled up to an exception. [This block](https://github.com/rq/rq/compare/v1.10...v1.10.1#diff-24e9998fb7718d4e0599f46e4e121f94ef08b56f8319805598d3ccb93fe6b0e4R584-R589) needs to handle the case where there is no failure callback. It should `raise` at the end so the exception can get handled somewhere else.

**Comment by selwin** [comment]
Mind opening a PR for this?

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1671
