### ISSUE TITLE
Horse killed job delete cause issues

### ISSUE THREAD

**Issue by veejar** [rq/rq#1643]
Steps to reproduce:
1. Start long-running job.
2. Kill this job using worker method "kill_horse".
3. Delete job from queue failed jobs using job.delete method.
4. Redis key "rq:failed:queue_name" will not be updated.

**Comment by veejar** [comment]
Issue is related to job with is_stopped=True.
job.delete() - works incorrect then
job.failed_job_registry.remove(job.id) - works fine

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1677
