### ISSUE TITLE
Canceled jobs are not removed from CanceledJobRegistry automatically

### ISSUE THREAD

**Issue by Brandhor** [rq/rq#1647]
Jobs in the other registries are removed automatically after 500 seconds but that's not the case for CanceledJobRegistry

**Comment by selwin** [comment]
Canceled jobs don't get automatically deleted unless the user chooses to do so (similar to jobs that are not yet executed). So this is a not a bug, unless you're finding cases when jobs get deleted, their entries in CanceledJobRegistry are not deleted.

I'm closing this issue for now, please re-open if you still think there's a bug.
