### ISSUE TITLE
Worker rq:worker found an unhandled exception, quitting...

### ISSUE THREAD

**Issue by lemueljay** [rq/rq#1654]
**ISSUE:** "Worker rq:worker : found an unhandled exception, quitting..." ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'

I am running a Django app which uses redis-rq and running 20 Heroku dyno workers. But it seems that rq workers throw an error on jobs that already timeout. 

This ends up all the dyno workers crashing, unable to get back up, making Redis full of enqueued jobs until it fills up and blows the entire queue.

Environment:
Heroku Platform
Python 2.7
Django==1.11.29
rq==1.3.0

I know Python 2.7 has been deprecated but is there any workaround on this issue? 

Thank you very much for your help.

**Comment by jonahmelhado** [comment]
I'm having the same issue and I'm not passing any empty strings to the job but I'm using Python 3.10.2

**Comment by selwin** [comment]
You should run the newest version of RQ.
