### ISSUE TITLE
Allow custom logging configuration

### ISSUE THREAD

**Issue by selwin** [rq/rq#166]
Currently there are a few ways to configure `Worker`'s exception handling behavior:
1. By passing  `--sentry-dsn` to `rqworker` (assuming that you want to use `sentry`)
2. By writing a custom script, passing your own exception handler to `Worker(exc_handler=foo)`

Now that `RQ` uses Python's `logging`, should we also allow the user to more easily configure logging when running `rqworker`? Python allows logging configuration to be [loaded from a file](http://docs.python.org/2/library/logging.config.html#logging.config.fileConfig), so we could add a `--logging-config=logging.conf` option to `rqworker`.

**Comment by phalgun** [comment]
+1. Would this be added? 

If not, is there a workaround to use a custom logger from the `logging` module.

**Comment by calvingiles** [comment]
My workaround is to add `from init_logging import logging` to `worker.py` and to create an `init_logging.py` as follows:

```python
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division

import logging
import os
import sys

__author__ = 'calvin'


class LoggerWriter:
    def __init__(self, logger, level, pipe):
        self.logger = logger
        self.level = level
        self.buffer = ''
        self.pipe = pipe

    def write(self, message):
        message = self.buffer + message
        lines = message.split('\n')
        self.buffer = lines[-1]
        lines = lines[:-1]
        for line in lines:
            self.logger.log(self.level, line)

    def flush(self):
        if self.buffer != '':
            self.logger.log(self.level, self.buffer)
        self.buffer = ''

    def isatty(self):
        self.pipe.isatty()


log_level = os.environ.get('LOG_LEVEL', 'INFO')
numeric_level = getattr(logging, log_level.upper(), None)
if not isinstance(numeric_level, int):
    raise ValueError('Invalid log level: %s' % log_level)
logging.basicConfig(level=numeric_level, format="%(asctime)s %(levelname)s %(message)s")

if not isinstance(sys.stdout, LoggerWriter):
    sys.stdout = LoggerWriter(logging, logging.INFO, sys.stdout)
if not isinstance(sys.stderr, LoggerWriter):
    sys.stderr = LoggerWriter(logging, logging.WARNING, sys.stderr)
```

This works pretty well but I get two log entries sent to the log file as rq is logging to stdout as well as logging.

**Comment by hnykda** [comment]
Any update on this? Probably not, right?

**Comment by selwin** [comment]
As far as I know, no one is working on this feature. It would be great if you could make a PR to add `--logging-config` though :)

**Comment by hnykda** [comment]
Hey. Thanks for the response. I edited the issue and it seems to me as good enough solution really.

**Comment by Houd1ny** [comment]
@hnykda how to start your own worker.py?

**Comment by hnykda** [comment]
https://python-rq.org/docs/workers/#custom-worker-classes

```
import logging
from rq import Worker

# configure your logging format here

class FreightWorker(Worker):
    pass
```

**Comment by Houd1ny** [comment]
@hnykda Thank you for your response!
Could you take a look on my question https://github.com/rq/rq/issues/1088 ?

**Comment by cjbland** [comment]
Is anyone having issues with setting the minimum log level with v1.2.2? I cannot seem to get `info` log messages to not be displayed.

**Comment by WillUdstrand** [comment]
+1 on this feature

**Comment by lowercase00** [comment]
Currently there are quite a few ways to do this: configuring the log formatting on the worker itself, or just configuring a regular logger and running the worker manually with `worker.work()`.
