### ISSUE TITLE
A canceled scheduled job stays in the scheduled queue and then executes anyway

### ISSUE THREAD

**Issue by euanmacinnes** [rq/rq#1669]
I have an issue where a job that has been scheduled, but the user has later decided to cancel it, stays in the scheduled queue, and does not move to the canceled queue. In addition, the scheduled job continues to execute anyway.

It's a reasonably simple workaround in a way, as the job knows it's canceled, so it can be checked at the start prior to the job executing, however that then results in the job being marked as Successful.

**Comment by selwin** [comment]
The real fix is that if a job is canceled, it should also be removed from `ScheduledJobRegistry` so it doesn't get executed. Mind opening a PR for this?

**Comment by selwin** [comment]
Upon checking the code, this logic is already here. https://github.com/rq/rq/blob/840438559261fd64b07d1bce489d352e6d553da5/rq/job.py#L803
