### ISSUE TITLE
Bulk Enqueue Documentation Inconsistent with API

### ISSUE THREAD

**Issue by y4n9squared** [rq/rq#1680]
In the documentation for [Bulk Job Enqueuing](https://python-rq.org/docs/#bulk-job-enqueueing), it states that

> Queue.prepare_data accepts all arguments that Queue.parse_args does EXCEPT for depends_on, which is not supported at this time, so dependencies will be up to you to setup.

This does not appear to be the case as `Queue.parse_args` accepts arguments for `on_success` and `on_failure` callbacks added in 1.9.0 but `Queue.prepare_data` does not.

https://github.com/rq/rq/blob/145884fcd5a016ee353da9ce1a586044bf058f45/rq/queue.py#L413-L425

It would be nice if this could get added (and subsequently plumbed through to `enqueue_many`) so that bulk job creation and single job creation have feature parity.

**Comment by selwin** [comment]
Yeah, `on_success` and `on_failure` were both added after `prepare_data()`. Do you mind opening a PR for this?

**Comment by y4n9squared** [comment]
@selwin I've opened a PR with the changes.

Noticed existing flake8 checks run in Github Actions are flagging violations but workflow is succeeding because the command still returns zero exit code. Please advise on how to properly run linters and/or if tests are needed.

**Comment by selwin** [comment]
Can we run flake8 only against newly added/modified lines?

**Comment by selwin** [comment]
@y4n9squared do you mind modifying the Github Actions workflow along with your PR such that flake8 flags violations, but are run only against modified lines? This way we can ensure that incoming changes are always flake8 compliant.

**Comment by y4n9squared** [comment]
Don't mind at all, but I feel it would be better in a separate PR. There are only 15 lint violations in the actual source tree and 30 in the tests directory. I feel like a good PR can just fix these and remove `--exit-zero` from the `flake8` invocation so that all lints are gated and then the entire project can be lint-free going forward.

**Comment by selwin** [comment]
Agreed, thanks!
