### ISSUE TITLE
is there support for async Redis clients?

### ISSUE THREAD

**Issue by akabinds** [rq/rq#1684]
When I attempt to use a Redis client provided from `aioredis` or `redis.asyncio`, creating a `Worker` using this connection errors with the following:
```
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/.../code/.../venv/lib/python3.10/site-packages/rq/worker.py:232: RuntimeWarning: coroutine 'Redis.execute_command' was never awaited
  self.ip_address = [client['addr'] for client in connection.client_list() if client['name'] == self.name][0]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/.../code/.../src/glitchup/web/tests.py", line 4, in <module>
    worker = rq.Worker([redis_queue], connection=redis_conn)
  File "/home/.../code/.../venv/lib/python3.10/site-packages/rq/worker.py", line 232, in __init__
    self.ip_address = [client['addr'] for client in connection.client_list() if client['name'] == self.name][0]
TypeError: 'coroutine' object is not iterable
```

The thing that is stumbling me is that `Redis.execute_command` is never called anywhere by me. It seems like there is something internally that is missing. This is my first time using `rq` and I decided just to switch back to normal `redis.Redis` client. If this support isn't intended for this library, I would love to know that. Otherwise, it would be nice to see if this support is implemented.

**Comment by selwin** [comment]
We simply haven't gotten around to testing this using async Redis clients yet. This is not something I'm actively pursuing but I'd be happy to accept PRs for this.

**Comment by akabinds** [comment]
> We simply haven't gotten around to testing this using async Redis clients yet. This is not something I'm actively pursuing but I'd be happy to accept PRs for this.

Ok great! Thank you for the clarification.
