### ISSUE TITLE
Is it possible to configure the JobStatus.CANCELED state as a "failing" state for dependencies?

### ISSUE THREAD

**Issue by jtfidje** [rq/rq#1691]
We us RQ in such a way where canceled parents should _not_ lead to any dependents running / executing. Is this something that is possible to configure?

**Comment by selwin** [comment]
I think canceled jobs should not lead to dependents running or executing. Is this not the case? If it's not, then it's a bug that should be fixed.

**Comment by jtfidje** [comment]
Thank you for getting around to this so fast!
