### ISSUE TITLE
Finished jobs not queueing dependants

### ISSUE THREAD

**Issue by jtfidje** [rq/rq#1692]
In 1.11 I now have a bug where dependencies are not queued because the "parent" job is not considered finished when `queue.enqueue_dependents(job, pipeline=pipeline)` is called in `worker.handle_job_success`.

When `dependencies_are_met` are called on the dependants, `parent_job` is not passed and thus the check fails because the parent has not yet been set to `JobStatus.FINISHED`

Is this intended?

**Comment by selwin** [comment]
No, this is not intended. Let me check.

**Comment by selwin** [comment]
There's a test on job being enqueued when it's dependencies have finished here https://github.com/rq/rq/blob/5b95725dc4410634a658bda9aa59188eaeaf87ea/tests/test_dependencies.py#L39 so I don't think there's any issues here.

I'm closing this issue for now, please reopen if you can provide more details on how this fails for you.

**Comment by jtfidje** [comment]
Thanks. This was indeed an issue on my side that I must have overlooked.
Sorry for the inconvenience!
