### ISSUE TITLE
[Question] how do I run worker in my FastAPI docker project

### ISSUE THREAD

**Issue by utopictown** [rq/rq#1703]
i have tried
```
CMD rq worker && python3 main.py
```
wouldnt do it, it didnt connect to my redis

do i need to just create separate dockerfile for worker and connect to same redis?

edit:
tried to create separate dockerfile just to run worker but the worker need complete feature of the main app like db, config, etc. wouldnt it mean i need 2 container exactly same just to run the app and worker?

**Comment by odarbelaeze** [comment]
Hi @utopictown, you should probably use a separate docker container for your `rq workers`, and yes you can use the same image for your web application and worker.

**Comment by utopictown** [comment]
thanks for your reply, i ended up using supervisord inside docker, so i only need 1 container

**Comment by ashmantak** [comment]
@utopictown I have a similar requirement where i have a nano service inside a container and i want to run RQ workers inside the same container. Can you please share the codee here ??

**Comment by CatLava** [comment]
I'm having this same experience, any detail on how you did this? Need to run RQ workers that reference functions in my FastAPI docker app
