### ISSUE TITLE
Reading a job status can be inconsistent with the rest of the job

### ISSUE THREAD

**Issue by rggjan** [rq/rq#1706]
There is an issue where reading a job status can be inconsistent with the rest of the job
When a job is successful, it first updates the status of the job (including on redis):

https://github.com/rq/rq/blob/153d29cce74cf1143a5f6bbe2672e7fb55b9abfe/rq/worker.py#L1030

Then, in a second call, it updates the rest of the fields, especially the job result:

https://github.com/rq/rq/blob/153d29cce74cf1143a5f6bbe2672e7fb55b9abfe/rq/worker.py#L1033

After debugging an issue for half a week, we found that this can cause the following issue:

1. the worker updates the status of the job to “Finished”
2. a different process (on a different machine) reads the job status with “job.get_status”
3. the status is finished, so the code continues and calls “job.result”
4. This returns None, and so it seems the job returned a None result (even though it returned a different result, which has not yet landed on redis).
5. the worker calls job.save, only now is the result updated on redis

Preventing to set the status individually (before everything else) of the job (like the result) would avoid this issue.

The issue is especially likely to occur when the payload (eg the result) of the job is very large, causing step 5 to finish after step 3, even when starting before step 3.

**Comment by selwin** [comment]
Yeah, I think `worker.handle_job_success()` should accept `pipeline`as an argument so all these changes can be saved in a single pipeline.

**Comment by rggjan** [comment]
Actually, I just realized that the transactions are supposed to run in a `pipeline`:
https://github.com/rq/rq/blob/153d29cce74cf1143a5f6bbe2672e7fb55b9abfe/rq/worker.py#L1012

However, the issue is that `enqueue_dependents` doesn't call `multi` in all cases (which is required to make the `pipeline` work after the `watch`), as claimed by the comment: https://github.com/rq/rq/blob/153d29cce74cf1143a5f6bbe2672e7fb55b9abfe/rq/worker.py#L1018

This causes all calls to be executed immediately.

See here, where `enqueue_dependents` returns (https://github.com/rq/rq/blob/153d29cce74cf1143a5f6bbe2672e7fb55b9abfe/rq/queue.py#L630) before `multi` is called (https://github.com/rq/rq/blob/153d29cce74cf1143a5f6bbe2672e7fb55b9abfe/rq/queue.py#L645).

I think inside `worker.handle_job_success` it would need to check if `multi` was called or if it wasn't in the `enqueue_dependents` function, and then call it directly if necessary.

**Comment by selwin** [comment]
Do you mind making a PR for this?
