### ISSUE TITLE
rq worker logging is too chatty at INFO level

### ISSUE THREAD

**Issue by tonyc-blastpoint** [rq/rq#1717]
The log message [here](https://github.com/rq/rq/blob/master/rq/scheduler.py#L107) prints any time the rq worker checks the queue for new jobs.  Even with long intervals, this results in a lot of messages.  I don't want to bump up the log threshold, because other INFO messages like logging the pid of the process, printing when the scheduler stops, etc. are useful.  Would a PR to reduce this message to `DEBUG` level be welcome?

**Comment by selwin** [comment]
Yes, this log statement looks like it belongs to `DEBUG` level logging. Please open a PR for this.

**Comment by selwin** [comment]
Thanks!

**Comment by tonyc-blastpoint** [comment]
You beat me to it.  Thanks.
