### ISSUE TITLE
Job.fetch() doesn't work if the job is not yet enqueued in a queue.

### ISSUE THREAD

**Issue by AravindhKuppusamy** [rq/rq#1721]
The following code throws `NoSuchJobErrror`. 

```
from fakeredis import FakeStrictRedis
from rq import Queue
from rq.job import Job

from rq_demo.demo import count_words_at_url

redis_conn = FakeStrictRedis()
q = Queue(is_async=False, connection=redis_conn)

url = "http://nvie.com"
job = Job.create(func=count_words_at_url, args=(url,), connection=redis_conn)

# q.enqueue_job(job)

job = Job.fetch(job.id, connection=redis_conn)
print(job.result)
```

But when I add the job to the queue, `Job.fetch()` works fine. Why is that the case? Shouldn't it be independent of the queue? How to fetch the job when the job is not yet added to the queue?

**Comment by selwin** [comment]
Yeah `Job.create` should already persist the job in Redis such that it can be fetched. Have you tried using regular Redis connection rather than FakeRedis?

**Comment by selwin** [comment]
You must call `job.save()` before it gets saved to Redis. See https://github.com/rq/rq/blob/master/tests/test_job.py#L229
