### ISSUE TITLE
request() to api sometimes causes error: Moving job to FailedJobRegistry (work-horse terminated unexpectedly)

### ISSUE THREAD

**Issue by jwalway** [rq/rq#1723]
Hello,

I've implemented **redis** and a worker queue to process a function.   It's a large function that calls other functions.  One of the functions includes a **request()** for product information from the countdown api server (used for ebay).   I'm using **Python 3.9**.

**Not every time, but perhaps every ten or twenty requests() I get the following error:**
_"Killed horse pid 10
2022-10-27T20:22:31.356467+00:00 app[worker.1]: 20:22:31 Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned None)"_

This error happens both on my **local machine** (ubuntu 22.04) and on the **heroku.com** server.  

I have it narrowed down to requests to the **countdown api**. 

Note, the function I delegate to a redis task works fine when run without redis. 

Does anyone have any ideas about this?

Thanks!
...John

**Comment by jwalway** [comment]
Addendum ... I tried forking the function instead of using redis to run it, and it works fine on a fork here on my local ubuntu machine.   So, the child process has no issues without redis.    I can't do that on the heroku server, as I assume they won't allow me to spawn processes like that.

**Comment by selwin** [comment]
Hey there, that log message appears when a horse gets killed. This could be caused by two things:
1. Horse exceeds timeout
2. The main worker receives `SIGINT` or `SIGTERM` (which could be sent manually, or also by Heroku).

**Comment by kingkong-cmd** [comment]
> Addendum ... I tried forking the function instead of using redis to run it, and it works fine on a fork here on my local ubuntu machine. So, the child process has no issues without redis. I can't do that on the heroku server, as I assume they won't allow me to spawn processes like that.

Hi @jwalway ,

I am having the same problem. Memory usage seems fine, so I can't figure out why Heroku is killing my worker job. Did you ever figure this out?
