### ISSUE TITLE
Job worker_name attribute returns None

### ISSUE THREAD

**Issue by eswolinsky3241** [rq/rq#1731]
I am creating a job locally and then starting a worker on another machine using the CLI. I am passing a name to the worker by using the --name flag. However, when I then enqueue a job and inspect the job object, the worker_name is None.

**Enqueue job code:**
`>>> q = Queue(random_id, connection=Redis())`
`>>> job = q.enqueue(run_script, script)`

**Worker command**
`rq worker --name ${HOSTNAME} --url redis://redis --burst random_id`

**When Job starts, worker name can be seen in redis**
![image](https://user-images.githubusercontent.com/58117461/202286230-17e104ff-af6e-4833-b83d-a49e14295465.png)

**However, worker_name on job object is None. I've confirmed that the job is still running when I try to access it**
`>>> print(job.worker_name)`
`None`

Expected behavior would be for the name passed to the --name flag on my worker process to be saved in the worker_name attribute of my job. I want to use this for debugging code and saving logs.

**Comment by selwin** [comment]
You'll need to refetch the job from Redis since `job.worker_name` is set by the worker process in the background. I'd also accept a PR that changes the worker name to `name (uid)` if `--name` flag is set.

**Comment by eswolinsky3241** [comment]
That makes sense, thanks.
