### ISSUE TITLE
Add `at_front` to enqueue_at

### ISSUE THREAD

**Issue by gabriels1234** [rq/rq#1740]
Hi @selwin,

I noticed that you have omitted the at_front argument from enqueue_at. There are cases where you may only have one worker and have 40 tasks that take a total of about 15 minutes to complete, but you also have other tasks that need to be run more frequently (e.g. every 10 minutes). In these cases, it would be helpful to have the option to specify that the task should be placed at the front of the queue when it is enqueued with enqueue_at.

see here:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/96071233/208152648-4061bee8-195d-4623-943a-b981f92d2c35.png">

I understand that there are currently some differences and limitations between the way enqueue and enqueue_at work. However, it may be possible to implement the at_front option at a low level for enqueue_at, and this could also be ported to rq-scheduler. While this is just a suggestion for an enhancement, I think it would be really useful to have.

**Comment by selwin** [comment]
Adding `at_front` option is a good idea and shouldn't be too hard to do. Mind opening a PR for this? :)

**Comment by gabriels1234** [comment]
@selwin I'd love to! And to keep things in-sync, would also submit PR to RQ-Scheduler.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1743
