### ISSUE TITLE
on_success and on_failure not working

### ISSUE THREAD

**Issue by bsdis** [rq/rq#1744]
I want to use on_success` like this:

```
            self.q.enqueue(
                analysis_handler, 
                args=(filename,),
                on_success=frame_analysis_success,
                on_failure=frame_analysis_failure
            )
```

However, when i try that, all my jobs fails with `Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 256)`.
If i remove `on_success` and `on_failure` to have just this:

```
            self.q.enqueue(
                analysis_handler, 
                args=(filename,)
            )
```
then everything works as expected. My success and failure handlers are defined as:
```
def frame_analysis_success(job, connection, result, *args, **kwargs):
    print('Frame success!!!')

def frame_analysis_failure(job, connection, result, *args, **kwargs):
    print('Frame failure!!!')
```

What am I doing wrong here ?
Or is this posibly a bug?

**Comment by art-egorov** [comment]
Hi! I'm not a developer of this project, but I'm exploring it as well)
It can be because for failure you're using wrong arguments:
It should be like that:
def report_failure(job, connection, type, value, traceback):
    pass

**Comment by selwin** [comment]
Hey there you can look at how callbacks are implemented in the test case here. https://github.com/rq/rq/blob/62acd56c917137e8096d3f73514364c07994d9e4/tests/test_callbacks.py#L62
