### ISSUE TITLE
Drop 3.6 support

### ISSUE THREAD

**Issue by ccrvlh** [rq/rq#1778]
Python version 3.6 was released 6 years ago and has EOL 1 year ago with no further security support. The next minor release `1.13` could be a good opportunity to do this since 1.12 was just released.

**Comment by cluck** [comment]
Will Python 3.6 syntax compatiblity be kept? There is continued support for Python 3.6 by third-parties like Red Hat for many years to come.

**Comment by lowercase00** [comment]
I don't imagine rq will support (any) old Python EOL versions for many years to come. This would (1) not allow to use new Python features that may be relevant or (2) mean a lot of effort to back-port changes.

IMHO the best policy would be to always support the Python versions that are currently receiving support (3.7 - 3.11 now).

We are talking about a project that is basically maintained by a single person @selwin, with sporadic community help. The comparison to RedHat (or any corporation-backed project) is not really fair.

**Comment by selwin** [comment]
I'm quite ok with continuing to support EOL versions unless:
1. They start to require a lot of effort to maintain (I realize `a lot` is a relative term :))
2. It prevents us from using a new feature. For example dropping Python 3.5 allows us to use type hints

So we'll try to support older versions if possible, but I'm giving no guarantees as to when we'll stop supporting versions that are already EOL.
