### ISSUE TITLE
Way to check if a worker is `with_scheduler`

### ISSUE THREAD

**Issue by cunla** [rq/rq#1783]
Currently `with_scheduler` is passed only in `work(...)`, so when querying workers, there is no way to tell whether a worker has scheduler or not.

Proposed solution:
The workers that have scheduler should be stored in redis (eg, in a separate key, like `REDIS_WORKER_KEYS`).
And then when querying workers (using `Worker.all()` or `Worker.find_by_key(..)` it should instantiate the Worker class with a `with_scheduler` param.

**Comment by lowercase00** [comment]
Makes sense. Wondering if we should use the worker metadata on `rq:worker:<worker_name>` and instantiate the worker with more information. Perhaps instead of having a separate key, we could just add a `with_scheduler` key to the worker hash, and query that

**Comment by cunla** [comment]
Even better.. can you point me where is the worker hash? I can work on this ticket this weekend.
(I need it for Django-do-scheduler)

**Comment by lowercase00** [comment]
This happens in quite a few places, the logic is: first the workers registers it's birth (`register_birth()`), which the bulk of the hash information, and then some random methods are called while it works to enrich the information on the existing hash eg. `current_job_working_time`, `successful_job_count` etc.

This is a good start:

https://github.com/rq/rq/blob/436250d36ba5d90a4979fe919c5d902c57223a35/rq/worker.py#L338-L371

And if you search for `hset` or `hmset` on the worker class you should also see some more information being saved.
