### ISSUE TITLE
Getting exception on rq 1.13.0: Restoring job causes `KeyError` when `result_type` is `None`.

### ISSUE THREAD

**Issue by cunla** [rq/rq#1825]
When running some tests, seams to be related to missing key on payload (change on #1801 )

> Error
> Traceback (most recent call last):
>   File "/Users/style/PycharmProjects/django-rq-scheduler/scheduler/tests.py", line 838, in test_check_rescheduled_after_execution
>     queue.run_sync(entry)
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/queue.py", line 1046, in run_sync
>     job.success_callback(job, self.connection, job.return_value())  # type: ignore
>                                                ^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/job.py", line 757, in return_value
>     self._cached_result = self.latest_result()
>                           ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/job.py", line 820, in latest_result
>     return Result.fetch_latest(self, serializer=self.serializer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/results.py", line 155, in fetch_latest
>     return cls.restore(job.id, result_id.decode(), payload, connection=job.connection, serializer=serializer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/results.py", line 125, in restore
>     Result.Type(int(payload['type'])),
>                     ~~~~~~~^^^^^^^^
> KeyError: 'type'

**Comment by lowercase00** [comment]
@cunla do you have a minimal snippet to reproduce this please?

**Comment by cunla** [comment]
```
        job = job_instance(self.JobClass, scheduled_time=timezone.now() + timedelta(seconds=1))
        queue = job.get_rqueue()
        first_run_id = job.job_id
        entry = queue.fetch_job(first_run_id)
        queue.run_sync(entry)
        job.refresh_from_db()
        self.assertTrue(job.is_scheduled())
        self.assertNotEquals(job.job_id, first_run_id)
```

**Comment by lowercase00** [comment]
@cunla I don't know these methods `get_rqueue` `refresh_from_db`, `job_instance`. It's very hard to find (and solve) problems that way. My suggestion to adopt a StackOverflow-like approach where the issues come with more detailed information and instructions on how to reproduce problems.

**Comment by cunla** [comment]
Well, writing code to reproduce the issue is difficult since it is not consistent, though, I can say now that it happens sometimes when the job is executed by the same process that scheduled it, so maybe it has to do with some cached value.

However, identifying the problem, in this case, is quite easy. I pinpointed the change that caused it and the stack trace.

[Notice most of the method](https://github.com/rq/rq/blob/master/rq/results.py#L114-L131) has `payload.get('return_value')`, `payload.get('exc_string')`, followed by checks if None, but this particular value does not.

A fix would be something like:
```
    @classmethod
    def restore(cls, job_id: str, result_id: str, payload: dict, connection: Redis, serializer=None) -> 'Result':
        ...
        exc_string = payload.get('exc_string')
        if exc_string:
            exc_string = zlib.decompress(b64decode(exc_string)).decode()

        result_type = payload.get('type')
        if result_type:
            result_type = Result.Type(int(result_type))
        return Result(
            job_id,
            result_type,
            connection=connection,
            id=result_id,
            created_at=created_at,
            return_value=return_value,
            exc_string=exc_string,
        )
```

**Comment by lowercase00** [comment]
I guess the important part about understanding the issue is understanding why it happens in the first place - I'm always in favor of having a safe guard (`None` checks) in place, but this wasn't designed to be `None` at all - the `Result` object expects a `Type` (at least this is not marked as `Optional[Type] = None`, so I'm not sure if the issue is not having the `result_type` or maybe the `Result` object should allow for `Type = None`. @selwin worked on this, I'll leave this here.


PS:  As a suggestion, a perhaps slightly better and more helpful issue would be something like (just an example):

> Restoring job causes `KeyError` when `result_type` is `None`.

And then a good follow up question would be: why is the `result_type` of a finished job `None`?

**Comment by cunla** [comment]
Updated issue title

**Comment by selwin** [comment]
@cunla can you confirm that this error is not present on 1.12?

@lowercase00 is right that Result is designed to always have a type associated with it.

**Comment by cunla** [comment]
Confirmed. 

It happened the day I updated to 1.13.0 - this is the first time I have encountered it, and I can't replicate it when downgrading to 1.12.0.

My findings so far:
- I am not able to replicate it **constantly** even on 1.13.0, it happens sporadically (~1/4 runs). 
- It happens only when trying `run_sync` from the process queuing the job.

**Comment by selwin** [comment]
Ok, I'll look into it.

**Comment by selwin** [comment]
```
> Traceback (most recent call last):
>   File "/Users/style/PycharmProjects/django-rq-scheduler/scheduler/tests.py", line 838, in test_check_rescheduled_after_execution
>     queue.run_sync(entry)
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/queue.py", line 1046, in run_sync
>     job.success_callback(job, self.connection, job.return_value())  # type: ignore
>                                                ^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/job.py", line 757, in return_value
>     self._cached_result = self.latest_result()
>                           ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/job.py", line 820, in latest_result
>     return Result.fetch_latest(self, serializer=self.serializer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/results.py", line 155, in fetch_latest
>     return cls.restore(job.id, result_id.decode(), payload, connection=job.connection, serializer=serializer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/style/PycharmProjects/django-rq-scheduler/.venv/lib/python3.11/site-packages/rq/results.py", line 125, in restore
>     Result.Type(int(payload['type'])),
>                     ~~~~~~~^^^^^^^^
> KeyError: 'type'
```

@cunla are you able to inspect what the value of `payload` is in the traceback?

**Comment by cunla** [comment]
> @cunla are you able to inspect what the value of `payload` is in the traceback?

empty dictionary.

Maybe you prefer to put a check in `fetch_latest()` to see whether the payload is empty. 

I can't make sense of it. The only place where there is `xadd(..)` uses `serialize()` (which sets a value for `type`) --> Still trying to figure out how it can happen.

**Comment by selwin** [comment]
Yeah, `fetch_latest()` also checks whether Redis returns any value [here](https://github.com/rq/rq/blob/42ac7d4150951b5f5fba8be11573920c1e6f6e69/rq/results.py#L151). Something weird is going on.

**Comment by cunla** [comment]
It does not happen anymore, though I still can't explain why it did.
Anyway, I am closing this.
