### ISSUE TITLE
Unexpected behavior when using an existing job ID for new jobs

### ISSUE THREAD

**Issue by amks1** [rq/rq#1826]
If you try to save a new job with an explicitly specified `job_id`, and it is one that you've used just previously, initially it seems like it has worked.

But the `args` and `kwargs` of the new job will not get set, it will have the same ones as the previous job. You can queue the new job and it will run, but because the function arguments are different it will lead to unexpected behavior.

It would be nice to have an exception or at least a warning to stop someone from attempting this.

**Comment by amks1** [comment]
Aah. I just saw the other open issue #1701   mentioning the same problem.. Sorry for not searching before posting.

**Comment by lowercase00** [comment]
Yes, was just going to link those two issues, thanks for doing that and closing it.
Feel free to add any additional information you feel might be relevant on that issue as well.
