### ISSUE TITLE
Version 1.13.0 (almost) breaks rq-scheduler

### ISSUE THREAD

**Issue by ronlut** [rq/rq#1834]
rq-scheduler [imports](https://github.com/rq/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L15) `rq.compat` which was removed in #1761.
Somehow, pypi's rq version 1.13.0 still contains that `compat` folder, hence it doesn't break rq-scheduler. But it will. (BTW, worth checking why it's still there).
I am not sure rq-scheduler is maintained, but it says it is maintained by you @selwin so raising it here.

A potential PR to solve that: https://github.com/rq/rq-scheduler/pull/284

**Comment by ronlut** [comment]
Thanks for merging it, is it possible to deploy the new version to pypi as well?
Thanks @selwin!

**Comment by lowercase00** [comment]
@ronlut I guess you're talking about `rq-scheduler` right? Can we close this and have a new issue over there?

**Comment by selwin** [comment]
@ronlut I’ll find some time to do it this weekend

**Comment by ronlut** [comment]
@lowercase00 not really in my local env, try to install rq with pypi in a new venv and go to `site_packages/rq` in your venv and you'll find it there
