### ISSUE TITLE
[Scheduler] Connection pool class not used by scheduler to instantiate new connections

### ISSUE THREAD

**Issue by tchapi** [rq/rq#1879]
Hi

First of all thanks for the great work on this project 👍🏼 

While working with RQ in our code, we noticed that we could not make the RQ scheduler (`rq worker --with-scheduler`)  work correctly, as it would not use our connection the way we intended it to be used (_with some custom behavior like automatically reconnecting after secret rotation for instance_).

In the [scheduler code](https://github.com/rq/rq/blob/master/rq/scheduler.py#L57), you're using `self._connection_class = connection.__class__` which is bypassing any custom connection class we might want to use by explicitly using the _connection instance_ class name to recreate the connection (ie, `Redis`).

In the next line, the code is retrieving the `connection_class = connection.connection_pool.connection_class` (which is indeed our custom class), but does not use it to instantiate the connection. Is this intended?

aka. Is there any reason not to do this?

```python
self._connection_class = connection.connection_pool.connection_class
```

Happy to provide more details if needed
Thanks a lot for your answer!

**Comment by selwin** [comment]
Please make a PR for this :) 

`self._connection_class = connection.connection_pool.connection_class`

**Comment by tchapi** [comment]
Done in https://github.com/rq/rq/pull/1885 (with a slightly different approach)

**Comment by tchapi** [comment]
Fixed in latest release
