### ISSUE TITLE
Allow on_success and on_failure be referenced using string reference

### ISSUE THREAD

**Issue by Amaimersion** [rq/rq#1891]
RQ allows to refer to the job function using string reference, for example:

```python
q.enqueue(
    f="my_package.my_module.my_func"
)
```

I expected that `on_success` and `on_failure` can be used in the same way:

```python
q.enqueue(
    f="packageA.module.func",
    on_success="packageB.module.funcA",
    on_failure="packageB.module.funcB"
)
```

But I got this error: `on_success callback must be a function`. 

And then I ended up with placing these callback functions in the same module where `enqueue` code resides:

```python
q.enqueue(
    f="packageA.module.func",
    on_success=funcA,
    on_failure=funcB
)
```

But it feels that referring callbacks using string reference is a more right way because I want these functions to be placed inside worker module, and I do not have access to the worker module during enqueue call because it happens from separate project. That's the whole purpose why `f` can be string reference.

**Comment by selwin** [comment]
PR welcome :)
