### ISSUE TITLE
[v1.14.0] TypeError: __init__() got an unexpected keyword argument 'ssl'

### ISSUE THREAD

**Issue by gg718** [rq/rq#1892]
Experiencing the follow error using the newly released v1.14.0:

```
11:03:52 Worker rq:worker:50d9ed1aa0a7f782ffc682847b5b89dd started with PID 45, version 1.14.0
11:03:52 Subscribing to channel rq:pubsub:50d9ed1aa0a7f782ffc682847b5b89dd
11:03:52 *** Listening on default...
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 1435, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/bin/ltp-worker", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.9/site-packages/ltp/worker/__main__.py", line 8, in main
    Worker(
  File "/venv/lib/python3.9/site-packages/rq/worker.py", line 385, in work
    self._start_scheduler(burst, logging_level, date_format, log_format)
  File "/venv/lib/python3.9/site-packages/rq/worker.py", line 465, in _start_scheduler
    self.scheduler.acquire_locks()
  File "/venv/lib/python3.9/site-packages/rq/scheduler.py", line 101, in acquire_locks
    if self.connection.set(self.get_locking_key(name), pid, nx=True, ex=self.interval + 60):
  File "/venv/lib/python3.9/site-packages/redis/commands/core.py", line 2302, in set
    return self.execute_command("SET", *pieces, **options)
  File "/venv/lib/python3.9/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 1437, in get_connection
    connection = self.make_connection()
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 1477, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 1085, in __init__
    super().__init__(**kwargs)
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 941, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'
```

Content of `__main__.py`:

```python
import os

from redis import Redis
from rq.worker import Worker


if __name__ == "__main__":
    Worker(
        ("default",),
        connection=Redis.from_url(
            os.environ["REDIS_URL"],
        ),
    ).work(with_scheduler=True)
```

**Comment by selwin** [comment]
This could be related to changes in [this PR](https://github.com/rq/rq/pull/1885) that changes the way Redis connection is parsed. Mind telling us the value of `os.environ["REDIS_URL"]`?

cc @tchapi

**Comment by tchapi** [comment]
👋🏼 
I think that maybe [these transformations](https://github.com/tchapi/rq/blob/5bf8239ea2a8378a6d0e344fcf80aaa07bcb37f3/rq/connections.py#L126-L135) are maybe now unnecessary since we're not using the _connection pool kwargs_ as _connection kwargs_, so it _may_ be the culprit, what do you think?

```python
if issubclass(connection_pool_class, SSLConnection):
    connection_kwargs['ssl'] = True
if issubclass(connection_pool_class, UnixDomainSocketConnection):
    # The connection keyword arguments are obtained from
    # `UnixDomainSocketConnection`, which expects `path`, but passed to
    # `redis.client.Redis`, which expects `unix_socket_path`, renaming
    # the key is necessary.
    # `path` is not left in the dictionary as that keyword argument is
    # not expected by `redis.client.Redis` and would raise an exception.
    connection_kwargs['unix_socket_path'] = connection_kwargs.pop('path')
```

**Comment by selwin** [comment]
Worth a try, the thing is I'm not sure because I've always used bog standard, non SSL Redis URI so I'm unable to test it myself.

Mind opening a PR and see if it fixes @gg718 's problem? I wonder if we can also write a test for this.

**Comment by tchapi** [comment]
We definitely need a test for SSL / domain socket connections, will try asap!

**Comment by tchapi** [comment]
FYI @gg718 the fix made it to `master` if you want to try

**Comment by selwin** [comment]
I'll asume this is fixed in https://github.com/rq/rq/pull/1894 . Please reopen if this is still a problem.

**Comment by gg718** [comment]
Fixed - thank you!

**Comment by biuti** [comment]
I'm not able to create a connection to AWS encrypted elasticache redis.
The connection works thru Redis with this parameters:
`REDIS_HOST = 'xxx.cache.amazonaws.com'      # Default: 'localhost'`
`REDIS_PORT = 6379            # Default: 6379`
`REDIS_SSL = True             # Default: False`
`REDIS_SSL_CERT_REQS = None   # Default: None`
This is using a non TLS scheme.

When I try to connect using command in docker-compose file:
`rqworker --with-scheduler --name worker --config local_settings`
the SSL parameter triggers a TLS connection, that gives the error:
`  File "/home/sid/.local/lib/python3.8/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: unknown subcommand 'list'. Try CLIENT HELP.`
With SSL = False the Redis server refuses the connection:
`'cannot connect to Redis: Connection closed by server.'`

Unless there is already a solution for this case, I think it could be useful to add a REDIS_SCHEME parameter, with values 'tcp' and 'tls', default value REDIS_SSL ? 'tls' : 'tcp'
