### ISSUE TITLE
ImportError: cannot import name 'use connection' from 'rq' (/usr/local/lib/python3.8/site-packages/rq/__init__.py)

### ISSUE THREAD

**Issue by julianojj** [rq/rq#1896]
After v1.14 new release, django-rq requires version >= 2.8.0 but breaks other versions.
In test based on docker container, using rq version == 1.4.0, django-rq==2.3.2 and django==3.1, don't should affected for new release.

**Comment by JayaAnim** [comment]
I dont have rq explicitely installed in my requirements.txt and recently my code broke from use connection being depreciated. I currently use django-rq==2.4.1 and django==3.1.7. Have you found a workaround for the bug?

**Comment by parthvnp** [comment]
@julianojj @JayaAnim Can you provide some relevant code snippets? Might be able to recommend some possible approaches.

**Comment by selwin** [comment]
Django-RQ 2.8.1 explicitly requires RQ>= 1.14 so this shouldn't happen again.
