### ISSUE TITLE
Function as_text no longer returns None

### ISSUE THREAD

**Issue by jlopespt** [rq/rq#1900]
https://github.com/rq/rq/blob/5f883c6e1cb51d99fcc17fe45e80c0a03848c80f/rq/utils.py#L41

With version 1.14 the check for a NoneType is no longer done, and the function doesn't return None as it is stated on the description. Did not found any reference on the changelog.
This is causing a ValueError

This is the code removed from version 1.13:
https://github.com/rq/rq/blob/42ac7d4150951b5f5fba8be11573920c1e6f6e69/rq/utils.py#L153-L154

**Comment by selwin** [comment]
Yeah, version 1.14 included a bunch of internal refactors, mostly to make the codebase more type friendly.

**Comment by jlopespt** [comment]
You probably didn't understood the issue, the question is not cosmetic.
Excluding the None evaluation returns ValueError: Unknown type <class 'NoneType'>
It is not very logic to exclude it

**Comment by bnomis** [comment]
I have run into this issue too.

Worker.all(queue=queue), calls find_by_key(), which calls refresh(), the hmget() in refresh() returns None for queues.

as_text() is called with the None value as an argument (line 1041 in worker.py tag 1.14.1)

as_text() raises an exception

**Comment by bnomis** [comment]
Looks like this was fixed in https://github.com/rq/rq/issues/1912
