### ISSUE TITLE
Work-horse terminated unexpectedly; waitpid returned 132 (signal 4);

### ISSUE THREAD

**Issue by dvelaren** [rq/rq#1901]
Hello, I'm having problems using redis queue in my Ubuntu Server 22.04 (running AWS with 16GB of Ram and 4 CPU cores).

I have a web application using docker compose with Python 3.10, Redis 7.0.11, Redis Queue 1.14.0.

In my application I send a task to redis queue that uses EvalML library to find the best ML model for a set of variables.

The webapp project works correctly in WSL 2 (Windows 11), MacOS Monterrey. 

I think there is a bug with Ubuntu server and RQ

**Comment by selwin** [comment]
Signal 4 is SIGILL, that means your job was terminated by the OS.

https://www-uxsup.csx.cam.ac.uk/courses/moved.Building/signals.pdf
