### ISSUE TITLE
cannot import use_connection (depreciated method)

### ISSUE THREAD

**Issue by JayaAnim** [rq/rq#1904]
I currently use django-rq==2.4.1 and django==3.1.7. Recently my rqworkers fail because use_connection method cannot be imported from rq. I do not have rq explicitly defined in my requirements.txt. 

Do I need to add a specific version of rq to my requirements.txt to fix this new bug, or do I need to use a new version of django-rq?

**Comment by selwin** [comment]
Yes, you'll need to use a new version of Django-RQ.
