### ISSUE TITLE
worker information missing after finish a job

### ISSUE THREAD

**Issue by beanyoung** [rq/rq#191]
before run job, the information of worker is 

```
1) "birth"
2) "1363360320.311374"
3) "queues"
4) "default"
5) "state"
6) "busy"
```

while finish job, the information of worker is 

```
1) "state"
2) "idle"
```

maybe the bug is line [328 to 330](https://github.com/nvie/rq/blob/7c63b72c9982405f38152fa5b9708af3d3482616/rq/worker.py#L328-L330)

**Comment by lowercase00** [comment]
Closing this (too many versions were released after this was opened), feel free to reopen if there are issues.
