### ISSUE TITLE
Add new queue to worker without restarting script.

### ISSUE THREAD

**Issue by anubhabdaserrr** [rq/rq#1910]
Is it possible to add a queue automatically while the Redis worker process is running; without restarting the script?

```python
w = Worker(redis_queue_list, connection=connection)
w.work()
```

My use case involves modifying `redis_queue_list` by appending new queues based on incoming requests. How do I go about this?

**Comment by selwin** [comment]
Not at the moment, you'll have to re-run the worker script with different queue arguments.

**Comment by anubhabdaserrr** [comment]
Thanks for clarifying!
