### ISSUE TITLE
[Bug] Breaking change in `as_text()` breaks `Worker.refresh()` at least

### ISSUE THREAD

**Issue by tchapi** [rq/rq#1912]
Hi 👋🏼 

Since [this commit](https://github.com/tchapi/rq/commit/36f5c88ca21ff30fb799e7d10b2f7b9bef4e585a#diff-131ce6502fe39f72674a7d588e39152a3d8eea79d8ca3483b951f6957d0ce8f1L151-R54) where `as_text()` now raises when the parameter is None, some stuff break, for instance `Worker.refresh()`.

This is the culprit:

```diff
-    if v is None:
-        return None
-    elif isinstance(v, bytes):
+    if isinstance(v, bytes):
```

We have places where we still call `as_text()` on possibly `None` values, like [here](https://github.com/rq/rq/blob/master/rq/worker.py#L1041) in `refresh()`:

```python
queues = as_text(queues)
self.hostname = as_text(hostname)
self.ip_address = as_text(ip_address)
self.pid = int(pid) if pid else None
self.version = as_text(version)
self.python_version = as_text(python_version)
self._state = as_text(state or '?')
self._job_id = job_id or None
```

All this above is breaking since we have workers without a lot of these parameters (shutdowned workers for instance)

I can make a PR quickly if needed — what would be the best way to address and fix? Do you prefer re-allowing `None` values in `as_text()` or fixing each line with a `as_text(x) if x else None` ?

Thanks a lot

**Comment by tchapi** [comment]
@selwin did you have a chance to have a look by any chance?

**Comment by selwin** [comment]
Sorry I missed this. Would prefer going the ‘as_text(x) if x else None’ route. as_text() should only receive something that we can convert to text.
