### ISSUE TITLE
Document `on_stopped` callback and job dependencies in `queue.enqueue_many()`

### ISSUE THREAD

**Issue by selwin** [rq/rq#1921]
@eswolinsky3241 I just realized that neither https://github.com/rq/rq/pull/1897/files nor https://github.com/rq/rq/pull/1909 contains docs explaining the features.

Do you mind opening a PR to quickly document the two new parameters?

**Comment by eswolinsky3241** [comment]
@selwin Will this work? https://github.com/rq/rq/pull/1922

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1922
