### ISSUE TITLE
Optional connection parameter with forced class

### ISSUE THREAD

**Issue by kurskontrolle** [rq/rq#1929]
The forced class for the connection parameter makes it impossible to work with anything else than Redis. Walrus (https://github.com/coleifer/walrus/) is a good and well-known alternative, but it cannot be used directly, since there is no casting in Python. Using a Walrus connection results in:
```
  File "/opt/venv/lib/python3.11/site-packages/rq/connections.py", line 117, in resolve_connection
    raise NoRedisConnectionException('Could not resolve a Redis connection')
 rq.connections.NoRedisConnectionException: Could not resolve a Redis connection
```

An easy solution would be to drop this requirement in the initializer or allow others as well.

Workaround:
```
from walrus import Database as Walrus_Redis
class Redis(Walrus_Redis):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```
Then use above "Redis" class to initialize the connection and pass it to RQ.

**Comment by selwin** [comment]
I'm not sure I follow. The `Redis` return type of `resolve_connection` is just a type hint that doesn't get enforced by Python so you should still be able to use anything that mimics `redis-py`'s API. In fact, people sometimes use fakeredis for testing.

I'm closing this for now, please reopen if needed.

**Comment by kurskontrolle** [comment]
@selwin the problem is that it is specifically asked for a Redis class in the initialisers:

`connection: Optional['Redis']`

You can ofc feed whatever object you want into this (cf what I do above), but it needs to be called Redis.

**Comment by selwin** [comment]
Yeah, but it’s only a type hint, so feeding Walrus or FakeRedis would
still work, as long as they implement methods used by RQ. If you’re
concerned about type warnings, you can probably silence it with # type:
ignore.
