### ISSUE TITLE
Can a job in Queue("one") `depends_on` a job from Queue("two")?

### ISSUE THREAD

**Issue by fpoms** [rq/rq#1936]
Does RQ support `depends_on` across queues? I can't seem to find it anywhere in the documentation.

```
q1 = Queue("one")
job_1 = q1.enqueue(dummy_job)

q2 = Queue("two")
job_2 = q2.enqueue(dummy_job, depends_on=job_1)
```

**Comment by selwin** [comment]
Technically it can, but both queues have to be in the same Redis DB.
