### ISSUE TITLE
issues with worker quitting

### ISSUE THREAD

**Issue by Miracles666** [rq/rq#1938]
Today, I encountered an issue where after restarting Redis, the tasks were no longer being listened to. So, I restarted the worker, but even after killing the process, one of the workers remained present in Redis. The worker's name is set as "**xxx.worker**" (manually configured). I tried using the "**send_shutdown_command**" to kill the worker, but it had no effect. Only when I used "redis-cli kill" on the key, it took effect. This problem tends to occur more frequently within Docker containers, to the point where I have to rebuild docker-compose multiple times to remove the previous worker.

![image](https://github.com/rq/rq/assets/40236845/28b8bea4-05e7-4773-8b60-a1ff2a70440d)

**Comment by Miracles666** [comment]
@selwin

**Comment by selwin** [comment]
Worker keys have TTL’s, so they if they are killed immediately (using kill -9) for example, their keys may not expire until a few minutes later. But they will eventually be cleaned up
