### ISSUE TITLE
 fatal rq error

### ISSUE THREAD

**Issue by Miracles666** [rq/rq#1996]
rq:version is  1.15.0

I encountered a fatal rq error.

I think it may be related to the number of my tasks. My redis stores hundreds of thousands of rq tasks.

Then the following error occurred during task execution:

redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop -writes-on-bgsave-error option). Please check the Redis logs for dException Exception ExceException in thread Thread-2:

and 

redis.exceptions.ConnectionError: Con00:56:45 Could not conne00:56:45 Could not connect to Redis instance: Redis is loading the dataset in memory R00:56:47 C00:56:48 Could not connect to Redis instance: Redis is loading the dataset in memory Retrying in 4 s00:56:52 C00:56:52 C00:500:500:56:52 Could not connect to Redis instance: Redis is loading the dataset in memo00:57:00 C00:57: 00 Could n00:57:00 Could not connect to Redis instance: Redis is loading the dataset in memory 00:57:16 C00:57:16 Could not connect to Redis instance: Redis is loading the dataset in memory Retrying in 32 s01: 14:33 C01:14:33 Could not01:14:33 Could not connect to Redis instance: Connection closed by server01:35:49 Worker rq:worke01:301:301:35:49 Worker rq:worker:xxx.xxx.xxx.xxx_subdomain_urlfinder_0 : found an unhandled exception, quitting...

What do I need to check now? , I have not encountered such an error before

**Comment by Miracles666** [comment]
My good brother, sorry to disturb you @selwin

**Comment by selwin** [comment]
Your Redis server is down because it ran out of disk space.

**Comment by Miracles666** [comment]
> Your Redis server is down because it ran out of disk space.

![image](https://github.com/rq/rq/assets/40236845/a5ba61ef-a1d2-4d6b-aaa0-516a710ab377)
It seems the disk is not full

**Comment by Miracles666** [comment]
@selwin
