### ISSUE TITLE
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:test) of pipeline caused error: MOVED 8713 mxxx.euw1.cache.amazonaws.com:6379

### ISSUE THREAD

**Issue by stephenhutch** [rq/rq#2004]
Was running a consumer (worker process) and producer locally with a local redis instance and everything was fine.

Then connected to a remote aws elasicache redis cluster and the following error arose:

    redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:test) of pipeline caused error: MOVED 8713 mxxx.euw1.cache.amazonaws.com:6379

Is this related to redis cluster - does the library not play well with redis cluster?

**Comment by selwin** [comment]
RQ should work with Redis clusters. Check your Elasticache setup.
