### ISSUE TITLE
Can we pass custom args to a callback (on_failure)

### ISSUE THREAD

**Issue by raphael-bresson** [rq/rq#2007]
Hi,
I submit some jobs to rq from a Flask app and senf info from those jobs to the client with socketio.

I would like to be able to emit the same way from the callbacks (on_failure, on_success) but I need to provide a room to emit to.
And I don't see how to pass the room ID to the callbacks, which list of arguments seems fixed.
It also seems that the callbacks have to be defined at the top level of my module, so no closure allowed ?

Could anyone help me ?

Thanks

**Comment by dams** [comment]
hi!
It's not possible to pass **directly** custom args to a callback, it receives a fixed set of things
`(job, connection, type, value, traceback):`

What we do is add an entry to the `job.meta` dictionary when creating the job, and in the callback, recover it via `job.meta["my_arg"]`

**Comment by raphael-bresson** [comment]
Ok thanks I'll use that trick :-)
