### ISSUE TITLE
Jobs being lost when killing workers

### ISSUE THREAD

**Issue by martyer** [rq/rq#2015]
When killing (cold shutdown) a worker that is processing a job that is configured with a retry, e.g.`Retry(max=3)`, I would expect the job to be moved to the `FailedJobRegistry` by another worker working on the same queue. But the job is simply lost, as soon as the now dead worker gets cleaned up.

Is this expected behaviour, or am I doing something wrong?

**Comment by selwin** [comment]
If you have another worker running, it will move the job to `FailedJobRegistry` after the job's execution timeout is over.

**Comment by martyer** [comment]
Hi @selwin,
Thank you for your answer. I have many other workers connected on the same Redis instance. But unfortunately, jobs of killed workers are not being moved to the `FailedJobRegistry`. Does a worker need to run on the same queue for it to detect orphaned jobs? If not, what could prevent another worker from detecting an orphaned job?

**Comment by anton-daneyko-ultramarin** [comment]
@martyer I think there's a timer and this "move" is done once in a while.
