### ISSUE TITLE
DeprecationWarning: datetime.datetime.utcnow()

### ISSUE THREAD

**Issue by superjcvd** [rq/rq#2044]
Hello

datetime.datetime.utcnow() will soon be deprecated and should be replaced by datetime.datetime.now(datetime.UTC)
(in utils.py lines 128 and 227)

I tried to create a PR but I'm not allowed to push my branch on this repo :)

Regards

**Comment by dewalujjwal** [comment]
@superjcvd  this issue is resolved

**Comment by riceyrice** [comment]
@dewalujjwal this fix was merged (to branch `master`) in March but is not in 1.16.2 which was released (from branch `v1`) in May? Is that intentional?
