### ISSUE TITLE
[feature] WorkerPool with different configuration for queues

### ISSUE THREAD

**Issue by ankush** [rq/rq#2090]
Right now we can provide fix list of queues for WorkerPool. 

So if I have two queues but I want dedicated set of workers for one of the queue then I need to run a separate pool. This reduces benefit we can get from shared memory in pool. 

Possible solution:
- Provide arguments for combination of queues+count.
- I am not sure what would be good CLI argument design for this

**Comment by ankush** [comment]
Potential CLI: `rq worker-pool --queue x,y,z:5 --queue a,b,c:2`

**Comment by ankush** [comment]
@selwin will you accept a PR for something like this?

**Comment by selwin** [comment]
@ankush sorry, I just saw this message. Sorry, but I don't think this will get into the RQ core. But if you want, we can rework or improve RQ's internal implementation to provide hooks that you may require so you can implement it more easily in a separate script or package.

I'm closing this issue for now, please reopen if you want to propose some changes to how `WorkerPool` is currently implemented.
