### ISSUE TITLE
Worker pool question

### ISSUE THREAD

**Issue by tsunamilx** [rq/rq#2098]
Hi

I need to run a bunch of tasks that basically run forever, and a web UI to start/stop/delete tasks. So I set up bunch of workers using [systemd method](https://python-rq.org/patterns/systemd/). It is working, but there is an issue: it uses a lot of memory.

Each worker process (no task is being run) uses ~50M memory, and once the task starts, it uses ~150M each. The thing is that most of the memory used from the task is actually from 3rd party libs (those are big libs like pandas, it uses ~50M memory by simply importing them), I think each worker process is independent so those libs are imported every time when it runs which will use all the memory really quickly if I start a lot of tasks

So the question is there a way to pre-import the those libs and have the libs shared in all worker processes?
I see a feature "Worker Pool" was introduced long time ago but still in beta, will it solve my problem, and is it stable?

Thanks.

**Comment by noahdavis319** [comment]
This is discussed in the documentation with an example of how to preload the libraries.

https://python-rq.org/docs/workers/#performance-notes

**Comment by wujian752** [comment]
The imported libs can't be shared between workers because workers run in different processes. 

The "Worker pool" only provides a way to manage workers so it doesn't help the memory problem.
