### ISSUE TITLE
How can i read data field stored in result fo redis?

### ISSUE THREAD

**Issue by GabsMarcelino** [rq/rq#2110]
Hey guys, can someone help me?

I would like to be able to read the data that was passed to the job
`queue.enqueue(company_consumer[0].handle_message, content)`

for some puprose to troubleshoot, i need to be able to read what was passed by `content` if needed, can someone help me? if you guys have any better solution, i would be grateful

![image](https://github.com/user-attachments/assets/5892994c-0ec0-4e69-8bb9-94c1deee113a)

**Comment by selwin** [comment]
It needs to be decompressed. https://github.com/rq/rq/blob/e80d4009ffc1d04d5a0bfa1a5d43d0f41d24dc9f/rq/job.py#L1029
