### ISSUE TITLE
RQ Worker Termination: Moving Job to FailedJobRegistry (signal 6) on RQ 1.16.2 with Amazon ElastiCache

### ISSUE THREAD

**Issue by shaharluftig-exp** [rq/rq#2139]
We are encountering an issue where RQ workers move jobs to the `FailedJobRegistry` due to unexpected terminations, with the following error message:
`Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned 134 (signal 6); )`

This issue occurs consistently in our production environment on Linux EC2 instances using Amazon ElastiCache and persists despite an upgrade to RQ version 1.16.2.

**Environment Details**:
- **RQ Version**: 1.16.2
- **Redis Backend**: Amazon ElastiCache (Redis version 6.2.6)
- **Production Environment**: 
  - EC2 instances running Linux
  - Redis managed by Amazon ElastiCache
  - Python processes running in Docker containers
- **Local Environment**:
  - Docker containers used for Redis
  - Worker processes run directly in Python, not within Docker
- **Python Version**: 3.11

**Error**:

`Moving job to FailedJobRegistry (Work-horse terminated unexpectedly; waitpid returned 134 (signal 6); )`

**Troubleshooting Steps Taken**:

1. **Local Recreation**: The issue did not reproduce in a local development environment, suggesting it may be specific to the production setup.
2. **Version Update**: Upgraded to RQ 1.16.2 to address any known bugs, but the issue persisted.
3. **Debug Logging**: Lowered the log level to DEBUG and added extensive logging around RQ logic, yet no additional logs are generated before the issue occurs, leaving us without indicators of the root cause.

**Expected Behavior**:
Workers should process jobs or fail gracefully without unexpected termination.

Any guidance on managing signal 6 terminations in this configuration, would be appreciated.

**Comment by selwin** [comment]
As far as I know, signal 6 is `SIGABRT` and is sent by the OS, so nothing we can do about the signal.

If you want provide a custom logic to catch this, you can provide an `on_failure` callback. https://python-rq.org/docs/#job-callbacks
