### ISSUE TITLE
Feature Request: Support for Custom Retry Intervals Per Job

### ISSUE THREAD

**Issue by imDarshanGK** [rq/rq#2164]
Current behavior: Currently, the retry intervals for failed jobs are set globally and cannot be customized per job.

Expected behavior: Allow users to set custom retry intervals for each job individually.

Steps to reproduce:

Enqueue a job with a specific retry interval using the Retry object.
Observe that the interval is applied globally and not on a per-job basis.

Thank you

**Comment by selwin** [comment]
You can already specify retry intervals on a per job basis. For example:

```python
queue.enqueue(my_job, retry=Retry(max=1, interval=5))  # Retried with 5 seconds interval
queue.enqueue(my_job, retry=Retry(max=1, interval=10))  # Retried with 5 seconds interval
```
