### ISSUE TITLE
Does RQ support connection pool?

### ISSUE THREAD

**Issue by josedesoto** [rq/rq#221]
Hi,

I am using rq library to connect with redis and it works fine. For example:

redis_conn = Redis(host='localhost',port=6379,password=None,db=0)
push_connection = push_connection(redis_conn)

But my app sometimes have many request to redis and I would like to avoid open and close connections all the time. I have thought to use connection pool, but not sure if it's supported. I have tried:

pool = redis.ConnectionPool(host='localhost', port=6379, db=0, max_connections=5)
redis_conn = redis.Redis(connection_pool=pool)
pool_conn = pool.get_connection('command_name')
push_connection = push_connection(pool_conn)

But does not work... is there a way to use pool connection or to prevent to open and close connections continuously?

In advance many thanks.

**Comment by lowercase00** [comment]
According to [this](https://github.com/redis/redis-py#connection-pools), pooling is being handled by RedisPy. Closing this.
