### ISSUE TITLE
Unable to run async job ... ImportError

### ISSUE THREAD

**Issue by elmarquez** [rq/rq#225]
I have a trivial application, based on your run_example.py, that I am unable to execute asynchronously. If I run this job with the Queue set to async=False, it succeeds. If it is set to async=True, or the default, it throws an ImportError exception.

I've tried this on two machines, one running the latest Debian and the other running Ubuntu 12.04 and get the same result on both. Both have Python 2.7.3, rq=0.3.8, python-redis=2.7.6, redis=2.2.12 installed.  I fear that I must be overlooking something incredibly stupid but I've tried this same example in a variety of ways, checked sys.path and so forth, and still can't get it to work.

I have two files in the same directory: runner.py and tasks.py

runner.py:

```
from tasks import count_words
from rq import Connection, Queue
import time

def main():
    q = Queue()
    t = q.enqueue(count_words,'http://shakespeare.mit.edu/hamlet/full.html')
    while t.return_value != None:
        print 'Waiting for result'
        time.sleep(5)
    print t.return_value

if __name__ == '__main__':
    with Connection():
        main()
```

tasks.py:

```
import urllib2

def count_words(url):
    f = urllib2.urlopen(url)
    data = f.read()
    return len(data)
```

The rqworker is running, sees the job and moves it to the failed queue with the following message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 410, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 355, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 127, in func
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named tasks
```

**Comment by mateocam** [comment]
@elmarquez I am having the same issue! where do I set the PYTHONPATH ?

**Comment by elmarquez** [comment]
@mateocam PYTHONPATH is an environment variable that you set before running your script, or you set as part of the host's default settings. This is description of how to get and set environment variables in a Linux/Mac environment:

https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps

This is a description of PYTHONPATH:

  https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH

Its been years since I've looked at rq. You probably need to set the PYTHONPATH to include the path to the folder where your script lives.
