### ISSUE TITLE
Scheduler: Support timeout argument

### ISSUE THREAD

**Issue by sylvinus** [rq/rq#232]
I may be wrong but I think there is no way currently of setting the timeout for scheduled tasks. Would be very useful to add again.

Thanks!

**Comment by inactivist** [comment]
Unless I'm misunderstanding something, this is available via the [`job_timeout`](http://python-rq.org/docs/#enqueueing-jobs) or [`timeout`](http://python-rq.org/docs/#enqueueing-jobs) parameter when enqueuing a job.
