### ISSUE TITLE
Feature request: pipelined enqueues and fetches

### ISSUE THREAD

**Issue by sylvinus** [rq/rq#241]
We often need to queue thousands of tasks, so we wrote a wrapper to queue them all in the same pipeline to get reasonable performance.

It looks like this (send_task() is basically a customized Queue.enqueue_call()) :

```
def send_tasks(task, params_list, **kwargs):

  pipeline = get_redis_connection().pipeline(transaction=False)
  kwargs["connection"] = pipeline

  jobs = [send_task(task, params, **kwargs) for params in params_list]

  pipeline.execute()

  return jobs
```

It is pretty simple and could be useful to others if it was bundled in some way in RQ for instance in an "Queue.enqueue_calls" method.

On the other hand, we also need to fetch the statuses of many jobs at once. In this case RQ could use a small refactor in Job.refresh() to split the hgetall() call from the parsing and unpickling. Here is the code we use as an example:

```
def get_tasks(tasks_ids):
  pipeline = get_redis_connection().pipeline(transaction=False)

  jobs = [Job(jobid, connection=get_redis_connection()) for jobid in tasks_ids]

  for job in jobs:
    pipeline.hgetall(job.key)

  values = pipeline.execute()

  for i, obj in enumerate(values):
    if len(obj) == 0:
      jobs[i] = None
    else:
      # TODO other used attributes
      jobs[i]._status = obj.get('status') if obj.get('status') else None

  return jobs
```

That's it, I hope it is helpful to others, would love to see this integrated in RQ in some way.

**Comment by jhorman** [comment]
Counter argument, against it not being a real problem in practice. I am also trying to queue thousands of jobs, but I am using a redis hosting provider with seemingly high latency between my data center and theirs. We are pipelining everything, which removes most of the trouble. `enqueue_many` would allow us to do this. Another option would be to pass `pipeline` into the delay call as a kwarg, though that is exposing probably too much detail.

I am thinking for now, of creating a new queue object on the fly pointing to a `pipeline` for `connection` but it scares me a bit in that there could be places that are expecting to get a synchronous response back.

**Comment by selwin** [comment]
Mind making a PR to propose an implementation? Bulk enqueue is something I'd like to have.
