### ISSUE TITLE
any to shutdown a worker without warm?

### ISSUE THREAD

**Issue by yishenggudou** [rq/rq#242]
I use supervisor to manage my rq worker
and my supervisor conf is like this

```
[program:rq-upload]
command=rqworker -H 10.182.63.61 -P /data/CDN_DATA_ANA/log/letvlog --name=10.180.153.80_re_upload_%(process_num)s log_upload_10.180.153.80
directory=/data/CDN_DATA_ANA/log/log
stopsignal=TERM
autorestart=true
autostart = true
startsecs = 5
process_name = rq_upload%(process_num)s
numprocs=2
user = root
redirect_stderr = true
stdout_logfile = /logs/rq-upload.log
```

But when I restart use  `supervisorctl -c /etc/supervisord.conf update re-upload:*`
It always tell me the worker name has used

**Comment by omidraha** [comment]
I have the same issue, when i stop `rqworker` from the docker-compose running command by `Ctrl+c` and want to start it again.


```
worker_1  |   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
worker_1  |     return ctx.invoke(self.callback, **ctx.params)
worker_1  |   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
worker_1  |     return callback(*args, **kwargs)
worker_1  |   File "/usr/local/lib/python2.7/dist-packages/rq/cli/cli.py", line 206, in worker
worker_1  |     w.work(burst=burst)
worker_1  |   File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 431, in work
worker_1  |     self.register_birth()
worker_1  |   File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 251, in register_birth
worker_1  |     raise ValueError(msg.format(self.name))
worker_1  | ValueError: There exists an active worker named u'5d36705967ac.22' already
```

**Comment by omidraha** [comment]
Any idea?

**Comment by ericpascual** [comment]
Same problem here.

**Comment by jbaiter** [comment]
Same problem here, I work around it by just issuing two `SIGINT` signals to the worker instead of leaving the killing of the process the supervisor process (`docker-compose` in my case). This makes the worker shutdown cleanly.

**Comment by italomaia** [comment]
docker-compose run worker-service
then CTRL+C
Works for me.

**Comment by nicbou** [comment]
I have the same problem, but I start rq as a background process, so italomaia's fix does not apply. Is there a way to work around this?

    rq worker $RQ_WORKER_NAME -u $REDIS_DB_URL &

**Comment by samuelcolvin** [comment]
yes, just send it a standard kill signal.

    ps -aux | grep "rq worker"

then take the process id (the second number) and execute

    kill <proc id>
