### ISSUE TITLE
Why use pickle over json

### ISSUE THREAD

**Issue by penggu89** [rq/rq#243]
I am wondering why rq use pickle over json to store the data (data, result and meta fields) in queues. 

Using json would as least have two advantages:
1. The data is more human readable. 
2. The data can be accessed by any other language. For example, we might have a nodejs app for analysis and monitoring.   

As far as I understand, the only advantage of using pickle is storing some complex types such as class or function.

**Comment by mrgordon** [comment]
Yep, I understand your reasoning but I too will probably end up needing to use pyres to get around the use of pickle.

**Comment by maximilianr** [comment]
FYI, we're using dill, which supports serializing far more complex objects

**Comment by cipri-tom** [comment]
@max-sixty did you have to do anything special in order to use dill? Or simply importing it _before `rq`_ suffices? I heard it does some magic about imports so that the next modules will think they are picklinging, whereas they are using dill

**Comment by max-sixty** [comment]
Yes, it's magic (imo too much magic, but sobeit)
