### ISSUE TITLE
Delay function unpickling until job is performed

### ISSUE THREAD

**Issue by wichert** [rq/rq#328]
I have some classes with custom pickling logic (see #325 for some background). These rely on some global state such as the SQLAlchemy session and Pyramid-specific thread-locals. This is problematic when they are unpickled in the main worker process. Specifically when unpickling I reload a SQLAlchemy object in the current transaction/session, which means the main worker process will end up with an open SQL transaction that is never committed, and SQL connection errors in the client when the connection is used across a fork.

I can try to work around this in various ways, but I am wondering if a much simpler option is possible here: just delay unpickling of `self.data` in a Job instance until `perform()` is called. 

I'm happy to prepare a pull-request implementing this if you are interested.

**Comment by lowercase00** [comment]
Closing - this is a +8 year old stale issue. Feel free to reopen if anyone feels this is still relevant.
