### ISSUE TITLE
Automatically spawning of workers

### ISSUE THREAD

**Issue by glestaris** [rq/rq#335]
Hello,

I am using rq in a part of my project for web triggered plotting tasks.

I've developed a load balancer (sort of) that monitors rq queues and spawns workers to compensate for the increasing number of waiting jobs.

Would this be an interesting contribution to the project? Should I take some time and make a pull request or is there (will be) something in rq that does this already?

Cheers,
George

**Comment by scorday** [comment]
@glestaris Please, please, please! That is what i searching for. Can you somehow share the code?

**Comment by ecarreras** [comment]
We have some initial working code [autoworker](https://github.com/gisce/autoworker), the next step is to do an AutoWorkerQueue which spawns a maximum of workers automatically on enqueued a Job

**Comment by glestaris** [comment]
Hey @scorday,

Nice to see this issue still being relevant but I am afraid I haven't touched this code for the past 3 years now (which makes it almost certainly impossible to merge back).

I'd recommend looking at the alternative @ecarreras has to offer. It seems similar to what I was doing back then and also has tests :)

**Comment by glestaris** [comment]
Plus @ecarreras seems to be using rq for the past 3 years+ so his solution will certainly be way more mature by what I was doing back then, and I have moved away from this project since.

**Comment by scorday** [comment]
@glestaris @ecarreras Thanks!

**Comment by lowercase00** [comment]
There are quite a few ways to handle this: HPA on k8s layer, simple script that gets the queue size and spawns new workers dynamically, autoworker, etc. Closing it.
