### ISSUE TITLE
Make reliable when Redis connection is dropped

### ISSUE THREAD

**Issue by nvie** [rq/rq#35]
`rqworker` should run reliably over long periods of time, without the possibility of crashing or stopping under normal circumstances. When redis-server is killed and immediately rebooted (i.e. upon a connection hiccup), `rqworker` should remain running normally.

Currently, it crashes due to Python Redis' driver's `redis.exceptions.ConnectionError`.

**Comment by lowercase00** [comment]
@selwin this is a pretty old issue and there's a retry logic `worker.dequeue_job_and_maintain_ttl` with the `connection_wait_time`. Suggestion to close this.

**Comment by selwin** [comment]
Inded. Thanks @lowercase00 :)
