### ISSUE TITLE
sentry DSN in config needs sync+ or requests+ prefix to work

### ISSUE THREAD

**Issue by tstriker** [rq/rq#353]
Not sure when this changed but I poked my face out trying to find where the exceptions go.

In short sentries from RQ just seemed never reach sentry itself and i suspect that it is due to something with threaded threads or somesuch.

What fixed it for me was specifying the transport in the sentry DSN as per this page:
http://raven.readthedocs.org/en/latest/transports/index.html?highlight=transport#requests

both requests (will need the lib) and sync work fine, the others result in no exceptions sent

**Comment by kevart** [comment]
Is this fixed? I have the same issue with rq==0.5.6. Adding *sync+* or *requests+* works.
