### ISSUE TITLE
Run Worker.work in same process without forking for Unit Testing + Mocking support

### ISSUE THREAD

**Issue by mistresseve666** [rq/rq#367]
Would it be difficult to support being able to run:

``` python
q = Queue()
w = Worker(q)
w.work(True)
```

in the same process the worker is created in without forking? I know I can make a subclass of Worker that forgoes forking, but it would nice to make rq more Unit Testing, and Mock friendly.

Currently if I want to mock anything that is ran inside of a job, I need to mock out `os.fork` to return `0` and `os._exit` to not do anything. This will force the worker to run in the same process, and allow my `mock.patch`. If I do not, then the rq job will run and not share the same mock objects.

If there are ways of doing this with `mock` and `rq` as-is, then I'd be happy to learn as I'm fairly new to `mock`.

**Comment by nabilm** [comment]
This is never worked ! i don't see something in the code flow that depends on the async argument you always call the resolve_connection ! and it 'll always raise error 
 57     def __init__(self, name='default', default_timeout=None, connection=None,
     58                  async=True, job_class=None):
---> 59         self.connection = resolve_connection(connection)
     60         prefix = self.redis_queue_namespace_prefix
     61         self.name = name

/home/vagrant/coolblue2/local/lib/python2.7/site-packages/rq/connections.pyc in resolve_connection(connection)
     68     connection = get_current_connection()
     69     if connection is None:
---> 70         raise NoRedisConnectionException('Could not resolve a Redis connection')
     71     return connection
     72

NoRedisConnectionException: Could not resolve a Redis connection

**Comment by robodude666** [comment]
@nabilm, this issue was around not being able to mock `rq` because it forked the process the job ran in and the mock never got updated. You will still need to provide a mock for the redis connection.

See #282 on how to use `fakeredis` to mock the connection while making rq's strict instance check happy.

**Comment by ericman93** [comment]
even if I'm using SimpleWorker, the meta and the data sending to job is being seralized
so if I'm passing magic mocks in `meta`, I wont be able to assert them being called since it isn't the same mock anymore
