### ISSUE TITLE
Make the job dependency API more robust

### ISSUE THREAD

**Issue by nvie** [rq/rq#387]
I think the "job dependencies" implementation is too complex and therefore isn't as well-designed as it should be. In the typical example:

``` python
first_this = Queue('high').enqueue(foo)
then_this = Queue('low').enqueue(bar, depends_on=first_this)
```

`first_this` has a good chance of having been executed and finished by the time the `then_this` call is made. Even though we _do_ check against this, this is a rabbit hole of race conditions:
- `foo` may have finished by the time the second enqueue call is made;
- it may have failed (how would retry interact with this?)
- we check whether it failed [like this](https://github.com/nvie/rq/blob/eb6fb27281a3a77b6041601f2d11ad9fb3560545/rq/queue.py#L190). This does solve the problem in _some cases_, but not _all_. There are still race conditions when the job is finished in between lines 190, 191, and 192. Adding more checks won't help. Only proper locking of some sort will, but it's complicated.

This is mostly caused by the lack of better abstractions. At the moment I'm just taking note here, but we'll have to discuss this a bit more and see how we can make this part of the API more reliable.

This will need to be addressed before I'm comfortable pulling PRs like #279.

What do you think, @selwin?

**Comment by lowercase00** [comment]
A lot has changed since this was opened. Closing it.
