### ISSUE TITLE
Worker.set_current_job_id should support multiple jobs per worker

### ISSUE THREAD

**Issue by selwin** [rq/rq#392]
Worker may concurrently work on multiple jobs as demonstrated in this [gevent based worker](https://github.com/zhangliyong/rq-gevent-worker). We should allow `current_job_id` to support multiple values.

**Comment by robodude666** [comment]
I'm a little lost frankly on why the `Worker` even has a `get_current_job` method. I understand you could in theory you could use the `Worker`'s classmethods to iterate over all the workers to figure out what jobs they're currently working on -- for say, a dashboard, but beyond that I don't see the use of knowing which job a worker is currently crunching.

If that's the intent of this method, then it means RQ must enforce a "one job per worker" paradigm which makes things like the gevent pool-based worker not possible as it'll break this design principle by running multiple jobs in a single worker.

If RQ wants to support multiple jobs per worker, and make pool-based or multiprocessing-based Workers possible then `get_current_job` and `set_current_job_id` aren't sufficient. They would, at the very least, need to be pluralized. It might be better to just give each `Worker` a `BaseRegistry`-based list/queue.

-robodude666

**Comment by lowercase00** [comment]
@selwin +7 year old issue. Suggestion to close it.
