### ISSUE TITLE
How can I poll all jobs?

### ISSUE THREAD

**Issue by MTecknology** [rq/rq#402]
I love the simplicity of rq and found queuing jobs to be incredibly easy. However, I don't see a way to get a list of jobs for a specific queue and also not a way to find whether they succeeded or failed.

My goal in the application is to create the jobs and then notify the user when they finish and report whether they failed or succeeded.

Obviously the mechanisms exist to get this data since rq-dashboard and other tools to do that exist. I just can't find any documentation for actually doing this myself.

Something like...

```
jobs = rq.get_jobs(queue='foo', connection=redis_conn)
for job in jobs:
    print job['id']
```

I'm sure it exists... where's the documentation? :(

**Comment by m1yag1** [comment]
I'm having trouble finding a way to get all jobs that have completed. Aside from the example above from @MTecknology is there another way that this has been implemented?

**Comment by MTecknology** [comment]
PR #391

**Comment by sigmavirus24** [comment]
I hate reviving old issues, but I'm not seeing how #391 made it possible to get finished jobs back since the Queue doesn't keep them.

**Comment by jkryanchou** [comment]
I haven't see any modifications on #391 PR to fix this issue? Anyone could mention it me?

**Comment by jkryanchou** [comment]
@selwin  Could you mention it to me how to get the FinishedJobs of Queue?

**Comment by chuckytah** [comment]
no further details on this? how to get the FinishedJobs of Queue?

**Comment by nzjrs** [comment]
RQ has a small code base and is very extensible. I simply implemented my own Job and Worker class and placed my application specific logic there. It's very clean and only a handful of LOC

**Comment by lowercase00** [comment]
This can be done using the `finished_job_registry` attribute on the `Queue` instance:

```python
q = Queue(...)
registry = q.finished_job_registry
registry.get_job_ids()
```

The queue also holds other registries as attributes:
- `failed_job_registry`
- `started_job_registry`
- `finished_job_registry`
- `deferred_job_registry`
- `scheduled_job_registry`
- `canceled_job_registry`

They all implement the `BaseRegistry` so all the methods[ listed there](https://github.com/rq/rq/blob/fa7a635aa42b9626abf488d51863b2333d7837e5/rq/registry.py#L20) can be used.

@selwin suggestion to close this.
