### ISSUE TITLE
Job.fetch(None) raises NoSuchJobError

### ISSUE THREAD

**Issue by robodude666** [rq/rq#429]
If you don't guard against passing `None` as the `id` argument yourself, `Job.fetch` will raise a `NoSuchJobError` exception after trying to `refresh`.

This is because the `id` property is lazy and creates a new `id` as we didn't assign one. This ends up being an issue because `NoSuchJobError` suggests the job id you requested does not exist, making it difficult to separate the two different types of exceptions, where instead it was simply an invalid value passed to `fetch`.

I think the appropriate fix would be to have `Job.fetch` raise a `ValueError` for not allowing a `None` value. The user will still have to catch this exception themselves, but it at least it will be clear what's going on.

**Comment by selwin** [comment]
The user should chec
