### ISSUE TITLE
Current master can't handle large queues

### ISSUE THREAD

**Issue by glaslos** [rq/rq#472]
While testing the current master branch, I stumbled over a massive performance degradation: The `pipeline.lrem` here: https://github.com/nvie/rq/commit/638211df20858187c39ea1a7ffd5c78c1a6acca3#commitcomment-9241474 is very expensive:

```
[1514L, 1421070696L, 2169075L, ['LREM', 'rq:queue:queuename', '0', 'a3c2a26a-e55a-4031-ba95-e66212425036']]
[1515L, 1421070700L, 2217511L, ['LREM', 'rq:queue:queuename', '0', 'd54a061d-122a-4834-8812-c351b4b701da']]
[1516L, 1421070703L, 2105862L, ['LREM', 'rq:queue:queuename', '0', 'd54a061d-122a-4834-8812-c351b4b701da']]
```

`rq:queue:queuename` has more than 2.5 million jobs. The `count=0` is causing redis to search through the whole list on every `job.remove()`

**Comment by selwin** [comment]
Yeah, removing an item from a queue in Redis is O(n).

RQ itself won't fail if the job itself is deleted without being removed from the queue. I wonder if we should discourage the use of `job.cancel()` and ask people to use `job.delete()` instead.

**Comment by glaslos** [comment]
`queue.remove()` is also used by `queue.fetch_job()`: https://github.com/nvie/rq/blob/dc09676ee03b978691d5d3c0bc725ab30bc0077a/rq/queue.py#L105

**Comment by selwin** [comment]
Yeah, we probably shouldn't implicitly call `queue.remove` when `queue.fetch_job()` couldn't find a job and let the user handle it themselves. For very large queues, job keys should only be popped off the list using `lpop` by Workers.

**Comment by glaslos** [comment]
Any reason why we use count=0 (delete all occurrences) over count=1 (first)? Do we expect more than one entry per job? with count=0 you always hit the O(n) worst case.

**Comment by selwin** [comment]
No, there should be no duplicate jobs on the queue. You're right, it should be count=1.

**Comment by selwin** [comment]
And to answer your comment about the fact that `queue.remove()` is also called by `queue.fetch_job()`; I think we'll have to delete all implicit invocations of `queue.remove()` in RQ's code base so we don't accidentally slowdown the entire DB.
