### ISSUE TITLE
Long-running jobs erroneously registered as 'failed'

### ISSUE THREAD

**Issue by classner** [rq/rq#550]
Long-running jobs (longer than worker-ttl) are currently registered in the 'failed' queue and the workers are removed from the dashboard and registry as 'dead'. This is due to the implementation of `worker.py` (line 492-494):

```
                self.set_state('busy')
                os.waitpid(child_pid, 0)
                self.set_state('idle')
```

The call to `os.waitpid` is blocking and prevents sending the heartbeat. Just raising the worker-ttl is not a valuable fix, because the worker-state is in that case being monitored with a strong delay (in my case, a job can take 30 mins to several hours, and raising the worker-ttl to those values would lead to many ghost workers in the worker lists...).
## Proposed fix

This code at the moment is in a loop to handle SIGINTs and SIGTERMs already. I think a simple yet effective fix for this issue would be to change the lines to:

```
                self.set_state('busy')
                pid, err_code = os.waitpid(child_pid, os.WNOHANG)
                if pid != 0:
                    # The process actually finished.
                    self.set_state('idle')
                    break
                else:
                    self.heartbeat()
                    # Uses the timeout as calculated in `worker.py` line 410 or 10 seconds,
                    # whatever is smaller. 10 seconds could be configurable.
                    time.sleep(min(max(1, self.default_worker_ttl - 60), 10))
```

Are there any issues with this that I don't see yet?

**Comment by selwin** [comment]
In `Worker.prepare_job_execution`, worker sends a [heartbeat](https://github.com/nvie/rq/blob/master/rq/worker.py#L533) with `timeout = (job.timeout or 180) + 60` so it should be able to accommodate jobs with varying timeouts, as long as `job.timeout` is set properly. Did you set `job.timeout` properly?

**Comment by ChrislS** [comment]
No, I did not do this, and did not come along this option. I did set the ttl on the job queue for all jobs in the queue, but no other options. I presume, these are two different things, then (it should definitely go into the [job doc](http://python-rq.org/docs/jobs/).

But does this not also have unwanted consequences: if the worker dies executing a long-running job, then the monitor will only indicate this a long time after it happened, correct? In this case I'd prefer to have a shorter feedback loop...

**Comment by selwin** [comment]
`timeout` is a documented option in the [Queue](http://python-rq.org/docs/) section of the docs.

I do agree that a shorter feedback loop is desirable. Continuously polling for the status of the child using `os.waitpid(child_pid, os.WNOHANG)` does not look like an elegant solution to me. Any other ideas on how to make this happen? I also want the child process to be able to notify its parent in real time when job execution is finished.

Perhaps we could use Redis' pub/sub feature to facilitate worker/child communication. I haven't really looked into whether this is possible though.

**Comment by ChrislS** [comment]
Thanks for the hint! :)

Well, it's necessary to send a message to the queue server in regular intervals anyway, so why not get the most up-to-date information about the process at the point in time? With a reasonable interval, I don't find the polling approach too bad. What would a better solution look like than checking the current state of the process when sending the heartbeat?

**Comment by selwin** [comment]
I think we should look into Redis' pubsub mechanism. The parent process should be able to subscribe to updates from it's child process. I don't know how complex this will be to implement though.

**Comment by selwin** [comment]
RQ's master worker process now [periodically](https://github.com/rq/rq/blob/master/rq/worker.py#L622) checks for the work horse's status so this should no longer be an issue.
