### ISSUE TITLE
Configurable failed queue name for worker class and rqworker

### ISSUE THREAD

**Issue by jmmills** [rq/rq#556]
It would be nice to be able to assign a failed queue name for a worker object (or when sub-classes) as well as a flag for rqworker (--failed-queue-name, -f)

I took a stab at it in a fork, it didn't work out of the gate, but maybe given some extra time I can figure it out. But the gist of it would be (correct me if I'm wrong here):
- Add name option (default to JobStatus.FAILED) to get_failed_queue
- Pass that name as first argument to FailedQueue, in which superclass will pickup default
- add failed_queue_name option as an optional kwarg to Worker, pass this into get_failed_queue if available
- add a cli flag to worker that passes that into worker class instanciation

**Comment by selwin** [comment]
Why would you rename a `FailedQueue`? What's your goal?

**Comment by jmmills** [comment]
In some cases one divides up work to different queues by work type, for example a transcoding service:
Avi, MP4 would be queues in which each input media would have a job places to transcode to that type... If it failed to transcode to that job, I would want to see that job in a failed queue named after its failed function.

It's mostly just to keep things organized.

**Comment by selwin** [comment]
A better solution would be to make `FailedJobRegistry` that's specific per queue. We already have `ActiveJobRegistry`, `FinishedJobRegistry` and `DeferredJobRegistry`, we should have `FailedJobRegistry` too. PR welcome :)

**Comment by jmmills** [comment]
@selwin I can give a shot I suppose when I find the time.

**Comment by selwin** [comment]
In the latest version of RQ, each queue already has it's own `FailedJobRegistry`
