### ISSUE TITLE
Branch multi-dependencies

### ISSUE THREAD

**Issue by yaghmr** [rq/rq#566]
The branch `multi-dependencies` is stable? Can I use in production? Why is not merged in `master`?

**Comment by yaghmr** [comment]
Congrats! Two months without a reply (yes or no was enough).
Great open source project.

**Comment by chishaku** [comment]
@yaghmr 

It is frustrating sometimes when people don't go out of their way to help you out, even if all you need is a yes or no.  We can all relate to that.

I'm not sure who takes primary responsibility for maintaining this library but my assumption is that, like many other libraries, `rq` is shared 'as-is' without any sense of entitlement on my part for any type of support.

Following from that assumption, I understand that respectful follow-up questions are more likely to lead to answers than snarky comments.  

If you're still interested in multiple dependencies, the branch below was recently implemented and is working for me and the author, as far as I can tell.  There are no guarantees of stability but fwiw, I'm using it in production.

https://github.com/jlopex/rq/tree/javi/multi-dependencies

If it works for you and you have feedback or if you have any questions, there is more discussion here: #260.
