### ISSUE TITLE
Propagate custom Job class down to queue in worker

### ISSUE THREAD

**Issue by aroberts** [rq/rq#568]
When invoking the worker with a custom Job class, I noticed that the queue was returning an `rq.job.Job` instance (instead of my custom job class) during `Queue.dequeue_any()`. I think I have a workaround, but it's confusing that the worker returns a custom job type for `get_current_job()`, but the jobs the worker receives to execute from the queue aren't of the custom type.

**Comment by selwin** [comment]
Yeah, that's confusing. I think `dequeue_any()` should return a custom job class. I think we should store the job class information in the job so `Queue.dequeue_any()` can use the right job instance.

Do you mind making a PR for this?

**Comment by selwin** [comment]
Fixed in https://github.com/zamzterz/rq/commit/78bd55695c85ce284de8f8c02a911ad6b3d6f015
