### ISSUE TITLE
Can't set most CLI options via --config

### ISSUE THREAD

**Issue by aroberts** [rq/rq#569]
Looking at the source for the `worker` cli command, it appears that only the Redis connection info, default queue names, and Sentry DSN are considered in the config module passed via `--config`.  I have verified that the logging flags (`-q`, `-v`), and the various class settings (`-j`, `-w`) also do not respect the config.  It would be great to be able to specify these flags in a file, rather than on the command line.

**Comment by selwin** [comment]
Agreed, pull request welcome :)

**Comment by selwin** [comment]
I'm closing this issue as many CLI options have been added over the years. If there's some configuration options still missing, please open a PR.
