### ISSUE TITLE
Log collection

### ISSUE THREAD

**Issue by NeckBeardPrince** [rq/rq#591]
We currently use RQ with different clients, we have a upstart script that kicks off worker and the output is dumped into a log file for collection. But I'm having a hard time trying to find a way for Logstash to read a "beginning" and "end" of output. Because each line has a timestamp there really doesn't seem to be an easy way to see when one line starts and the other ends. Is there a way or will there be a way to input a job idea or maybe even something at the start of output and something at the end of output so we can know what output was for what task?

> 20152310 00:46:45 - INFO - RQ worker u'rq:worker:ip-10-0-1-77.25274' started, version 0.5.6
> 20152310 00:46:45 - INFO -
> 20152310 00:46:45 - INFO - **\* Listening on-stg:staging:default...
> 20152310 01:00:00 - INFO --stg:staging:default: main.tasks.articles.update_articles() (28df18f8-b774-4de0-93bf-909238fc0de7)
> 20152310 01:00:04 - INFO - Starting new HTTPS connection (1): graph.facebook.com
> 20152310 01:00:04 - INFO - Starting new HTTPS connection (1): api.instagram.com
> 01:00:04 Job OK
> 20152310 01:00:04 - INFO - Job OK
> 01:00:04 Result is kept for 500 seconds
> 20152310 01:00:04 - INFO - Result is kept for 500 seconds
> 20152310 01:00:04 - INFO -
> 20152310 01:00:04 - INFO - **\* Listening on-stg:staging:default...
> 20152310 01:00:04 - INFO --stg:staging:default: main.tasks.campaigns.publish_campaigns_process() (d0bc5514-089a-43b9-942a-23d442e66026)
> 01:00:06 Job OK
> 20152310 01:00:06 - INFO - Job OK
> 01:00:06 Result is kept for 500 seconds
> 20152310 01:00:06 - INFO - Result is kept for 500 seconds
> 20152310 01:00:06 - INFO -
> 20152310 01:00:06 - INFO - **\* Listening on-stg:staging:default...
> 20152310 01:00:06 - INFO --stg:staging:default: main.tasks.adunits.expire_adunits_process() (f383bdca-f76f-49b2-8c94-d7793a584e7b)
> 01:00:07 Job OK
> 20152310 01:00:07 - INFO - Job OK
> 01:00:07 Result is kept for 500 seconds
> 20152310 01:00:07 - INFO - Result is kept for 500 seconds
> 20152310 01:00:07 - INFO -
> 20152310 01:00:07 - INFO - **\* Listening on-stg:staging:default...
> 20152310 01:00:07 - INFO --stg:staging:default: main.tasks() (6dec00e7-a703-4abe-a95e-c13edc4881f1)
> 01:00:07 Job OK
> 20152310 01:00:07 - INFO - Job OK
> 01:00:07 Result is kept for 500 seconds
> 20152310 01:00:07 - INFO - Result is kept for 500 seconds
> 20152310 01:00:08 - INFO -
> 20152310 01:00:08 - INFO - **\* Listening on-stg:staging:default...

**Comment by jmmills** [comment]
I've used pythons logging framework with different formatters with a high degree of success with RQ for logstash and splunk... 

https://pypi.python.org/pypi/logstash_formatter

**Comment by NeckBeardPrince** [comment]
Oh wow.. Looks handy, I'll take a look into that. Thanks.

**Comment by selwin** [comment]
Suggestions for making log output more readable is welcome :)

**Comment by Paulius-Maruska** [comment]
Well, the default RQ formatter isn't very file friendly (due to the colour codes being hard-coded into messages or, in some cases, message parameters). I know it looks nice when you're staring at the console output of a worker, but how many people actually do that?

**Comment by lowercase00** [comment]
Closing this as logging as mostly solved at this stage.
