### ISSUE TITLE
Exception handler for Queue

### ISSUE THREAD

**Issue by horida** [rq/rq#653]
The [documentation](http://python-rq.org/docs/exceptions/) explains how to pass exception handlers to a Worker. 
In [this SO answer](http://stackoverflow.com/a/16326962/1141095) it looks like it was part of RQ's Queue class once, though I can't find a way to do this.

Is there a reason why this is not implemented (anymore)?

**Comment by proofit404** [comment]
In my opinion it is better to wrap problematic part of your task into `try/except` block or context manager and schedule new task with retry counter incremented.

Returning to your question exception handlers are processed inside worker so its natural to specify it in the worker (don't know how it was implemented in the past).

**Comment by horida** [comment]
@proofit404 I have several methods that are enqueued in a row, each depending of the former one. The only way, to break in the middle of those queues, is to raise an Exception.
In order to avoid that the exception is passed through to Sentry, I'd like to intercept it. The exception handler looked promising. 
But I don't have access to the Worker when queueing like this `Queue(name='Qbar').enqueue(func, arg, depends_on=other_queue)`. Here `func` is the method that raises the exception

**Comment by proofit404** [comment]
Looks like you are trying to solve the consequence and not the reason of the problem.

Maybe it is better to cancel following jobs in the chain instead of failing current job?

```python
current_job = get_current_job()
dependents_key = current_job.dependents_key
for job_id in current_job.connection.smembers(dependents_key):
    cancel_job(job_id)
```

Remember to cleanup it recursively (the dependents of the current job dependents, etc).

**Comment by horida** [comment]
Thanks for your answer @proofit404 
Actually, I think your solution is solving the consequence. By letting fail the job the following jobs would be started at all.

**Comment by proofit404** [comment]
In the solution I've provide dependent jobs will not started too. I guess it is better to have some public api in the rq package for this stuff.
```python
cancel_dependent_jobs(job_id, connection=None)
```
@nvie @selwin what do you think guys?

**Comment by selwin** [comment]
Sorry, I missed this issue. Having `job.delete_dependents()` would be great. PR welcome :)

**Comment by lowercase00** [comment]
We do have `job.delete(delete_dependents=True)`, so I understand this is fixed for now. Feel free to reopen this if it's still an issue for anyone.
