### ISSUE TITLE
Serverless with redislite

### ISSUE THREAD

**Issue by delijati** [rq/rq#664]
It would be nice if rq could also use https://github.com/yahoo/redislite as backend

**Comment by selwin** [comment]
Does it support all the Redis commands used in RQ? If it does, then you should be able to pass in a Redisliste connection instead of Redis. If it doesn't, I'm a bit hesitant to do it because it will increase the effort to maintain this library.

**Comment by surfmikko** [comment]
I have been using RQ with fakeredis.FakeStrictRedis for testing purposes.

https://github.com/jamesls/fakeredis

**Comment by lowercase00** [comment]
@selwin suggestion to close this.
