### ISSUE TITLE
Signal handlers and multiprocessing library

### ISSUE THREAD

**Issue by uiii** [rq/rq#709]
Hi, I have a problem when I use `rq` and `multiprocessing` together. The problem is because `rq` set custom signal handlers, so when I need to terminate the process I get an error and the process is not terminated. I had this problem specifically with `fusepy` library.

Consider this code example:

``` python
redis = redis.StrictRedis()
queue = rq.Queue(connection=redis)
worker = rq.SimpleWorker(
        queues=[queue],
        connection=redis
)
worker.work(burst=True) 

# solution comes here (see bellow)
...

process = multiprocessing.Process(
    target=FUSE, 
    args=(fuse_operations, moutpoint, nothreads=True, foreground=foreground,), 
    daemon=True)

process.start()

...

process.terminate()  # this throws error
```

At the last line I get an error, but the fuse process is not terminated:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/uiii/.cache/virtualenv/konzum/lib/python3.5/site-packages/fuse.py", line 490, in _wrapper
    @staticmethod
  File "/home/uiii/.cache/virtualenv/konzum/lib/python3.5/site-packages/rq/worker.py", line 363, in request_stop
    raise StopRequested()
rq.worker.StopRequested
fuse: bad error value: 32708112
```

Solution? Just add these two lines after `worker.work`:

``` python
signal.signal(signal.SIGINT, signal.SIG_DFL)
signal.signal(signal.SIGTERM, signal.SIG_DFL)
```

So, what to do with this? I'm not sure, because I can imagine situations where the solution is not so trivial. I just wanted you to know about this.

**Comment by lowercase00** [comment]
I might be simpler to just write a new `MultiprocessingWorker` that takes the implementation details into account rather than trying to fit the `SimplerWorker` into the multiprocessing paradigm. I'll keep this open so we can track this feature.

**Comment by lowercase00** [comment]
Closing in favor of #1790
