### ISSUE TITLE
Race condition with job dependencies

### ISSUE THREAD

**Issue by th3hamm0r** [rq/rq#739]
I stumbled across this bug:
If a new job B with a dependency to job A is inserted during job A is executed, it may happen, that job B is never executed.
The problem is that `enqueue_dependents` in worker.py ([L682](https://github.com/nvie/rq/blob/master/rq/worker.py#L682)) is called outside of the pipeline which changes the job's status to finished. `enqueue_dependents` just does not use the pipeline (there is a "todo" for that: [L293](https://github.com/nvie/rq/blob/master/rq/queue.py#L293)).
The redis-watch in `enqueue_call()` ([L204](https://github.com/nvie/rq/blob/master/rq/queue.py#L204)) does not help in this case, because it executes normally during the job is in a non-FINISHED state.

I found https://github.com/nvie/rq/issues/387 about race conditions but it seems that result of the discussion was, that it should be safe (https://github.com/nvie/rq/issues/387#issuecomment-50255180). But actually it isn't...

**Comment by th3hamm0r** [comment]
As a quick fix I think I will move the line with `queue.enqueue_dependents(job, pipeline=pipeline)` to follow the `pipeline.execute()` call.
This should avoid the race condition, but of course it makes it a bit less fail-safe: if the worker crashes after finishing, but before enqueuing the dependents, we again have a "hanging" dependency chain.

To fix this issue correctly, I think the worker-side also needs a redis-watch (on the `dependents_key`). But the actual code change may be a bit more complex (eg. handling of `WatchError`) and for that I've too few knowledge about rq's code base.

**Comment by th3hamm0r** [comment]
Fyi: I've started an approach to fix the issue with an additional redis-watch in the worker, which should be failsafe too: https://github.com/th3hamm0r/rq/commit/7b8d4e075e30ca64fa8caa09867624cf2480c983
I'm currently testing it in a project.

**Comment by selwin** [comment]
Thanks for working on this. Could you please open a PR when you find a solution?

**Comment by th3hamm0r** [comment]
@selwin I think I've found a solution (#742)

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/742
