### ISSUE TITLE
Allow workers to read jobs from wildcard queues

### ISSUE THREAD

**Issue by saidimu** [rq/rq#75]
From the `rq` docs:

Given this

> As soon as you enqueue a job to a queue that does not exist yet, it is created on the fly.

And this

> Workers will read jobs from the given queues (the order is important) in an endless loop

It is very easy to forget to start workers that listen on a newly created-on-the-fly queue. Something like `$ rqworker *` might mitigate against this.

**Comment by lowercase00** [comment]
10 year old issue, I'll be closing this. We can assess whether we want to support this feature in the future again.
