### ISSUE TITLE
Improve implementation of fe122ac7

### ISSUE THREAD

**Issue by aaugustin** [rq/rq#750]
fe122ac7 introduced an `_has_effective_handler(logger)` function which appears to duplicate the public API `Logger.hasHandlers()`: https://docs.python.org/3/library/logging.html#logging.Logger.hasHandlers but doesn't handle correctly handlers that don't propagate messages.

Compare with the implementation of `Logger.hasHandlers()` here: https://github.com/python/cpython/blob/7f43e8608b63a5af0211730dd2e163cbf0d8563b/Lib/logging/__init__.py#L1471-L1491

Unfortunately, `hasHandlers` isn't available on Python 2, which rq appears to be still supporting at this time.

I would like to suggest the following pattern:

``` python
try:
    logger.hasHandlers
except AttributeError:
    # Compatibility shim for Python < 3.2
    has_handlers = _has_effective_handler(logger)
else:
    has_handlers = logger.hasHandlers()

if not has_handlers:
    # automagically configure logging
```

You could also update the implementation of `_has_effective_handler` for Python 2 (but I don't care about that part, it would make sense to favor stability above correctness on Python 2 at that point).

**Comment by selwin** [comment]
What you suggested (making use of build in APIs in Python 3 makes perfect sense :). I don't have much time to maintain open source projects lately but will try to squeeze this in if I can (a PR would be awesome though :).

**Comment by lowercase00** [comment]
Closing this for now. Logging configuration can be done when running the worker manually with `worker.work()` and it seems reasonable to have some default setup for people that are just running the cli `rq worker`.  Other log-related aspects can be discussed in the future.
