### ISSUE TITLE
Pipeline enqueue() calls?

### ISSUE THREAD

**Issue by matthewrobertbell** [rq/rq#753]
Hi,

I do large numbers of my_queue.enqueue() calls at a time, is there a way to do this with a pipeline? I looked at the source but couldn't see anything obvious. I often enqueue thousands of jobs at once, so pipelining seems worthwhile.

Thanks

**Comment by proofit404** [comment]
Looks like you can achieve it this way:

* create redis pipeline yourself
* create thousand job instances with `queue.job_class.create`
* call `queue.enqueue_job(job[n], pipeline=yourpipe)` thousand times
* execute pipeline `yourpipe.execute()`

Remember that you need to resolve all `depends_on` related logic yourself in this case.

Hope this helps.

**Comment by mattseh** [comment]
def pipeline_enqueue(pipeline, queue, func, *args, **kwargs):
        queue.enqueue_job(queue.job_class.create(func, args=args, kwargs=kwargs), pipeline=pipeline)


This worked, thank you!

**Comment by mattseh** [comment]
This actually doesn't work, and I think I know why:

Pipelined or not, this command is issued:

    "RPUSH" "rq:queue:default" "137413de-9926-4171-8b93-539b200d06db"

When not pipelined, this works fine, as it's the last command issued, however when pipelined, it's issued outside the pipeline, meaning that the worker will think there's a queue item before it's actually in there. 

Would I need to change queue.connection to be the pipeline, or is there a better way?

Thanks

**Comment by mattseh** [comment]
Would self.push_job_id being passed the pipeline from enqueue_job be the fix?

**Comment by mattseh** [comment]
Yep, changing it to 

    if self._async:
            self.push_job_id(job.id, at_front=at_front, pipeline=pipeline)

seems to work. I have no prior experience with RQ internals, can someone please confirm whether this would break anything?

Thanks

**Comment by mtdewulf** [comment]
I'm getting the same issue.  The worker is not processing any jobs enqueued via a pipeline, though not using a pipeline works fine (but is slow).

```python
pipe = connection.pipeline()  # Same `Redis` connection object used for RQ interaction.

for job in jobs:
    queue.enqueue_job(job, pipe)

pipe.execute()
```

**Comment by mtdewulf** [comment]
@mattseh, I tried that fix over [here](https://github.com/mtdewulf/rq/tree/pass-pipeline-to-push-job-id), but it triggered a lot of test failures.  I didn't look any further (I'm also new to RQ), but it seems like the correct fix is more complicated, unfortunately.

**Comment by mtdewulf** [comment]
(Deleted the last message - spoke to soon).  PR is [here](https://github.com/nvie/rq/pull/761).

**Comment by selwin** [comment]
It will be nice to have a nice API like `queue.enqueue_many([job1, job2, job3])` to make this simpler. Would appreciate a PR for this :). If it's overly complex, we don't need to support job dependencies (throw an exception) in the first iteration of the method.

**Comment by mattseh** [comment]
Am I correct in saying that currently jobs created using `enqueue()` can't be pipelined, only `enqueue_job()`?

It seems like there would need to be explicit passing of a pipeline object from `enqueue()` to `enqueue_call()` to `enqueue_job()`, is that right?

I agree with selwin that an `enqueue_many()` would be nice.
