### ISSUE TITLE
What happens if I pass in a job_id already in the queue?

### ISSUE THREAD

**Issue by rahulcap** [rq/rq#793]
The docs/code are unclear on the behavior when passing a job_id to enqueue(), when that job_id is already present.  

I see a few possibilities:
A) Is it a 'no-op', since the id is higher in the queue?
B) Does it replace the job?  (in-place, or at end of queue?)
C) Are both of them enqueued?
D) Does it fail?

- It would be useful to understand this behavior.  Since I currently get repeat requests for the same 'work', I'd like to do something like A or B so that the 2nd request is essentially ignored if the 1st one hasn't been worked on.  
- If the answer is C, then I imagine queue.fetch_job() will fail.  Or maybe it just returns a random one?
- if the answer is D, it's ok, as it's similar to A, but would be good to know if I need to handle the error case to get the right 'job' back.  

Either way - some clarity on this in the docs would be nice!

**Comment by rahulcap** [comment]
feedback on best way to handle this?

**Comment by rahulcap** [comment]
I ran some tests on this and it seems the behavior is "C" (enqueues both) and fetch_job() seems to just return one of the jobs.   This is "ok" but should probably be documented.

To handle my specific case, I wrote a wrapper that would first try to do a fetch_job() and then only enqueue if NOT "queued" or "deferred",  and it removes and requeues if it is "failed".

I think writing a custom wrapper like this is sufficient since people may have different requirements.  

My only suggestion then, is to provide documentation on this edge case of multiple jobs with the same job_id

**Comment by sirex** [comment]
It looks like, you can enqueue multiple jobs with the same job_id and all enqueued jobs with duplicate ids will be executed.

```python
from redis import Redis
from rq import Queue
from rq import SimpleWorker

def foo():
    print('ok')

q = Queue(connection=Redis())
q.enqueue_call(func=foo, job_id='42')
q.enqueue_call(func=foo, job_id='42')

print('q.job_ids:', q.job_ids)

worker = SimpleWorker([q], connection=q.connection)
worker.work(burst=True)
```

Output:
```
q.job_ids: ['42', '42']
ok
ok
```

**Comment by selwin** [comment]
What @sirex said, the job will be executed twice (if the job is still in Redis).
