### ISSUE TITLE
Workers don't send heartbeat during suspension.

### ISSUE THREAD

**Issue by red-crown** [rq/rq#804]
If you suspend workers for longer than the worker ttl, they will no longer appear in the monitoring dashboards. We should continue sending the heartbeat inside the check_for_suspension loop.

**Comment by selwin** [comment]
You're right. Mind opening a PR for this?

**Comment by red-crown** [comment]
Do you see a problem with just sending the heartbeat every second regardless of worker ttl?

**Comment by red-crown** [comment]
I'm also wondering if we should look for a better place for the suspension check. As someone else has pointed out, idle workers will always process one additional job after they have been "suspended" due to how the queue blocks for a job. I've briefly tried having the main worker sending something like a USR1 signal to the child to notify it but had some issues when the system call is interrupted.

In my scripts, I've basically resorted to suspending the workers and then pushing a number of null or "fake" jobs onto the front of the queues equal to the number of workers. My use-case for this has been on either code updates/deployments or with dynamically auto-scaled worker servers based on work load.

**Comment by selwin** [comment]
Yes, I'm aware of this limitation and it's something that we should fix.

Shutdowns (both warm and cold) are handled by the parent worker that kills the child worker if the child worker is busy. Can we use a similar method, using a different signal?

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/896
