### ISSUE TITLE
What happens to dependencies when queuing a job in custom exception handler?

### ISSUE THREAD

**Issue by daphnawegner** [rq/rq#813]
I have a custom exception handle that retries jobs a few times before sending them to the fail queue.

I have noticed that when a job that is caught by the exception handler is a dependant of another job the next job starts without waiting for the first job to finish after it was retried.

first_job = some job
second_job = some job which has a dependency to first_job

when first_job is caught by the custom exception handler, second-job immediately starts without waiting for first_job to finish it retry.

Is there a way to prevent this behaviour and make sure second_job waits for first_job to finish after it is being queued again?

**Comment by selwin** [comment]
If the first job fails, the second job (the dependent) should never start. If this is what happens, it's a bug. Care to make a PR to address this?

**Comment by lowercase00** [comment]
RQ now have a native `Retry` object (which wasn't available by the time this issue was created). This should handle the use case, so I'll close this issue for now. If there are any issues with this that's still not addresses please feel free to reopen this.
