### ISSUE TITLE
Worker.all() is slow with a large number of workers

### ISSUE THREAD

**Issue by selwin** [rq/rq#822]
- [x] `Worker.find_by_key()` should use `hmget` instead of multiple `hget` calls. Fixed in https://github.com/nvie/rq/pull/826
- [x] Create `Worker.count()` to return just the number of workers in Redis

**Comment by theodesp** [comment]
Is this done? As I can see the `Worker.count` being implemented.

**Comment by selwin** [comment]
Yes, this is already done.
