### ISSUE TITLE
Failed queue jams redis

### ISSUE THREAD

**Issue by yaniv-g** [rq/rq#834]
If the exception message is to big, or if you have many failed jobs, the failed queue gets bigger and bigger and at a certain point redis stops working because it doesn't have any available space.
The reason for this is that the result_ttl is not used when putting a failed job in this queue.
I'm not sure if the correct way is to necessarily use result_ttl for that (you might want to keep a failed job longer), but you should be able to add a timeout for failed jobs, in my opinion at least.

**Comment by selwin** [comment]
Yes, I think we should have an option to add `ttl` to failed jobs.

In addition, adding an option to compress job data before storing it in Redis would also significantly reduce the amount of memory stored in Redis while also potentially increasing performance. See this post for more context: (the tests are Django based but I think the result should be similar for RQ) https://www.peterbe.com/plog/fastest-redis-optimization-for-django

**Comment by selwin** [comment]
This has been fixed in RQ 1.0 which replaces `FailedQueue` with `FailedJobRegistry`
