### ISSUE TITLE
rpush/lpush triggers HGETALL and BLPOP?

### ISSUE THREAD

**Issue by hitigon** [rq/rq#857]
Hi,

I noticed one strange issue with RQ, when I was trying to work with RQ and Docker. 
(The redis docker image is "redis:alpine", running a single instance of Redis 3.2.8 (also tried with 3.2.6))

I have two workers running in my another container. Everything looks normal, workers do their jobs well, until I found that the `job queue` (rq:queue:default) was missing in redis. I looked the code, when enqueue_job happens (async), it supposes to push the new job id into a queue (rq:queue:default, if uses the default queue). But it didn't happen and there was any key named rq:queue:default in the redis storage. 

As I debugged the source code, the part of code indeed got triggered, and rpush did get executed as well, but nothing in redis still. 

So I tried to push a job id manually into redis, it returned integer 1, but no key was found, and pushed again, still returned 1 and no key. Yes, somehow it got popped out.

If I push other keys in the same fashion, they all work. But not this one, rq:queue:default.
If I flush the db, it still does not work.
If I start a new instance, without any RQ workers, rpush/lpush rq:queue:default works.

Then, I started to use redis monitor (should do it earlier), the following is what I saw:

```
1499230225.568655 [4 127.0.0.1:60924] "rpush" "rq:queue:default" "1d3a825c2-c332-4bcc-a115-eca03ccb1157"
1499230225.569471 [4 172.20.0.5:37786] "HGETALL" "rq:job:1d3a825c2-c332-4bcc-a115-eca03ccb1157"
1499230225.570153 [4 172.20.0.5:37786] "BLPOP" "rq:queue:default" "360"
```

OK, rpush somehow triggered not only rpush command, but also HGETALL and BLPOP? Is it something by design or I misconfigured something? I figured rq:queue:[queue_name] supposes to list the current jobs.

Could someone helps me understand?

[update]: I tested on my local box (without docker), the issue remains the same. 

Thank you!

**Comment by selwin** [comment]
My guess is that the `HGETALL` command was triggered by a worker trying to fetch job data. The subsequent `BLPOP` command is also triggered by the worker which goes back to waiting for job to be pushed to the queue.

Does this answer your question?
