### ISSUE TITLE
Community Support + Gitter/Discord

### ISSUE THREAD

**Issue by theodesp** [rq/rq#865]
I like this project and I would like to contribute.

However, I noticed that there is no community channel such as Gitter or slack so the developers can discuss PRs and other issues. Discussing ideas through GitHub is cumbersome.

I propose to setup a community chat for this as it will help with collaborating and assisting users.

https://gitter.im/
https://discordapp.com/

**Comment by danielbrownridge** [comment]
Github works for me TBH.

**Comment by trapito** [comment]
I'd join a discord if there was one, communication isn't good at all in this project

**Comment by selwin** [comment]
Sorry, I just saw this issue.

I'm not against opening a community channel for discussing ideas and getting help, but I'll need a volunteer (or two) to moderate the channel (Slack is preferred) - I don't think I'll have time to participate in it.

It will be valuable in hashing out ideas and discussing features, but I think I'd still want more concrete ideas or bug reports to be filed as Github issues that I can browse through.

Another important thing that this project lacks is good documentation, as highlighted in this issue: https://github.com/nvie/rq/issues/903  Would be great if someone can help with this too.

If we can have a few moderators, I don't mind creating the channel and putting it up on python-rq.org and README so it's discoverable.

**Comment by rpkak** [comment]
I think I could manage a disord server.

@selwin I don't really know much about slack, but I think a community server will simpler and better on discord as on slack.

If I should setup a discord, please ping me?

**Comment by selwin** [comment]
@rpkak I'm ok either way, but I have limited time nowadays and probably won't hang around much.

**Comment by rpkak** [comment]
Ok, I created a discord that can be found [here](https://discord.gg/pYannYntWH).

I now create a PR.
