### ISSUE TITLE
No (or infinite) Job Timeout

### ISSUE THREAD

**Issue by ttpham0111** [rq/rq#872]
In trying to set jobs to run indefinitely, I've discovered by overflowing the `int` passed to signal.alarm, I can create a really long time out with `-1`. 

The issue is that the worker adds the job to the `StartedJobRegistry` with a timeout of:
`timeout = (job.timeout or 180) + 60` [[source]](https://github.com/nvie/rq/blob/master/rq/worker.py#L627)

This causes the job status to be set as failed right when any worker starts working on the next job [[source]](https://github.com/nvie/rq/blob/master/rq/worker.py#L459).

The worker still finished the job though, and switches the job status back to success. This causes the job to be successful but exist in the failed queue.

Of course this can all be avoided by not using -1 for timeout (or just using 4294967295), but this seems like an edge case that should be handled?

Also, is there a legitimate way to make rq not kill jobs?

**Comment by selwin** [comment]
I think allowing users to pass in `-1` to indicate infinite timeout is reasonable. Do you mind creating a PR for this?

**Comment by bruce3557** [comment]
I also have this requirement. Is it possible to file a PR for this?

**Comment by selwin** [comment]
@bruce3557 yes, please open a PR for this.

**Comment by theodesp** [comment]
Can I take a look at this?

**Comment by selwin** [comment]
@theodesp of course :)

**Comment by theodesp** [comment]
Hey @selwin I'm implementing this and I see that we use the `parse_timeout` method to parse both timeouts and ttls. However, in that case, we cannot break the existing functionality of ttls as we want to keep them the same. For example for passing timeout values:

```
DEFAULT_INFINITE_TIMEOUT = 2 ** 31 - 1
self.assertEqual(0, parse_timeout(0))
self.assertEqual(DEFAULT_INFINITE_TIMEOUT, parse_timeout(-1))
self.assertEqual(DEFAULT_INFINITE_TIMEOUT, parse_timeout(1 - (2 ** 32 + 1)))
```

however in some places such as the `enqueue_call` in the `queue.py` we also do that:
```
        timeout = parse_timeout(timeout) or self._default_timeout
        result_ttl = parse_timeout(result_ttl)
        ttl = parse_timeout(ttl)
```

which is wrong as we return DEFAULT_INFINITE_TIMEOUT for ttl as -1

How do you suggest we handle that?

**Comment by theodesp** [comment]
I have a proposed PR for this

**Comment by selwin** [comment]
When designing RQ, we wanted to use `-1` to indicate infinite timeout so that's something that we want to keep (and probably document).

If I'm not misreading the problem description, the issue is that when `job.timeout` is `-1`, jobs aren't added with the correct ttl on `StartedJobRegistry`. The fix for that is to modify `BaseRegistry.add()` method to set job's score to `+inf` on Redis.

Do you mind modifying your PR @theodesp?

**Comment by theodesp** [comment]
Sure

**Comment by theodesp** [comment]
Updated PR https://github.com/rq/rq/pull/954
