### ISSUE TITLE
rq logging timezone

### ISSUE THREAD

**Issue by antonagestam** [rq/rq#910]
I'm using rq in conjunction with Django. In my Django application I've set `TIME_ZONE = 'UTC'`
and `USE_TZ = True`. This makes logging from within the Django application output as UTC. I could not find a way to tell RQ that I want to use UTC, so the logging output is mixed mess of UTC and my local timezone.

```
$ . .env && rqworker --name skyhawk_hunter high normal
03:26:08 RQ worker 'rq:worker:skyhawk_hunter' started, version 0.9.2
03:26:08 Cleaning registries for queue: high
03:26:08 Cleaning registries for queue: normal
03:26:08 
03:26:08 *** Listening on high, normal...
03:26:08 high: spdl.tasks.clear_queue() (35dd2262-281b-4943-b53b-ca63ee2c537e)
02:26:08 INFO Resetting application
02:26:08 INFO ---> Cleared 7 items from queue `normal`
02:26:08 INFO ---> Set all accounts to not busy
02:26:08 INFO ---> Set all active tracks to pending
02:26:08 high: Job OK (35dd2262-281b-4943-b53b-ca63ee2c537e)
02:26:08 Result is kept for 500 seconds
03:26:08 
03:26:08 *** Listening on high, normal...
03:26:18 normal: spdl.tasks.download_track('4fQC4KPuhs36tc0ze3rWf9') (ee670ed8-df76-46c7-ade8-36896bab927f)
02:26:18 INFO Worker acquired non-busy account
```

Is there a way to deal with this?

**Comment by selwin** [comment]
You should use https://github.com/ui/django-rq for this.

django-rq aside, I agree that RQ itself should support timezones. The first step would be modifying `Worker.__init__` to accept `tz` argument.

**Comment by antonagestam** [comment]
@selwin I've looked at django-rq and it seems like a good project but for this app it didn't seem to add any value. I want to keep things separate. I suspect this issue is not specific to Django though, and should probably not be solved in a way that is either.

Thanks for the hint, if I get the time I might do some experimenting with that!

**Comment by antonagestam** [comment]
It seems like setting the environment variable `TZ` fixed this, like Django does in https://github.com/django/django/blob/master/django/conf/__init__.py#L139

So maybe this is not a bug after all, just a symptom of Django setting `TZ`.

**Comment by selwin** [comment]
This is something you can configure in Python's logging mechanism. https://stackoverflow.com/a/6321221
