### ISSUE TITLE
Getting worker id from within running job?

### ISSUE THREAD

**Issue by eqy** [rq/rq#919]
I am trying to build a system that issues jobs to different hardware devices---some devices are identical and interchangeable, so they share a queue. For isolation, no job should be running concurrently with another job on the same device, which maps nicely to workers in rq. (One worker per device.)

However, it would be very convenient if I could inspect the name or other identifier of the worker currently running a job from within the job so that the job can dispatch itself to the correct hardware device. Is there currently a way to do this, or am I abusing/misunderstanding the preferred pattern?

Thanks

**Comment by samuelcolvin** [comment]
Best to have one queue per device type, then the worker running on each device only runs jobs from that queue.

Then you can decide which device type a job should be run on and enqueue it on that appropriate queue.

Does that work?

**Comment by eqy** [comment]
The issue is that there may be multiple devices for some device types where
it would make sense to process jobs concurrently. To do this it would be
convenient to determine which worker was executing a job so that a job
could dispatch itself to the correct device (workers would be assigned to
devices statically).
