### ISSUE TITLE
Best practice to set redis key prefix for all keys used by RQ

### ISSUE THREAD

**Issue by iperelivskiy** [rq/rq#920]
Hi,

After quick scan of the source code I determined that while base classes like Queue, Worker etc could be subclassed in order to override `redis_queue_namespace_prefix`, there is no way to control this code (except full method override which is strongly undesired):

```python
def empty(self):
    """Removes all messages on the queue."""
    script = b"""
        local prefix = "rq:job:"
        local q = KEYS[1]
        local count = 0
        while true do
            local job_id = redis.call("lpop", q)
            if job_id == false then
                break
            end

            -- Delete the relevant keys
            redis.call("del", prefix..job_id)
            redis.call("del", prefix..job_id..":dependents")
            count = count + 1
        end
        return count
    """
    script = self.connection.register_script(script)
    return script(keys=[self.key])
```

where prefix is just hardcoded.

Having this how subj can be achieved in best possible way? Thanks.

Looking ahead it would be very helpful to have this as some sort of a setting that will shine with `django-rq` when `KEY_PREFIX` may be used in `CACHES` setting definition.

**Comment by ivanperelivskiy** [comment]
Looking ahead that would be very helpful to have this as some sort of setting and will shine in `django-redis` when `KEY_PREFIX` may be used in `CACHES` setting definition.

**Comment by selwin** [comment]
Step 1 would be to modify places where prefix is hard coded to use `redis_queue_namespace_prefix` (since this is good practice anyway). This will at least allow people to easily override this via subclassing.

PR for this is welcome :)

**Comment by ohoushyar** [comment]
Hi, just wondering if this has been addressed completely? Is it possible to set prefix?
