### ISSUE TITLE
Q: What would happen if I press Control+C when worker is running?

### ISSUE THREAD

**Issue by aetherwu** [rq/rq#924]
I have a question about queue and workers in which docs does not specific clearly. (I've tried to go through it.)

What would happen to my queue? Would the queue still exist when 'rq worker' has been ended intentionally or accidentally?
If I run 'rq worker' again, could the queue resume working from where it was taking down?

I understand that I can try it out but I have 2w+ tasks running in queue ....

**Comment by samuelcolvin** [comment]
You should be fine, rq should wait for the current job to finish then terminate. If you do a "hard shutdown" (eg. hit Ctrl+C twice quickly) the current job will be terminated before it's finished.

Either way the jobs in the queue should be unaffected and processing them should resume when you restart the rq worker.

A bit of background: the "r" in rq stands for redis. Redis isn't part of rq, is a sophisticated in memory database with numerous [powerful data-structures](https://redis.io/topics/data-types) including lists (the "q" in rq) which rq uses. Redis runs independently of rq, it can be a seperate process on the same machine or running on another machine else where on the network.

When you enqueue a job with rq, all rq is really doing is [pushing](https://redis.io/commands/rpush) data about the job into one end of a list. When the worker "executes" the job, all it's really does is [pop](https://redis.io/commands/blpop) the job definition out of the other end of the list and "do it". If you stop the worker the list of jobs is still there waiting to be popped and processed.

Hope that makes sense.

**Comment by aetherwu** [comment]
Thanks a lot! I processed my queue safely. Hope this conversation could be useful for other users!

**Comment by Florents-Tselai** [comment]
@aetherwu have a look at [rq-dashboard](https://github.com/eoranged/rq-dashboard) too . 
Will give you a better picture of what's happening 

![image](https://user-images.githubusercontent.com/2118708/35376151-6d7ab7e0-01b2-11e8-9ee8-14a3b3251903.png)
