### ISSUE TITLE
move python-rq.org to the rq organisation and improve

### ISSUE THREAD

**Issue by samuelcolvin** [rq/rq#925]
@selwin @nvie I can't find where the python-rq.org site code is.

Can we keep the code in a separate repo in this organisation?

How is it currently hosted? Would it be a good idea to move the site to netlify or readthedocs so it can autodeploy on changes?

Also are we wedded to the design, would it be a good idea to move to a standard sphinx or mkdocs theme which might be easier to navigate?

**Comment by selwin** [comment]
The docs are hosted on [Github Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/). It's currently configured to auto publish whenever there's any change to `gh-pages` branch.

I'm ok with moving the docs to a separate repo if you think this will make contributions easier :). 

My personal preference is to try to restructure the docs to make it easier to navigate before moving to `mkdocs`.

**Comment by samuelcolvin** [comment]
Sorry, that was very dumb of me not to look at other branches. Still I think a separate repo with deploy via netlify would be much easier.

**Comment by selwin** [comment]
I'm ok with creating a dedicated repo. Can we keep using Github Pages for now? Deployment is already automatic and I'd rather have as little moving parts as possible.

**Comment by nvie** [comment]
I still own the domain name. Just ping me if I need to point it elsewhere for you 👍

**Comment by samuelcolvin** [comment]
gh-pages is fine with me, netlify has numerous cool features but perhaps not worth it at this point.

**Comment by selwin** [comment]
Just a quick update, I've also moved `rq-scheduler` into RQ's org. https://github.com/rq/rq-scheduler

**Comment by wshayes** [comment]
Another quick note - if you are adding a repo for the docs - Github now allows you to publish anything in the /docs folder of the master branch in Github Pages if you check that setting option in the repo settings - avoids the confusion around the gh-pages branch

**Comment by selwin** [comment]
@wshayes done. The website is now built from the `docs` folder from the master branch. This should make it more discoverable https://github.com/rq/rq/tree/master/docs

**Comment by selwin** [comment]
Closing this issue as fixed.
