### ISSUE TITLE
Batching work (i.e., same job, different arguments)

### ISSUE THREAD

**Issue by lukedeo** [rq/rq#928]
Hi all, 

Was wondering if rq supports the ability to chew on a batch of tasks at the same time in the same process. 

I.e., I am wondering if there is any way to have

```python
job1 = q.enqueue(count_words_at_url, 'http://nvie.com')
job2 = q.enqueue(count_words_at_url, 'http://cnn.com')
job3 = q.enqueue(count_words_at_url, 'http://foobar.com')
```

But inside the invocation to `count_words_at_url`, be passed all three urls at the same time. Something akin to the `batch` argument [here](https://github.com/closeio/tasktiger#task-options) in [TaskTiger](https://github.com/closeio/tasktiger). I'd like to stick to rq if possible.

Cheers

**Comment by samuelcolvin** [comment]
It's not possible, you need to either:
* run multiple works
* spawn new threads (or processes) inside a job
* use an asynchronous RPC library like [arq](https://github.com/samuelcolvin/arq)

(ng this as I hope I've answered the question, but feel free to follow up with more questions if you like.)
