### ISSUE TITLE
rq + flask on heroku. how to notify when job is done?

### ISSUE THREAD

**Issue by mateocam** [rq/rq#931]
I have an web app on heroku which does a long request, so I added the rq worker to send the request as a background task.

I want to notify the client/user of the web app when the background task is done. I've been trying to use something like this:

```
for job_id in q.job_ids:
	print job_id
```

but the problem is that once deployed on heroku I still get the timeout error because of the polling. 

How can I approach this?

Please help!!

**Comment by meowlz** [comment]
I have a similar setup...the very last thing my job does is notifying  the frontend via websocket that the task is finished.
