### ISSUE TITLE
For elastic worker mgmt, any advices? 

### ISSUE THREAD

**Issue by 61t** [rq/rq#933]
Thanks author for providing us rq as a simple and reliable job queue solution. 

I just went through the doc and did some function tests. Perfect for my project.  

Below are 2 concerns about my project, that need your advices of solution. 

# 1. elastic workers mgmt

I need to find a solution to dynamic manage/increase/decrease workers in a server and server numbers according to job workload base on cpu/io/mem. 

# 2. long running job mgmt

I can easily tell rq is working perfect for short term job from seconds to hours even days. But part of my jobs need long running job from days to might be forever. Also it also hits first question, as it need dynamic increase/decrease worker numbers in a servers or server numbers for these long running jobs. By the way, what's your thoughts about rq for long running jobs.

**Comment by samuelcolvin** [comment]
Autoscaling is outside the bounds of rq, it requires you to modify your
infrastructure - if you need to run thousands of concurrent jobs there's no
point in increasing the number of workers without providing more
hosts/cores.

Jobs should not run for a long time, it stops you restarting workers/
deploying etc. Any job longer than 10 seconds is vulnerable to cancellation
by worker shutdown. Instead split the tasks into multiple shorter jobs.

**Comment by 61t** [comment]
Thanks for your reply. I agreed with your advices about long running job. 

For autoscaling, actually I am trying to find another framework/project to integrate with rq. This feature for my project is more critical than long running job, as you said, I can split long job into small pieces. 

Any advices of autoscaling framework/project to work with rq worker?  

Also @nvie @selwin

**Comment by 61t** [comment]
If there is no easy solution for autoscaling. I am planning to write a script to increase/decrease workers from a server pool based on queue size that I think is a decent solution without that much effort.

**Comment by selwin** [comment]
I use systemd template units to temporarily increase/decrease workers.

I have a `rqworker@.service` definition which allows me to start more workers by calling `systemctl start rqworker@1.service`, `systemctl start rqworker@2.service` and so on.

**Comment by samuelcolvin** [comment]
At tutorcruncher we autoscale workers on heroku using hirefire.

**Comment by 61t** [comment]
Thanks @selwin @samuelcolvin 

They are good solutions to auto scale local and global respectively. 

Currently I am only focus on AWS and GCP. I checked with cloud platform auto scaling solution and satisfied by now for first stage evaluation. I will deep into that by hooking into perf metric with rq.Queue.count.

**Comment by selwin** [comment]
No worries :)
