### ISSUE TITLE
Workers dies unexpectedly - job not marked as failed  

### ISSUE THREAD

**Issue by Kriechi** [rq/rq#944]
Hi,

I'm having issues in my infrastructure that sometimes workers (i.e., their host machine) just randomly die or become permanently unavailable on the network). If the worker is currently processing a job, this causes the job to hang indefinitely.

This is different from the case when the work horse dies, in which case the job is correctly put into the failed queue, so I can manually requeue it later.

Workers already send a heartbeat, but apparently this only works in IDLE state, and not in BUSY.
Right now I have about 100 workers in my list that are BUSY - but in reality they don't exist any more.

Is it possible to restore those hogged jobs from the dead workers?
Is it possible to add a more reasonable heartbeat to the workers themselves (not work horses)?

Are there any strategies to reliably recover from my current predicament?

**Comment by selwin** [comment]
With regards to the failed jobs, as long as you have active RQ workers, they will periodically harvest these failed jobs and move them to `FailedQueue`.

Could you check whether "busy" worker keys have TTLs?

**Comment by Kriechi** [comment]
I do have active workers. But the default queue is empty, so nothing gets done.
The busy workers are dead, do not respond to pings, are are therefore lost.
I don't see any code that would do harvesting, as you describe it.
The worker heartbeat only sets an expire flag in redis, but not while they are busy...

**Comment by Kriechi** [comment]
Technically there are no "failed jobs". The jobs in question "are being worked on". 

I can see the `last_heartbeat` of the workers was back in March 23rd...
But they are not expiring by themself, and there is no active "manager" that would periodically check that sort of thing...

Maybe I should start a background thread to poll all workers, and manually expire them, and move their jobs into the failed queue?

**Comment by selwin** [comment]
Dead jobs are harvested here: https://github.com/rq/rq/blob/7a3c85f1854b72ed76573f421cca936f2b96937a/rq/worker.py#L480

Worker keys should have TTLs, even during job execution, set during `prepare_job_execution()`. Are you using custom workers by any chance?

**Comment by Kriechi** [comment]
No, I'm using the standard worker, started with `rq worker -u redis://10.10.10.42 -P /custom/mount/tmp`.

With regard to `clean_registries`:
I think my issue is that I have set a job timeout `timeout=2**31 - 1`, because my jobs run for multiple days (scientific computing tasks).

**Comment by selwin** [comment]
Ah ok, that's why.

Modifying`_monitor_work_horse_tick()` to periodically (every 10 seconds) send `heartbeat` will help. This way, we can change `prepare_job_execution()` to send heartbeats with low TTLs, regardless of job timeout.

https://github.com/rq/rq/blob/master/rq/worker.py#L625

Do you mind opening a PR for this? This may be a bit tricky to test properly though.
