### ISSUE TITLE
warning from sentry dsn parsing

### ISSUE THREAD

**Issue by houqp** [rq/rq#946]
Hi,

Looks like sentry is changing it's dsn parsing logic, would be nice to migrate to the new convention before they drop support for the current one.

The warning we got is:

```
/usr/local/lib/python3.6/site-packages/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
```

**Comment by selwin** [comment]
I'm experiencing this in my own projects as well. Haven't had the time to look into this. Help is appreciated :)

**Comment by samuelcolvin** [comment]
surely this makes sense, rq works best with `HTTPTransport` anyway.

So rq always uses `HTTPTransport` and just strips and ignores the transport in the dsn

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1045

**Comment by selwin** [comment]
Docs here: https://python-rq.org/patterns/sentry/
