### ISSUE TITLE
Quieten rq logs with custom worker

### ISSUE THREAD

**Issue by jonathan-kosgei** [rq/rq#958]
I've read about the `--quiet` option but I need to do this in the application.

My code looks like this;
```
    print('Starting Worker...')
    with Connection(rq_conn):
        qs = 'default'
        w = Worker(qs)
        w.work()
```

How do I configure the worker to not print logs?

**Comment by selwin** [comment]
We don't have an API for this yet. Would be happy to to accept a PR that allows for something like this `Worker(log_level='WARNING')`

**Comment by theodesp** [comment]
Hey if we allow this to happen then which logging_level should take precedence? The one on the constructor or the one on the `work` method?

**Comment by selwin** [comment]
Ah, I didn't realize that `work()` already accepts `logging_level` as an argument. We should document that. I'm closing this issue since this is already possible.
