### ISSUE TITLE
Passwords that contain "/" character cause problems in Redis URLs

### ISSUE THREAD

**Issue by martinpeck** [rq/rq#960]
If I try and use a REDIS_URL, and within that url I have a password that looks like this...

```python
redis_url = 'rediss://:F6tM/t41SZ/c57sr2KFt0=@myredis.example.com:6380/0'
```

... (notice that it has two `/` characters) then I see a connection error as the url is not parsed correctly.

The underlying package `redis-py` supports URLEncoding/Decoding of connection urls, but it's something that requires code changes (it requires an additional parameter when making the connection). e.g...

```python
client = redis.Redis.from_url(redis_url, decode_components = True)
```

To make use of this ability, the following code would need to be altered to use the `decode_components` parameter:

https://github.com/rq/rq/blob/2bc2f447d31aa955bbd77c16873768e442f32031/rq/cli/helpers.py#L39-L40

Is it reasonable that `rq` should make a change so that it uses `decode_components = True` in all situations or, to preserve the current behaviour, is is reasonable to add an additional ENV variable (e.g. `CACHE_REDIS_ENCODED_URL` to specify an encoded URL, or `CACHE_REDIS_DECODE_URL` set to `True` if decoding should occur)? If so, I'm happy to provide a PR.

**Comment by blueyed** [comment]
Not really required anymore according to https://github.com/okpy/ok/issues/1279#issuecomment-401888936.

**Comment by martinpeck** [comment]
You're right that this isn't required for okpy. However, is there any benefit in adding this support to prevent this being a problem for others? I'm happy to close this if the answer is "no", or supply a PR if "yes"

**Comment by martinpeck** [comment]
This hasn't got traction, and the related issue has been resolved, so I'm going to close this now.
