### ISSUE TITLE
expiring failed jobs

### ISSUE THREAD

**Issue by samuelcolvin** [rq/rq#964]
from #921 @selwin said:

> We can then release version 1.0 which is backwards incompatible with earlier versions. With this version, I want to also convert `FailedQueue` to `FailedJobRegistry` which scales a lot better to a large number of jobs. 

The failed jobs queue is really weird and I would guess not needed by most users.

At TutorCruncher we recently found 60% of redis filled with failed jobs from the last two years. Just sitting in the queue. We now run a job every 3 hours to empty the failed queue.

I'm not sure what the original reason for the failed queue was, but we (and I would guess most people) just log the exception to sentry and have no need for the failed queue.

It would be great if there was a way to completely disable the failed queue or have jobs expired after a given period of time. Thoughts?

**Comment by selwin** [comment]
[This branch](https://github.com/rq/rq/tree/failed-job-registry) contains an implementation of `FailedJobRegistry`. The `FailedJobRegistry` is fully implemented, I'll just need to delete `FailedQueue` before it's ready for merging.

This branch already allows you to:
1. Automatically expire failed jobs after a variable amount of time by doing `Worker(failed_job_ttl=3600)`
2. Disable the default exception handler by doing `Worker(disable_default_failure_handler=True)`

In all my projects at work, we log failed jobs to Sentry for alerting purposes, but with having a registry of failed jobs allows you to quickly requeue jobs with a GUI based tool like [django-rq](https://github.com/rq/django-rq). So for us, they serve different purposes.

Having said that, in 1.0 you'll be able to easily disable the default failure handling mechanism if you don't need it :)

![django site admin 2018-06-06 21-44-15](https://user-images.githubusercontent.com/188658/41045560-cb422bf0-69d2-11e8-9f66-c4700c48f428.jpg)

**Comment by sochi** [comment]
Reading the comments above, and seeing that RQ 1.0 is released already.. there is no `failed_job_ttl` argument implemented for `Worker`.
According to the documentation this seem to be instead done differently as a `failure_ttl` parameter to `enqueue` call: http://python-rq.org/docs/jobs/

Note the documentation also states that failed jobs are kept for 1 year by default. And personally I am not sure that this is actually true as the `failure_ttl` defaults to `None`.. it might be hidden somewhere around though :-)

**Comment by selwin** [comment]
Currently `failure_ttl` is passed via `Queue(failure_ttl=...)` or `queue.enqueue(failure_ttl=...).

The default `failure_ttl` is [1 year](https://github.com/rq/rq/blob/master/rq/registry.py#L169).

I'm closing this issue since this feature is already released.

Please open a PR if you need to pass `--failure-ttl` via `Worker`.

**Comment by sauravmahuri2007** [comment]
@selwin , @samuelcolvin,

I was using Augusto Men's answer as mentioned in [How to clear Django RQ jobs from a queue?](https://stackoverflow.com/questions/18104563/how-to-clear-django-rq-jobs-from-a-queue) to get and delete failed jobs. After upgrading to **django-rq==2.1.0**, I had to use **FailedJobRegistry** from rq.registry as django_rq.**get_failed_queue** has been removed. The newer code looks something like this:

```
from django_rq import get_queue
from rq.registry import FailedJobRegistry

failed = FailedJobRegistry(queue=get_queue())
while True:
    failed_job = failed.dequeue()
    if not failed_job:
        break
    failed_job.delete()
    failed.empty()
```

But this is giving AttributeError:
    
```
failed_job = failed.dequeue()
AttributeError: 'FailedJobRegistry' object has no attribute 'dequeue'
```

looks like *dequeue* has been removed. Could you please help me to write the proper way to use **FailedJobRegistry**. Thanks in advance..

**Comment by JaakkoRoponen** [comment]
@sauravmahuri2007 

I used the raw connection to iterate over rq:job keys and deleted failed:

```
from django_rq import get_connection
from rq.job import Job

# delete failed jobs
con = get_connection('default')
for key in con.keys('rq:job:*'):
    job_id = key.decode().replace('rq:job:', '')
    job = Job.fetch(job_id, connection=con)
    if job.get_status() == 'failed':
        con.delete(key)
con.delete('rq:failed:default')  # reset failed jobs registry
```

**Comment by selwin** [comment]
I'll add `failed_job_registry.delete(job_id)` in the next release to make this more convenient.

**Comment by sauravmahuri2007** [comment]
@JaakkoRoponen ,

Thanks for your comment. I didn't try this as I've already found a way and committed my code last week. This is what I coded adapting **FailedJobRegistry**:
```
from django_rq import get_queue
from rq.registry import FailedJobRegistry

failed_registry = FailedJobRegistry(queue=get_queue())
    jobs_id = failed_registry.get_job_ids()
    for job_id in jobs_id:
        job = q.fetch_job(job_id)
        if job.is_failed: # I think this check is not needed as FailedJobRegistry may have only the failed jobs. Just to confirm, I added this condition.
            job.delete()
```

**Comment by jbarham** [comment]
I've created a Django management command to do bulk deletes of failed jobs from Django RQ. The gist is [here](https://gist.github.com/jbarham/de89f85e900bf5f3adce3f0e4d65c5d9).
