### ISSUE TITLE
Profiling RQ workers

### ISSUE THREAD

**Issue by rith87** [rq/rq#965]
We've recently seen our python RQs build up, probably because of recent code changes. I was wondering if there was a way to profile these RQ workers and perhaps get the following information:

- Number of times worker has performed each job
- Average time for each job
- If possible, a lower level breakdown by function of each job

Initially, I was thinking to use python's cProfile but that doesn't really work since the RQ workers do their jobs in a new process. The other thing I could try is to log start and end times for each job and write some script to parse the logging.

Any other ideas?

PS: Not sure if it matters but we're using python RQ via flask RQ.

**Comment by selwin** [comment]
The first two metrics you're looking for are already built in. Workers in RQ >= 0.9 keep track of the number of jobs they perform and the amount of time they spend working. 

Checkout the docs [here](http://python-rq.org/docs/workers/), under `Worker statistics`.

We don't yet have the breakdown on a per job basis.
