### ISSUE TITLE
Q: redislab outage hangs workers

### ISSUE THREAD

**Issue by cgthayer** [rq/rq#966]
Redis Labs had an outage a couple of days ago, which resulted in a lot of our rq workers just hanging. They run in a loop with an exception handler, but we didn't seen them exit/return or raise. Seems like some heartbeating isn't quite working.

(perhaps the fix for this could also solve https://github.com/rq/rq/issues/787 ?)

Code looks like this. Is there anything we should do differently to improve reliability? We have a custom implemented ping-er, which caught the issue for us, but I imagine many people don't have something similar.

PS. detecting and dying is fine with us.

```
    def listen(self):
        client = Client(self.sentry_dsn, transport=HTTPTransport)
        num = 0
        while True:
            current_name = self.name if num == 0 else f'{self.name}-{num}'
            self.redis = StrictRedis.from_url(self.url)
            try:
                with rq.Connection(self.redis):
                    logger.info(f'Listening on {self.topic}, press Ctrl+C to exit.')
                    self.worker = rq.Worker(self.topic, name=current_name, exception_handlers=[self._exception_handler])
                    # should run forever
                    did_work = self.worker.work()
                    logger.info(f'Worker exited? did_work={did_work}')
            except KeyboardInterrupt as exc:
                print(f'Worker caught control-c, exiting: {exc}')
                break
            except Exception as exc:
                client.captureException()
                logger.info(f'Worker caught exception, restarting: {exc}')
            time.sleep(3)
            num += 1
        return
```

**Comment by cgthayer** [comment]
I see that we create our self.redis from `StrictRedis.from_url(self.url) ` and that there may be some options to redis that would resolve this. Namely, we may be able to pass in `socket_keepalive=True
` so that even if the worker stops receiving it can actively check that the connection is up.

https://redis-py.readthedocs.io/en/latest/_modules/redis/connection.html?highlight=socket_keepalive

**Comment by cgthayer** [comment]
Seems like I may be the only one experiencing this... maybe this is a bad interaction with another library.

**Comment by jwnx** [comment]
I believe I may be experiencing this same problem with redislab. Heartbeating doesn't seem to work after a while and a few days ago, an outage stuck all my jobs despite having workers available.

@cgthayer have you found any solution to this?

**Comment by cgthayer** [comment]
@jwnx Sadly we have a work-around but not a fix. It's possible that it's rq, redis, or GKE (google kubernetes engine). The google layers may be doing something with the network layer that we're not aware of.

We tried adding keepalives, but that didn't help, so we use socket_timeout=300 now. If our worker (the listener) doesn't get any request for 5 mins we assume it's hung and just let it raise an exception which causes our code to reconnect. This works okay for us because we have a bunch of k8s pods. Here are some quick snippets.

```
timeout = random.randint(600, 600 + 60)
redis = StrictRedis.from_url(app.config['REDIS_URL'], socket_timeout=timeout)

redis_conn = Redis(host=redis_host, port=redis_port, password=settings.redis_password, socket_timeout=timeout)

self.connection = StrictRedis.from_url(url, socket_keepalive=True, socket_timeout=300)

```
More about the networking code / options:  https://gitlab.cs.washington.edu/sampa/redis/blob/master/redis-py/build/lib/redis/connection.py#L386

**Comment by selwin** [comment]
So I tried to simulate RQ's behavior during Redis connection failures. When Redis outage happens when worker is listening for jobs, it will terminate properly.

![1 bash 2018-09-15 09-09-30](https://user-images.githubusercontent.com/188658/45581399-6ce8d100-b8c7-11e8-8808-d15aa6f0dc3c.jpg)

However, if connection is interrupted when a worker is in the process of running a job, it loops indefinitely, so this is what we need to fix. It should detect that it can't connect to Redis (catches Redis related exceptions) and terminates immediately.

It would be great if someone can open a PR for this.

**Comment by selwin** [comment]
This should be fixed in these commits: https://github.com/rq/rq/compare/cc19d1a89eab77ff25522a5b51c258798e620190...e00ff978676ba45d1e96f0d44129ef543cc7a9d3
