### ISSUE TITLE
RQ for parallelization? How many workers should I spawn? Documentation?

### ISSUE THREAD

**Issue by meowlz** [rq/rq#968]
Hi in our setup we use rq to paralellize our computations. Is there a rule of thumb how many workers one should spawn for optimal performance?

E.g. How many workers should be spawned on a quad core computer with hyper threading?

Unfortunately I did not find anything in the rq docs about it.

http://python-rq.org/docs/workers/

**Comment by theodesp** [comment]
Regarding this question, I suggest you investigate the effects of either Amdahl's or Gustafson law. It's not something we can answer straight away as it depends on many factors.
