### ISSUE TITLE
"async" function argument causing SyntaxError since Python3.7

### ISSUE THREAD

**Issue by Madi7** [rq/rq#972]
In rq/queue.py:

    def __init__(self, name='default', default_timeout=None, connection=None,
                 async=True, job_class=None):
        ...

Python3.7's release note:

    Backwards incompatible syntax changes:

        async and await are now reserved keywords.

**Comment by blueyed** [comment]
Fixed in https://github.com/rq/rq/commit/c2b939d2df7df2bd0a6e5a73823a07baecc17895.

**Comment by regan-karlewicz** [comment]
Any idea when there will be a release to fix this?

**Comment by selwin** [comment]
Version 0.12 is now on PyPI https://pypi.org/project/rq/
