### ISSUE TITLE
Integration with dd-trace

### ISSUE THREAD

**Issue by cfingerh** [rq/rq#974]
I'm using python rq in Django project and I use Datadog to monitor. I would like to be able to trace the jobs using the datadog APM tracer ( https://github.com/DataDog/dd-trace-py ). Has somebody tried it?

I think one option would be to append to the executing command of each job "ddtrace-run" ...

**Comment by selwin** [comment]
I think the best way to implement this would be to write your own `Worker` class that sends stats to DataDog as needed.

If you decide to publish this, feel free to leave a comment and I'll put a link to it in the docs.
