### ISSUE TITLE
Release v0.12

### ISSUE THREAD

**Issue by kitsuyui** [rq/rq#978]
Hi, Our team are looking forward to use rq with the new version of Python.

We know that we can use it already by pip with git installation. However PyPI release is more convenient.

When is the release date of the next version?

**Comment by regan-karlewicz** [comment]
+1

**Comment by cheeseandcereal** [comment]
+1

**Comment by selwin** [comment]
Version 0.12 is now on PyPI https://pypi.org/project/rq/

**Comment by kitsuyui** [comment]
Thank you so much!
