### ISSUE TITLE
Document pattern for multiple workers via systemd

### ISSUE THREAD

**Issue by anseljh** [rq/rq#981]
Hello! I'm wondering if there's a solid pattern people are using for starting up multiple workers under systemd. I'm happy to help write up a page for the docs if there is.

**Comment by selwin** [comment]
I run multiple RQ instances via systemd template unit files. I have a template named `rqworker@.service` which allows me to spin up additional workers by calling `systemctl start rqworker@one.service`, `systemctl start rqworker@two.service` etc.

All of them can also be reloaded by calling `systemctl reload rqworker@*`.

More about systemd template unit files here: https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files

If you can, please open a PR for this.

**Comment by anseljh** [comment]
Thanks! That's the solution I ended up on as well, so it's nice to have some validation. I will open a PR, but probably won't get to it for a few weeks.

**Comment by MeteHanC** [comment]
> I run multiple RQ instances via systemd template unit files. I have a template named `rqworker@.service` which allows me to spin up additional workers by calling `systemctl start rqworker@one.service`, `systemctl start rqworker@two.service` etc.
> 
> All of them can also be reloaded by calling `systemctl reload rqworker@*`.
> 
> More about systemd template unit files here: https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files
> 
> If you can, please open a PR for this.

Hey,

Can you please share your systemd service file? Thanks in the advance

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/commit/065943f0b46955257dee6208f50b45b5c24d014e
