### ISSUE TITLE
Queue.job_ids is Always Empty

### ISSUE THREAD

**Issue by jerryji** [rq/rq#984]
My simple job tasks run fine, however, none of the functions to get all the jobs on queue works --

$ pip3 freeze | egrep -i "rq|redis"
redis==2.10.6
rq==0.12.0

$ flask shell
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
App: app [production]
Instance: .../flask/instance
>>> from redis import Redis
>>> import rq
>>> q = rq.Queue('example-rq', connection=Redis.from_url('redis://'))
>>> job = q.enqueue('app.tasks.example', 100)
>>> job.get_id()
'93c0e279-3ce7-48c6-8f97-ace8a29ada70'
>>> q.job_ids
[]
>>> q.get_job_ids()
[]
>>> q.jobs
[]

What could be wrong?

BTW, github code formatting sucks, but my [SO question](https://stackoverflow.com/questions/51573566/python-rq-queue-job-ids-always-empty) is not getting any answer or many views.

**Comment by jerryji** [comment]
I did some tracing in Redis and observe the following:

keys after "rq worker example-rq" --

127.0.0.1:6379> keys * 
1) "rq:worker:FalconX.4952"
2) "rq:workers:example-rq"
3) "rq:workers"

keys after "job = q.enqueue('app.tasks.example', 100)"

127.0.0.1:6379> keys * 
1) "rq:workers:example-rq"
2) "rq:job:50d7edbc-3e73-4d63-b473-72696a993ec3"
3) "rq:wip:example-rq"
4) "rq:worker:FalconX.4952"
5) "rq:workers"
6) "rq:queues"

The "rq:queue:example-rq" does not exist --

127.0.0.1:6379> SMEMBERS rq:queues
1) "rq:queue:example-rq"

127.0.0.1:6379> type rq:queue:example-rq
none

After example() completes --

127.0.0.1:6379> keys * 
1) "rq:workers:example-rq"
2) "rq:job:50d7edbc-3e73-4d63-b473-72696a993ec3"
3) "rq:worker:FalconX.4952"
4) "rq:finished:example-rq"
5) "rq:workers"
6) "rq:queues"


I'm puzzled why "rq:queue:example-rq" has been put in "rq:queues" but still does not exist. Any pointer will be much appreciated.

**Comment by jerryji** [comment]
It seems the rq:queue:example-rq is popped right away, is there a way to get the current running job of a particular queue?

**Comment by selwin** [comment]
All active jobs are stored in `StartedJobRegistry`. Here's an example:
```python
from rq.registry import StartedJobRegistry

queue = Queue()

registry = StartedJobRegistry(queue=queue)
print(registry.get_job_ids())  # This prints out a list of running jobs
```

If you can, please open a PR to document this.

**Comment by jerryji** [comment]
Thanks for the reply! 

Could you please confirm that all the queued jobs are in BaseRegistry?

i.e.,  `set(BaseRegistry(queue=queue).get_job_ids()).union(set(StartedJobRegistry(queue=queue).get_job_ids())) ` returns _all_ the jobs that are running or will run?

**Comment by selwin** [comment]
No, enqueued jobs are stored in queues themselves. The APIs are similar though, you can do:
```python
queue = Queue()
queue.get_job_ids()
```
