### ISSUE TITLE
Task queue empties itself after 1 or two days?

### ISSUE THREAD

**Issue by wessm** [rq/rq#988]
I have a weird issue, and being a beginner in python, I have no idea where to start debugging, so maybe someone can point me in the right direction:

I am using RQ and RQ dashboard on an AWS instance (running in docker) to control a bunch of workers (~10-15) on the same machine (also in separate docker containers). Everything works, I queue my tasks and the workers start to execute them. But after some time (around 10 hours to two days), RQ-Dashboard shows empty task queues and does not show any workers any more. I know the tasks can't be finished, and also I see the worker processes still running idle, but nothing gets executed. I set really high timeouts on my jobs (around 3 days or something), but I don't think it is a timeout issue, since all the queues seem to be empty. Also, I usually have a few jobs that failed, but after this magical "reset" the failed queue also shows as empty in RQ dashbord.

What I tried: I checked the logs of the RQ server (``docker logs rq-server``), but that shows nothing except the occasional ``saved DB to disk`` message. redis-cli ``KEYS *`` shows the workers, but no jobs. What would be the next step to figure out the cause of this issue?
Thanks!

**Comment by wessm** [comment]
Nevermind, I figured it out: Altough the sysadmin told me otherwise, the port of the redis db was open to the public, and having no password set, the DB was getting flushed by people wanting to use my server to mine bitcoins :-)

**Comment by ian-axelrod** [comment]
LOL. Great ticket.

**Comment by abriosi** [comment]
Actually I have had the same problem except I know that my server is secure. I can't seem to find any logs that tell me what happened. The queues just became empty and I'm sure there are no job time restrictions
