### ISSUE TITLE
Worker Death Registration Question/Issue?

### ISSUE THREAD

**Issue by bemcdonnell** [rq/rq#990]
Hey all, fantastic tool here. I've been using `rq` for several months now to deploy heavy simulations off to AWS-EC2.  I've managed to pull together an infrastructure which leverages `rq` and `boto3`.   Along the way I have had some challenges with different failures and so now I'm working to harden up the code base and to make it less prone to failures.. and making it self correct.   I am having two issues and I believe I've isolated them to `Worker.register_death()`.  The issue could be me... I'm fully aware of this possibility.

Before enqueuing my list of jobs, I keep them save in what you might call a backup list (stick a pin in this, i'll come back to it).  

In one of my failure cases my entire queue is lost and all my workers are disconnected (observed from rq-dashboard).  In the event something compromises the queue (whether it be my own error or something wrong on the redis-server), I auto-correct this by:
1. emptying the queue (which I believe is deleting the jobs), and
2. With the following block I register the worker's death and reboot my worker nodes

```python
    def reboot_workers(self):
        # get workers on queue
        print("Rebooting Workers")
        self.register_worker_death()
        if self._workers:
            for instance in self._workers:
                instance.reboot()

    def register_worker_death(self):
        print("Attempting to Register Worker Deaths")
        queue = Queue(REDIS_QUEUE_NAME, connection=self._connection)
        workers = Worker.all(queue=queue)
        for worker in workers:
            worker.register_death()
        time.sleep(15) #I Have tried a longer wait too
```

After rebooting, the workers reconnect themselves to the queue and begin checking out jobs.  

Here's the problem... It seems that when I register the worker death, they are still lurking around as zombie workers.  I've researched the GH issues tab and found some alternatives to kill the zombies ("Rule# 2 Double Tap" Reference to the movie Zombieland starring Emma Stone) but I wonder if there is something else I might be missing... Like a simple refresh somewhere?  So what happens next is that I enqueue a *new* job list (which is the same as the old one but does not use the same job IDs) and as soon as I enqueue these jobs, the workers that I registered deaths on either (a) checkout the job and execute it or (b) start the job and never complete it. 

I have a function that essentially polls all the jobs and checks their status.  Once they are all complete, it exits cleanly.  Here is my polling loop (polled every 5 seconds)
```python
for ind, job in enumerate(self._jobs):
    print(ind, job.id, job.is_finished, job.result, job.get_status(), self._job_results[ind])
```

here is an example of case (a):

```
Minutes: 0.94     JOBS 20   queued: 1    started: 1    finished: 18   failed: 0   
0 efda6df8-6ba0-4fb7-9dc7-93031c94347d True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- Workers were still "on" 
1 f8500c50-a521-4b53-8463-3e909ebe95cb True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<-
2 93e805db-b291-4cff-8544-25a61f554985 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<-
3 4a3ee4d8-21d6-4d93-b3c5-babd63c7a98f True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<-
4 00c6c052-f97c-4e39-8bf5-8588719d8118 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<-
5 1066a7f8-4b29-4b9f-acb4-8f8c902ad429 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<-
6 52ea2953-5f31-41bf-b4fc-52d6d5bc96a2 False None queued Queued #<- perhaps checked out, never completed
7 4b5f3f1c-4cac-4de3-af67-2dbd077044e8 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- New worker did this
8 9c907265-f823-46fb-9669-dfa8d2491138 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- New worker did this
9 d0efe0c6-776d-4322-9a70-4d547e6a4621 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- New worker did this
10 6da05530-8481-4de3-8862-26c7b43692bd False None started Queued #<- perhaps checked out, never completed
11 c94af890-8b6b-407d-8306-b8929ac828b7 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- New worker did this
12 f61c3a68-a030-4cbc-8de1-8ad413de0945 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- New worker did this
13 89528ed1-e376-4374-bca8-99d263e85d34 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- New worker did this
14 63966e37-d92b-4af2-9e65-45d0451bb2b7 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5 #<- New worker did this
15 eec1fdf8-28a8-4999-909f-54bd0880e539 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
16 3be04ddd-6fa4-4b54-b022-1ef8695b128a True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
17 fa507a50-ca0c-4db1-bf38-d56a3dba2c3a True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
18 07131b70-84d5-4390-9d7b-b86a476f2ce3 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
19 eabe55e1-0d34-42cb-9999-5ea584976fa6 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
```

Here is an example of case (b):
```
Minutes: 3.6      JOBS 20   queued: 4    started: 0    finished: 16   failed: 0   
0 f2539d55-ce45-45f2-b852-e5fdb141db4c False None queued Queued #<- These were checked out be supposedly dead workers
1 ff089c8e-d30b-4bd6-a230-3cd2becdef46 False None queued Queued
2 7b8ecfc8-697a-4681-a2cd-764f281e0e43 False None queued Queued
3 328faf22-6c32-491a-8bdb-2bd69dd29977 False None queued Queued
4 b18fe0f9-a4f7-47b9-bf65-482d20fac903 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
5 6326d985-d6d4-4ca2-8331-e36beab8e91f True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
6 28fd64fe-d684-461f-90a2-9da50aab56e5 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
7 acb5e092-f4b0-418e-a61c-9d3c4d7dc920 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
8 1b308820-e0dd-4dd3-9d27-4fe437a6d0fa True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
9 473b2573-9bbc-4ee1-a423-e95c54bf2b5b True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
10 264400f6-5a52-46a0-b49f-4904dd28d729 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
11 3a454eac-ee23-47fc-b483-e17cc62e50ce True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
12 eb738daf-22a4-4647-ad53-1acbf160e81b True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
13 7c11e687-b03d-478c-a9c0-9ccc0b1efada True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
14 de4d1f7d-4836-42a2-86fc-4c4203167a1d True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
15 e7ef85a3-9b27-4e56-9e43-667577ca1f24 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
16 bac2adff-9666-4d5a-9b79-a498d4d2e4ee True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
17 b995abc0-807b-4c1b-b397-11960099f62f True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
18 1e8bde4a-9839-4bd4-843f-79d3874a26ff True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
19 ed917f55-92c6-4edb-92d6-4e50f80f15c0 True h_1_i_2_j_3_k_4_l_5 finished h_1_i_2_j_3_k_4_l_5
```

I spent some time looking at the specifics here of `Worker.register_death()`.   I see a process expire of 60. I've tried waiting more that 60 seconds for the death registration to propagate through all the places.. Meanwhile I have a separate script that I am running to check if any workers are registered and it shows the "old" ones are not registered while all this is take place.  

Code from `worker.py:Worker`
```python
    def register_death(self):
        """Registers its own death."""
        self.log.debug('Registering death')
        with self.connection._pipeline() as p:
            # We cannot use self.state = 'dead' here, because that would
            # rollback the pipeline
            worker_registration.unregister(self, p)
            p.hset(self.key, 'death', utcformat(utcnow()))
            p.expire(self.key, 60)
            p.execute()
```

Any new thoughts on how I might double tap these zombies to really ensure they are not going to interfere with my simulation business?

**Comment by selwin** [comment]
If you want to kill the workers, you shouldn't call `worker.register_death()` directly - this only deletes the worker key from Redis and does not actually kill the worker process.

The proper way to take down workers is to send it a SIGTERM signal (`ctrl-c` if you're running the worker from a terminal) and they'll cleanup after themselves.
