### ISSUE TITLE
missing the logging/date formatting option from version 0.12.0?

### ISSUE THREAD

**Issue by fuzzyami** [rq/rq#992]
hai there and thank you for this immensely useful lib. much obliged!

I was hoping to set the date-format with the recently added flag, however, it appears to be missing from version 0.12.0:

```
root@ip-10-0-0-180:~# rq --version
rq, version 0.12.0
root@ip-10-0-0-180:~# rq worker --logging_level
Error: --logging_level option requires an argument
root@ip-10-0-0-180:~# rq worker --date-format
Error: no such option: --date-format
root@ip-10-0-0-180:~# rq worker --log-format
Error: no such option: --log-format
```

**Comment by selwin** [comment]
The date format logging option was pulled in after 0.12 was released so you'll have to wait until the next release to use this option. You can use RQ's master branch if you need this feature immediately.
