### ISSUE TITLE
Worker arguments --log-format can use?

### ISSUE THREAD

**Issue by duzhipeng** [rq/rq#999]
When I read the document,I found that '--log-format' in Worker arguments on page 'http://python-rq.org/docs/workers/' , but when I try 'rq worker --log-format'% (asctime) s% (message) s', prompt 'Error: no such option:--log-format'.

What's more, running'rq worker-help' doesn't exactly match the documentation.

So is the document not up to date or is it something else? It feels like there's a lot of confusion in the document.
Rookie from Celery, confused.

**Comment by selwin** [comment]
The `--log-format` cli option is currently only available in the master branch. Aiming to ship a new version sometime in the next few weeks. Sorry for the confusion.
